Repository ovh/docs, pull requests merged in 2024-05, with the labels that each got.

#6282 SK1532 - How-to-associate-a-domain-name-with-a-squarespace-hosting - TRANSLATIONS
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.de-de.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.en-asia.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.en-au.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.en-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.en-gb.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.en-ie.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.en-sg.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.en-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.es-es.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.es-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.fr-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.fr-fr.md
  pages/web_cloud/domains/how_to_connect_domain_to_shopify/guide.pl-pl.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.de-de.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.en-asia.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.en-au.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.en-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.en-gb.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.en-ie.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.en-sg.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.en-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.es-es.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.es-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.fr-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.fr-fr.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.it-it.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.pl-pl.md
  pages/web_cloud/domains/how_to_connect_domain_to_squarespace/guide.pt-pt.md
Labels: translations only

#6293 KevS-SK1534-KFT0016587-Update-How-to-create-a-shared-database-for-WebHosting
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-fr.md
Labels: KFT, Minor update

#6303 Network - Load Balancer - Fixing typos
  pages/network/load_balancer/use_api_reference/guide.en-asia.md
  pages/network/load_balancer/use_api_reference/guide.en-au.md
  pages/network/load_balancer/use_api_reference/guide.en-ca.md
  pages/network/load_balancer/use_api_reference/guide.en-gb.md
  pages/network/load_balancer/use_api_reference/guide.en-sg.md
  pages/network/load_balancer/use_api_reference/guide.fr-ca.md
Labels: fix

#6302 S3 Object Storage - S3 compliancy - added presigned urls details
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.pt-pt.md
Labels: Minor update

#6291 BrenKT-QF-150524-WEB-Email-MXplan-Outlook-windows
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_outlook_2016/guide.pt-pt.md
Labels: fix, KFT

#6298 KevS-SK1536-KFT0016413-Update-Manual-installation-Drupal-for-WebHosting
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.de-de.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-asia.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-au.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-gb.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-ie.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-sg.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-us.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.fr-fr.md
Labels: KFT, Minor update

#6307 FR update overthebox version matrix
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
Labels: Minor update

#6308 Public Cloud Databases - Capabilities - Update
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.de-de.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-au.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-us.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.es-es.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.es-us.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.it-it.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.pt-pt.md
Labels: Minor update

#6313 KevS-SK1538-KFT0015769-Update-Outgoing-transfert-for-DomainDNS
  pages/web_cloud/domains/transfer_outgoing_domain/guide.fr-ca.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.fr-fr.md
Labels: KFT, Minor update

#6317 SAP Logs - Links and formats fixes
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_analyze_and_work_with_your_logs/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_analyze_and_work_with_your_logs/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.pt-pt.md
Labels: fix

#6316 SAP logs - Syntax fixes
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.pt-pt.md
Labels: fix

#6318 SAP Logs - Fix markdown
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.pt-pt.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.pt-pt.md
Labels: fix

#6320 SAP Logs - fix: syntax
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_index_of_sap_logs/guide.pt-pt.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_logs_on_ovhcloud_logs_data_platform_solution_setup/guide.pt-pt.md
Labels: fix

#6306 KevS-SK1536-KFT0016413-Update-Manual-installation-Drupal-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.de-de.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-asia.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-au.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-gb.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-ie.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-sg.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.en-us.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.es-es.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.es-us.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.fr-fr.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.it-it.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.pl-pl.md
  pages/web_cloud/web_hosting/cms_manual_installation_drupal/guide.pt-pt.md
Labels: translations only, KFT, Minor update

#6315 KevS-SK1538-Update-Outgoing-transfert-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/transfer_outgoing_domain/guide.de-de.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.en-asia.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.en-au.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.en-ca.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.en-gb.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.en-ie.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.en-sg.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.en-us.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.es-es.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.es-us.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.it-it.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.pl-pl.md
  pages/web_cloud/domains/transfer_outgoing_domain/guide.pt-pt.md
Labels: translations only, KFT, Minor update

#6319 KevS-SK1539-KFT0015523-Update-CRON-task-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/cron_tasks/guide.de-de.md
  pages/web_cloud/web_hosting/cron_tasks/guide.en-asia.md
  pages/web_cloud/web_hosting/cron_tasks/guide.en-au.md
  pages/web_cloud/web_hosting/cron_tasks/guide.en-ca.md
  pages/web_cloud/web_hosting/cron_tasks/guide.en-gb.md
  pages/web_cloud/web_hosting/cron_tasks/guide.en-ie.md
  pages/web_cloud/web_hosting/cron_tasks/guide.en-sg.md
  pages/web_cloud/web_hosting/cron_tasks/guide.en-us.md
  pages/web_cloud/web_hosting/cron_tasks/guide.es-es.md
  pages/web_cloud/web_hosting/cron_tasks/guide.es-us.md
  pages/web_cloud/web_hosting/cron_tasks/guide.it-it.md
  pages/web_cloud/web_hosting/cron_tasks/guide.pl-pl.md
  pages/web_cloud/web_hosting/cron_tasks/guide.pt-pt.md
Labels: translations only, KFT, Minor update

#6322 HDS guarantees - Minor fixes
  pages/account_and_service_management/account_information/hds_garanties/guide.fr-fr.md
Labels: fix

#6321 BrenKt-QF-WEB-Domain-ZoneDNS-edit-160524
  pages/web_cloud/domains/dns_zone_edit/guide.de-de.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_edit/guide.es-es.md
  pages/web_cloud/domains/dns_zone_edit/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_edit/guide.it-it.md
  pages/web_cloud/domains/dns_zone_edit/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_edit/guide.pt-pt.md
Labels: translations only

#6323 KFT00016573 - Manage VoIP services
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_cancel_services/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/voip/changer_l_offre_et_les_options_d_une_ligne_voip/guide.fr-fr.md
Labels: KFT

#6325 IAM policies - YouTube video integration (FR only)
  pages/account_and_service_management/account_information/iam-policy-ui/guide.fr-ca.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.fr-fr.md
Labels: Minor update

#6324 KevS-SK1541-KFT0014502-Update-Create-a-shared-database-for-WebHosting
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-fr.md
Labels: KFT, Minor update

#6326 KevS-SK1542-KFT0014978-Update-How-to-connect-in-FTP-on-your-WebHosting
  pages/web_cloud/web_hosting/ftp_connection/guide.fr-ca.md
  pages/web_cloud/web_hosting/ftp_connection/guide.fr-fr.md
Labels: KFT, Minor update

#6300 Hbi traduction EN de la fiche specification securité SNC
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.de-de.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.en-asia.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.en-au.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.en-ca.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.en-gb.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.en-ie.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.en-sg.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.en-us.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.es-es.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.es-us.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.fr-ca.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.it-it.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.pl-pl.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-SNC/guide.pt-pt.md
Labels: translations only

#6330 KevS-SK1542-KFT0014978-Update-Connecting-FTP-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/ftp_connection/guide.de-de.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-asia.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-au.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-ca.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-gb.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-ie.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-sg.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-us.md
  pages/web_cloud/web_hosting/ftp_connection/guide.es-es.md
  pages/web_cloud/web_hosting/ftp_connection/guide.es-us.md
  pages/web_cloud/web_hosting/ftp_connection/guide.fr-ca.md
  pages/web_cloud/web_hosting/ftp_connection/guide.fr-fr.md
  pages/web_cloud/web_hosting/ftp_connection/guide.it-it.md
  pages/web_cloud/web_hosting/ftp_connection/guide.pl-pl.md
  pages/web_cloud/web_hosting/ftp_connection/guide.pt-pt.md
Labels: translations only, KFT, Minor update

#6333 update Public Cloud quotas to the current values
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.de-de.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.en-asia.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.en-au.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.en-ca.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.en-gb.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.en-ie.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.en-sg.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.en-us.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.es-es.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.es-us.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.fr-ca.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.fr-fr.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.it-it.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.pl-pl.md
  pages/public_cloud/compute/increasing_public_cloud_quota/guide.pt-pt.md
Labels: fix

#6288 BrenKt-TRANS-SK-1331-WEB-EmailPro-configuring_Gmail_Android
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.pt-pt.md
Labels: translations only

#6304 BrenKt-SK-1372-TRANS-WEB-Email-Exchange-Mail_on_Mac
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.pt-pt.md
Labels: translations only

#6339 Dedicated Servers - Windows Rescue mode - fr-fr version - Link fix
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.fr-fr.md
Labels: fix

#6340 Dedicated Servers - Windows rescue mode - FR fixes
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.fr-fr.md
Labels: fix

#6327 KevS-SK1541-KFT0014502-Update-Create-a-shared-database-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/sql_create_database/guide.de-de.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-au.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-us.md
  pages/web_cloud/web_hosting/sql_create_database/guide.es-es.md
  pages/web_cloud/web_hosting/sql_create_database/guide.es-us.md
  pages/web_cloud/web_hosting/sql_create_database/guide.it-it.md
  pages/web_cloud/web_hosting/sql_create_database/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_create_database/guide.pt-pt.md
Labels: translations only, KFT, Minor update

#6342 Fixes-WEB-pages-report_CSM-210524
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_android/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-sg.md
Labels: fix

#6345 Fixing links and images on several guides
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/how_to_configure_mail_macos/guide.pt-pt.md
Labels: FIX

#6338 KevS-SK1544-KFT0016205-Update-Htaccess-with-WordPress-for-WebHosting
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.fr-ca.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.fr-fr.md
Labels: KFT, Minor update

#6348 KevS-SK1546-KFT0015241-Update-DNS-history-for-DomainDNS
  pages/web_cloud/domains/dns_zone_history/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_history/guide.fr-fr.md
Labels: KFT, Minor update

#6284 Hosted Private Cloud : Backup with Veeam on VCD guides
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_console.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job_creation.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job_creation_2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job_creation_3.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job_creation_4.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job_creation_5.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job_creation_6.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_job_creation_7.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_jobs.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_repo.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_repo_2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_backup_vm.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_restore_vm.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_restore_vm_2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_restore_vm_3.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/meta.yaml
  pages/index.md
Labels: Guide creation

#6352 KevS-SK1546-KFT0015241-Update-DNS-history-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/dns_zone_history/guide.de-de.md
  pages/web_cloud/domains/dns_zone_history/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_history/guide.en-au.md
  pages/web_cloud/domains/dns_zone_history/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_history/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_history/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_history/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_history/guide.en-us.md
  pages/web_cloud/domains/dns_zone_history/guide.es-es.md
  pages/web_cloud/domains/dns_zone_history/guide.es-us.md
  pages/web_cloud/domains/dns_zone_history/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_history/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_history/guide.it-it.md
  pages/web_cloud/domains/dns_zone_history/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_history/guide.pt-pt.md
Labels: Translations ONLY, KFT, Minor update

#6351 KevS-SK1549-Update-DynHost-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/dns_dynhost/guide.de-de.md
  pages/web_cloud/domains/dns_dynhost/guide.en-gb.md
  pages/web_cloud/domains/dns_dynhost/guide.en-ie.md
  pages/web_cloud/domains/dns_dynhost/guide.es-es.md
  pages/web_cloud/domains/dns_dynhost/guide.fr-fr.md
  pages/web_cloud/domains/dns_dynhost/guide.it-it.md
  pages/web_cloud/domains/dns_dynhost/guide.pl-pl.md
  pages/web_cloud/domains/dns_dynhost/guide.pt-pt.md
Labels: Translations ONLY, KFT, Minor update

#6346 KevS-SK1543-KFT0016711-Update-Change-owner-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/trade_domain/guide.de-de.md
  pages/web_cloud/domains/trade_domain/guide.en-asia.md
  pages/web_cloud/domains/trade_domain/guide.en-au.md
  pages/web_cloud/domains/trade_domain/guide.en-ca.md
  pages/web_cloud/domains/trade_domain/guide.en-gb.md
  pages/web_cloud/domains/trade_domain/guide.en-ie.md
  pages/web_cloud/domains/trade_domain/guide.en-sg.md
  pages/web_cloud/domains/trade_domain/guide.en-us.md
  pages/web_cloud/domains/trade_domain/guide.es-es.md
  pages/web_cloud/domains/trade_domain/guide.es-us.md
  pages/web_cloud/domains/trade_domain/guide.fr-ca.md
  pages/web_cloud/domains/trade_domain/guide.fr-fr.md
  pages/web_cloud/domains/trade_domain/guide.it-it.md
  pages/web_cloud/domains/trade_domain/guide.pl-pl.md
  pages/web_cloud/domains/trade_domain/guide.pt-pt.md
Labels: Translations ONLY, KFT, Minor update

#6350 WEB-Email-troubleshooting-Lock_for_SPAM-SK-1548
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.pt-pt.md
Labels: KFT, Minor update, Translations

#6364 Fixes on various pages
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.fr-ca.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.fr-fr.md
  pages/account_and_service_management/managing_billing_payments_and_services/facturation_private_cloud/guide.fr-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/facturation_private_cloud/guide.fr-fr.md
  pages/bare_metal_cloud/managed_bare_metal/vlan-creation/guide.fr-ca.md
  pages/bare_metal_cloud/managed_bare_metal/vlan-creation/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/creation_vlan/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/creation_vlan/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_activation/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_iam_role/guide.pt-pt.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/28-flow/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/28-flow/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/47-nutanix-leap/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/47-nutanix-leap/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/48-metro-availability/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/48-metro-availability/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/intel_itv1_installation/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.pt-pt.md
Labels: FIX

#6362 Fixes
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_add_user_rights/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/technical-resources-03-lbaas-create-health-monitor/guide.pt-pt.md
Labels: FIX, KFT

#6365 Fixes on various pages
  pages/web_cloud/phone_and_fax/voip/troubleshoot-02-fix-control-panel/guide.fr-fr.md
Labels: FIX

#6367 VoIP - Fixing a typo - KFT0017251
  pages/web_cloud/phone_and_fax/voip/troubleshoot-02-fix-control-panel/guide.fr-fr.md
Labels: FIX, KFT

#6371 [Dedicated Servers] - Configuring an IPv6 block in a vRack - Minor updates
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/routed-mode-20240513.png
Labels: Minor update

#6379 Marketplace banner - Minor fix
  templates/banners/marketplace-support-collaboration/banner.fr-fr.html
Labels: FIX

#6382 Fixes on various pages
  pages/web_cloud/domains/dns_zone_edit/guide.fr-fr.md
  pages/web_cloud/domains/responsibility_model_domains/meta.yaml
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/locked_for_spam/guide.pt-pt.md
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/guide.fr-fr.md
Labels: FIX

#6286 Hosted Private Cloud : Remove Federation guides (vs IAM)
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.fr-fr.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.de-de.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.en-asia.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.en-au.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.en-ca.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.en-gb.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.en-ie.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.en-sg.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.en-us.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.es-es.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.es-us.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.fr-ca.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.fr-fr.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.it-it.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.pl-pl.md
  pages/bare_metal_cloud/managed_bare_metal/federation/guide.pt-pt.md
  pages/bare_metal_cloud/managed_bare_metal/federation/images/federation_canceled.png
  pages/bare_metal_cloud/managed_bare_metal/federation/images/federation_create.png
  pages/bare_metal_cloud/managed_bare_metal/federation/images/federation_grant_group.png
  pages/bare_metal_cloud/managed_bare_metal/federation/images/federation_grant_user.png
  pages/bare_metal_cloud/managed_bare_metal/federation/meta.yaml
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/01-add-directory01.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/01-add-directory02.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/01-add-directory03.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/01-add-directory04.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/02-adduser01.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/02-adduser02.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/02-adduser03.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/02-adduser04.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/03-addgroup01.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/03-addgroup02.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/03-addgroup03.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/03-addgroup04.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/04-federation_create.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/05-federation_canceled.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/06-federation_grant_user.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/images/07-federation_grant_group.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/federation/meta.yaml
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_kms_vsphere_configuration/guide.fr-fr.md
  pages/index.md
Labels: Do not merge, Guides removal

#6347 KevS-SK1544-KFT0016205-Update-Htaccess-with-WordPress-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.de-de.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.en-asia.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.en-au.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.en-ca.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.en-gb.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.en-ie.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.en-sg.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.en-us.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.es-es.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.es-us.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.fr-ca.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.fr-fr.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.it-it.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.pl-pl.md
  pages/web_cloud/web_hosting/htaccess_how_to_protect_wordpress/guide.pt-pt.md
Labels: Translations ONLY, KFT, Minor update

#6335 BrenKt-SK-1373-WEB-Domain-DNS-zone-edit
  pages/web_cloud/domains/dns_zone_edit/guide.de-de.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-au.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_edit/guide.en-us.md
  pages/web_cloud/domains/dns_zone_edit/guide.es-es.md
  pages/web_cloud/domains/dns_zone_edit/guide.es-us.md
  pages/web_cloud/domains/dns_zone_edit/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_edit/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_edit/guide.it-it.md
  pages/web_cloud/domains/dns_zone_edit/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_edit/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_edit/images/dns-zone-reset-01.png
  pages/web_cloud/domains/dns_zone_edit/images/dns-zone-reset-02.png
Labels: Translations

#6380 Telecom - OverTheBox - MAJ OTB v1 & v2
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/web_cloud/internet/overthebox/advanced_installer_limage_overthebox_sur_votre_materiel/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/config_reset/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/install_comment_fonctionne_overthebox_v1/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/install_comment_fonctionne_overthebox_v1/meta.yaml
  pages/web_cloud/internet/overthebox/install_faq/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4320.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4321.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4322.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4323.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4324.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4325.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4332.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4333.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4334.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4335.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4336.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4337.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4339.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4342.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4343.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4344.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/images/4345.png
  pages/web_cloud/internet/overthebox/intel_itv1_desactiver_dhcp_modem/meta.yaml
  pages/web_cloud/internet/overthebox/intel_itv1_installation/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/intel_itv1_installation/images/installationV1-final-plugs.png
  pages/web_cloud/internet/overthebox/intel_itv1_installation/images/installationV1-network.gif
  pages/web_cloud/internet/overthebox/intel_itv1_integration_decodeur_tv/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/intel_itv1_integration_decodeur_tv/images/4404.png
  pages/web_cloud/internet/overthebox/intel_itv1_integration_decodeur_tv/meta.yaml
  pages/web_cloud/internet/overthebox/middle_redirection_de_port/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/plus_itv2_installation/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/plus_itv2_lte/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/start-with-overthebox/guide.fr-fr.md
Labels: Guides removal

#6285 Update 3AZ documentation with small wording feedbacks and new screenshots
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/images/01-20240513-blur.png
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/images/02-20240513-blur.png
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/images/03-20240513-blur.png
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/images/04-20240513-blur.png
  pages/bare_metal_cloud/dedicated_servers/3az-presentation/meta.yaml
  pages/index.md
Labels: Guide creation

#6392 Public Cloud LB OpenStack - Steps and format fixes
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.pt-pt.md
Labels: FIX, Minor update

#6394 Format fix for OpenStack LBaaS
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.fr-fr.md
Labels: FIX

#6397 VMware - VCD Getting Started - Version fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-getting-started/guide.pt-pt.md
Labels: FIX
