Repository ovh/docs, pull requests merged in 2024-08, with the labels that each got.

#6657 [EN] Update - LDP guides
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_filebeat/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_syslog_ng/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_windows_nxlog/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/integration_opensearch_api/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/security_tokens/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/visualization_grafana/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/visualization_opensearch_dashboards/guide.en-gb.md
Labels: Priority: Low

#6641 Public Cloud - Creating a private network
  pages/network/Create Share_private_network_between_2_projects/guide.en-gb.md
  pages/network/Create Share_private_network_between_2_projects/guide.fr-fr.md
Labels: Guide creation, Quality Check

#6647 feat(using_ipmi_on_dedicated_servers): update documentation
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/KVM-web-browser01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/KVM-web-browser02.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/access_kvm.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-applet-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-console-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-kvm-html-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-kvm-html-02.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-kvm-html-03.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-kvm-java-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-kvm-java-02.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-kvm-java-03.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-reboot-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-reboot.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-sol-html-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-sol-html-02.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-sol-sshkey-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-sol-sshkey-02.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-sol-sshkey-03.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-test-01.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi-test.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi_reboot.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi_reboot_2020.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi_reboot_2022.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi_test.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi_test_2020.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/ipmi_test_2022.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/java_ipmi_hard_reboot.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/java_ipmi_initiate.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/java_ipmi_initiate_2020.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/java_ipmi_initiate_2022.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/sol_ipmi_activation.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/sol_ipmi_activation_2020.png
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/images/sol_ipmi_activation_2022.png
Labels: Quality Check

#6622 Updating MKS x HA-NAS documentation
  links/storage/nas-ha
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/images/manage-nfs-partition-access-ip.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-nas-ha/images/manage-nfs-partition-access.png
Labels: Quality Check

#6662 update drawing to be more explicit
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/images/netcon3.png
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/images/netcon4.png
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/images/netcon5.png
Labels: KFT / Issue

#6669 Cold Archive - Overview guide updates
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.de-de.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.en-asia.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.en-au.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.en-ca.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.en-gb.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.en-ie.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.en-sg.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.en-us.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.es-es.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.es-us.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.fr-ca.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.fr-fr.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.it-it.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.pl-pl.md
  pages/storage_and_backup/object_storage/cold_archive_overview/guide.pt-pt.md
Labels: Minor update

#6671 SAP Backint - Update the method to check/enable versioning
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.pt-pt.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/images/versioning_disabled.png
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/images/versioning_enabled.png
Labels: Minor update, Priority: Low

#6688 Fixes on several pages
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/concepts-01-public-cloud-networking-concepts/guide.fr-fr.md
Labels: FIX

#6664 New guide that explain how to create update and access to a rancher
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/create-rancher.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/popup.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-access.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-home.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-list.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-login-page.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-name.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-plan.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-to-update.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-update-in-progress.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-update-popup.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-update.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/images/rancher-version.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/meta.yaml
Labels: Guide creation, Quality Check

#6684 New guide managing users and projects on rancher
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-cluster.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-falco.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-menu.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-project-ns.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-project.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-sre-user.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-sre.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-standard-user.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-ui.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-user.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/images/rancher-users.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/managing-users-and-projects/meta.yaml
Labels: Guide creation

#6676 New doc how to use rancher CLI with MRS
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/images/rancher-about-link.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/images/rancher-account.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/images/rancher-apikey-creation.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/images/rancher-avatar-menu.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/meta.yaml
Labels: Guide creation, Quality Check

#6665 New doc to import existing kube cluster in rancher
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/images/cluster-dashboard-explore.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/images/generic-driver.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/images/mks-name.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/images/rancher-ui.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/images/register-cluster-instructions.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/import-existing-kubernetes/meta.yaml
Labels: Guide creation, Quality Check

#6675 New guide how to edit configuration of a kube cluster
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-api-creds.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-cluster-management.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-cluster-name.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-edit-config.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-labels-annotations.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-members.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-np.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/images/rancher-update-policy.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/edit-config-kubernetes-cluster/meta.yaml
Labels: Guide creation, Quality Check

#6687 Dedicated Servers - Adding a Virtual MAC to an Additional IP - Adding availability information for HG/Scale/Advance
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.pt-pt.md
Labels: Minor update

#6690 Managed Rancher Services - Fixing typos and index
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/create-update-rancher/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/using-rancher-cli/guide.pt-pt.md
Labels: FIX

#6672 New doc how to create a MKS cluster with rancher
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/cluster-config.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/mks-active.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/mks-creating.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/mycluster.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/network-config.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/nodepool.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/project-id.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/rancher-create.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/rancher-mks-name.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/images/rancher-ui.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-mks-kubernetes-cluster/meta.yaml
Labels: Guide creation, Quality Check

#6686 New guide creating a Kubernetes cluster based on PCI
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/kubectl-get-nodes.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/kubectl-get-ns.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/pci-creds.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-cluster-config.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-cluster-created.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-cluster-name.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-create-credentials-project.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-create-credentials.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-create-pci-creds.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-create.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-creds.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-kubectl-shell.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-machine-pool-1.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-machine-pool-2.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-pci-creds-project.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-select-creds.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/images/rancher-ui.png
Labels: Guide creation

#6689 News guide: Backing up and Restore a Kubernetes cluster
  links/public-cloud/rancher
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/automatic-snapshots.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/rancher-backup-local.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/rancher-backup-s3.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/rancher-cluster.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/rancher-edit-config.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/rancher-etcd-config.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/rancher-ui.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/restore-in-progress-2.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/restore-in-progress.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/restore-snapshot.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/s3-details.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/s3-etcd.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/s3-object.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/s3.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/snapshot-in-progress.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/snapshots.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/images/take-snapshot.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/backup-restore-etcd-s3/meta.yaml
Labels: Guide creation

#6679 New guide - Firmware WDC SS530
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/wdc-sas-ss530-fw-upgrade/meta.yaml
  pages/index.md
Labels: Guide creation, Quality Check

#6694 New guide: create a Kubernetes cluster with existing nodes
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-cluster-creation.jpg
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-cluster-creation.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-cluster-roles-command.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-cluster-roles-worker.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-cluster-roles.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-command-worker.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-create-custom.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/images/rancher-ui.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-custom-nodes/meta.yaml
Labels: Guide creation

#6695 Fixes on several pages
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/meta.yaml
Labels: FIX

#6696 New guide : deploying a monitoring stack (Prometheus & Grafana) in a Kubernetes cluster with Rancher
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/error-cpu-core-insufficient.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/grafana.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/monitoring-stack.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/promql.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-alertmanager.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-cluster-tools.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-cluster.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-explore.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-grafana.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-install-prom.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-logs.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-monito-pods.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-monitoring-menu.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-monitoring.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-prometheus.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-rke2.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/images/rancher-ui.png
  pages/public_cloud/containers_orchestration/managed_rancher_service/deploy-monitoring-prometheus-grafana-metrics/meta.yaml
Labels: Guide creation

#6698 VoIP - FAQ - Adding a scheme about SIP lines VS alias numbers
  pages/web_cloud/phone_and_fax/voip/faq-voip/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/voip/faq-voip/images/alias-vs-sip.png
Labels: Minor update

#6683 Dedicated Servers - Network on Windows Servers with Hyper-V - Advance range update
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.pt-pt.md
  pages/index.md
Labels: Minor update

#6697 Data Platform - SK1641 & SK1642 - Creating a dedicated page for the video demo
  pages/index.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.de-de.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-asia.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-au.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-ca.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-gb.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-ie.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-sg.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-us.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.es-es.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.es-us.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.fr-ca.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.fr-fr.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.it-it.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.pl-pl.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.pt-pt.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/meta.yaml
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.de-de.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-asia.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-au.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-ca.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-gb.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-ie.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-sg.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-us.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.es-es.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.es-us.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.fr-ca.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.fr-fr.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.it-it.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.pl-pl.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.pt-pt.md
Labels: Guide creation

#6702 VMware - IP configuration on a VM - Adding IPv6 configuration steps
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_interfaces_v6 copy.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_interfaces_v6.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_windows_v6.jpg
Labels: Priority: Low

#6705 TRANS-Cloud-BareMetal-Dedicated-using_IPMI
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.pt-pt.md
Labels: Translations ONLY

#6708 EN Update - Tracking slow MySQL queries for LDP
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_mysql_slow_queries/guide.pt-pt.md
Labels: Priority: Low

#6709 VMware - Configure IP on a VM - change jpg to png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_interfaces.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_interfaces_v6.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_ovh_network.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_ovh_network_advanced.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_windows.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/configure_ip_on_vm/images/config_ip_windows_v6.png
Labels: FIX, Priority: Low

#6714 Grammatical fixes for LDP guides
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/cli_bonfire/guide.pt-pt.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.pt-pt.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_roles_permission/guide.pt-pt.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.pt-pt.md
Labels: FIX

#6715 QF-Cloud-BareMetal-Dedicated-IPMI
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.de-de.md
Labels: FIX

#6721 Update MKS Public Cloud loadbalancer guide to remove typo and Naming Convention
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pt-pt.md
Labels: Minor update

#6720 VPS - Configure IPv6 - Netplan configuration example update
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-us.md
Labels: Minor update

#6723 VPS - IPv6 config - Netplan config example update - Duplicating PR #6720
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.pt-pt.md
Labels: Translations

#6716 HPC : Guide update life cycle policy
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.pt-pt.md
Labels: Update request, Priority: Urgent

#6722 DBaaS - Cluster plan upgrade - add instructions for API and plan downgrade
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-us.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.pt-pt.md
Labels: Minor update

#6726 SK1649 - Compute - Download and transfer instance backup - title update
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.de-de.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-asia.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-au.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-ca.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-gb.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-ie.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-sg.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-us.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.es-es.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.es-us.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.fr-ca.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.fr-fr.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.it-it.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.pl-pl.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.pt-pt.md
Labels: Minor update

#6724 Public Cloud Network Services - Update L3 service FAQ
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.pt-pt.md
Labels: Priority: Low

#6730 Support FAQ - Fixing formats
  pages/account_and_service_management/account_information/faq-support/guide.de-de.md
  pages/account_and_service_management/account_information/faq-support/guide.en-asia.md
  pages/account_and_service_management/account_information/faq-support/guide.en-au.md
  pages/account_and_service_management/account_information/faq-support/guide.en-ca.md
  pages/account_and_service_management/account_information/faq-support/guide.en-gb.md
  pages/account_and_service_management/account_information/faq-support/guide.en-ie.md
  pages/account_and_service_management/account_information/faq-support/guide.en-sg.md
  pages/account_and_service_management/account_information/faq-support/guide.en-us.md
  pages/account_and_service_management/account_information/faq-support/guide.es-es.md
  pages/account_and_service_management/account_information/faq-support/guide.es-us.md
  pages/account_and_service_management/account_information/faq-support/guide.fr-ca.md
  pages/account_and_service_management/account_information/faq-support/guide.fr-fr.md
  pages/account_and_service_management/account_information/faq-support/guide.it-it.md
  pages/account_and_service_management/account_information/faq-support/guide.pl-pl.md
  pages/account_and_service_management/account_information/faq-support/guide.pt-pt.md
Labels: FIX

#6733 add ICMP filter on Load Balancer IP
  pages/public_cloud/public_cloud_network_services/known-limits/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/known-limits/guide.pt-pt.md
Labels: Priority: Low

#6738 MKS - Add High Speed Gen2 as storage class
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/backup-and-restore-cluster-namespace-and-applications-with-trilio/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/fix-persistent-volumes-permissions/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.pt-pt.md
Labels: Quality Check

#6754 KevS-SK1668-Update-DNSSEC-for-DomainDNS
  pages/web_cloud/domains/dns_dnssec/guide.fr-ca.md
  pages/web_cloud/domains/dns_dnssec/guide.fr-fr.md
Labels: Minor update

#6755 KevS-SK1668-Update-DNSSEC-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/dns_dnssec/guide.de-de.md
  pages/web_cloud/domains/dns_dnssec/guide.en-asia.md
  pages/web_cloud/domains/dns_dnssec/guide.en-au.md
  pages/web_cloud/domains/dns_dnssec/guide.en-ca.md
  pages/web_cloud/domains/dns_dnssec/guide.en-gb.md
  pages/web_cloud/domains/dns_dnssec/guide.en-ie.md
  pages/web_cloud/domains/dns_dnssec/guide.en-sg.md
  pages/web_cloud/domains/dns_dnssec/guide.en-us.md
  pages/web_cloud/domains/dns_dnssec/guide.es-es.md
  pages/web_cloud/domains/dns_dnssec/guide.es-us.md
  pages/web_cloud/domains/dns_dnssec/guide.it-it.md
  pages/web_cloud/domains/dns_dnssec/guide.pl-pl.md
  pages/web_cloud/domains/dns_dnssec/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6744 Hpc - Guide update VCD network components
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.pt-pt.md
Labels: Update request, Priority: Low

#6734 Hpc - Update guide login to vSphere web interface from the control panel
  links/hosted-private-cloud/vmware
  pages/assets/screens/control_panel/product-selection/hosted-private-cloud/vmware/vmware_user_modification.png
  pages/assets/screens/control_panel/product-selection/hosted-private-cloud/vmware/vmware_users.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/connection_interface_w.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/connection_interface_w_html5.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/connexion_client_l.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/connexion_client_l2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere-client-html5.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere-client.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere_web_client_all.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere_web_client_iam.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere_web_client_iam_vs_local.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere_web_client_local.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere_web_client_pcc_home.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/vsphere_web_client_user_modification.png
Labels: Update request, Priority: Low

#6761 VMware - Logging in to vSphere - Code fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.pt-pt.md
Labels: FIX

#6768 KevS-SK1670-Update-Create-db-and-user-for-WebCloudDatabases
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.fr-fr.md
Labels: Minor update

#6763 Adding info about permissions groups and expiration date
  pages/account_and_service_management/account_information/iam-policies-api/guide.de-de.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-asia.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-au.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-ca.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-gb.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-ie.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-sg.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-us.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.es-es.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.es-us.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.fr-ca.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.fr-fr.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.it-it.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.pl-pl.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.pt-pt.md
Labels: Minor update

#6769 VoIP - FAQ - Style fix
  pages/web_cloud/phone_and_fax/voip/faq-voip/guide.fr-fr.md
Labels: FIX

#6771 KevS-SK1670-Update-Create-db-and-user-for-WebCloudDatabases-TRANSLATIONS
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.de-de.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.en-asia.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.en-au.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.en-ca.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.en-ie.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.en-sg.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.en-us.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.es-es.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.es-us.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.fr-fr.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.it-it.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6732 Update MKS / LoadBalancer with Octavia integration - Lint, fixes and new use cases
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pt-pt.md
Labels: Quality Check

#6717 Hpc - Update guide VMware vSphere logForwarder feature
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.pt-pt.md
Labels: Update request, Priority: Low

#6728 Hpc - Guide update VCD Veeam data protection
  links/public-cloud/object-storage
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.pt-pt.md
Labels: Update request, Priority: Low

#6749 Hpc - Guide update : VCD network concepts
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pt-pt.md
Labels: Update request, Priority: Low

#6776 KevS-SK1633-Git-integration-final-TRANSLATIONS
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pt-pt.md
Labels: Translations ONLY

#6782 Dedicated Servers - Intervention follow-up - Minor fixes (KFT)
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.pt-pt.md
Labels: FIX, KFT / Issue

#6783 Object Storage - Creating a bucket - Image update (KFT)
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_create_bucket/images/highperf-create-container-20220928081750384.png
  pages/storage_and_backup/object_storage/s3_create_bucket/images/highperf-create-container-20240827.png
Labels: KFT / Issue

#6784 Dedicated Servers - Intervention follow-up - Minor update (KFT)
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.pt-pt.md
Labels: KFT / Issue, Minor update

#6786 Hpc - Guide fix kms on managed vSphere
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pt-pt.md
Labels: FIX

#6787 VMware - KMS - Additional fixes
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.pt-pt.md
Labels: FIX

#6789 VMware - KMS - Additional fixes
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_okms_vm-encrypt/guide.pt-pt.md
Labels: FIX

#6788 SK-1671-TRANS-WEB-Emails-MXplan-Zimbra-Webmail-Calendar_feature
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.pt-pt.md
Labels: Translations ONLY

#6791 Connectivity - How to enable IPv6 on an OVHcloud Internet Access
  pages/index.md
  pages/web_cloud/internet/internet_access/comment_gerer_ipv6/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_gerer_ipv6/images/IPv6-activate.png
  pages/web_cloud/internet/internet_access/comment_gerer_ipv6/images/IPv6-status.png
  pages/web_cloud/internet/internet_access/comment_gerer_ipv6/meta.yaml
Labels: Guide creation

#6795 Format fixes on several guides
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.pt-pt.md
Labels: FIX

#6798 Public Cloud Network Services - FAQ - Format update and table fix
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-06-faq/guide.pt-pt.md
Labels: FIX
