Repository ovh/docs, pull requests merged in 2024-10, with the labels that each got.

#6893 FB - Improve "first step with a VPS" guide
  links/bare-metal/vps-options
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.pt-pt.md
Labels: Translations

#6919 Hpc - Migration VCD fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: Update request, Priority: Dependency

#6959 KevS-SK1742-KFT0020855-Update-Delete-DNS-zone-for-DomainDNS
  pages/web_cloud/domains/dns_zone_deletion/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_deletion/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#6962 KevS-SK1743-KFT0021410-Update-Change-Web-offer-for-WebHosting
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#6960 FR update overthebox version matrix with v1.0.2
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
Labels: Minor update

#6967 FR update overthebox version matrix with v0.9.6
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
Labels: Minor update

#6970 Hpc - VCD migration guide fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: Update request, FIX

#6972 FR update overthebox 4G guide for OTB V3 LTE
  pages/web_cloud/internet/overthebox/plus_itv2_lte/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/lte-backup.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/lte-mptcp-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/lte-step1-1.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/lte-step1-2.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/lte-step1-3.jpg
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/lte-step2-1.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/lte-step2-2.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/usblte-android-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/usblte-check-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/usblte-e3372-1-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/usblte-e3372-2-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-check-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step1-1-backcover-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step1-2-lteModule-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step1-3-simInsert-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step2-antenna-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-1-luciltedown-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-2-lucilteitf-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-3-airmob-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-3-bouygues-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-3-free-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-3-orange-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-3-sfr-2024.png
  pages/web_cloud/internet/overthebox/plus_itv2_lte/images/v3lte-step3-4-luciltesaveitf-2024.png
Labels: Quality Check

#6971 KevS-SK1750-KFT0017514-Update-Install-one-click-module-for-WebHosting
  pages/web_cloud/web_hosting/cms_install_1_click_modules/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_install_1_click_modules/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#6975 OverTheBox - Minor fix
  pages/web_cloud/internet/overthebox/plus_itv2_installation/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/plus_itv2_lte/guide.fr-fr.md
Labels: FIX

#6976 Public Cloud - Compute/DB - Inserting getting started videos
  pages/public_cloud/compute/public-cloud-first-steps/guide.de-de.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-asia.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-au.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-ca.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-gb.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-ie.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-sg.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-us.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.es-es.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.es-us.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.fr-ca.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.fr-fr.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.it-it.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.pl-pl.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.en-us.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_01_order_control_panel/guide.pt-pt.md
Labels: Minor update

#6935 Hpc - Guide update, upload with govc on VMware api
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.fr-fr.md
Labels: Update request, Do not merge yet, Quality Check

#6977 Hpc - Guide fix migration VCD
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: FIX, Priority: Urgent

#6925 KevS-SK1729-Update-CDN-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.de-de.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.en-asia.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.en-au.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.en-ca.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.en-gb.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.en-ie.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.en-sg.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.en-us.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.es-es.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.es-us.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.fr-ca.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.fr-fr.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.it-it.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.pl-pl.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6963 KevS-SK1742-KFT0020855-Update-Delete-DNS-zone-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/dns_zone_deletion/guide.de-de.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-au.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-us.md
  pages/web_cloud/domains/dns_zone_deletion/guide.es-es.md
  pages/web_cloud/domains/dns_zone_deletion/guide.es-us.md
  pages/web_cloud/domains/dns_zone_deletion/guide.it-it.md
  pages/web_cloud/domains/dns_zone_deletion/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_deletion/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue

#6964 KevS-SK1743-KFT0021410-Update-Change-Web-offer-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.de-de.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-asia.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-au.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-ca.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-gb.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-ie.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-sg.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-us.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.es-es.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.es-us.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.fr-ca.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.it-it.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.pl-pl.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue

#6984 FB - Fix image on Multisite diagnostic
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.en-ie.md
Labels: FIX

#6990 EFS Concepts - Translations fixes
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_concepts/guide.de-de.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_concepts/guide.es-es.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_concepts/guide.es-us.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_concepts/guide.pt-pt.md
Labels: FIX

#6987 [NETAPP][EFS] New guide for customers
  links/storage/enterprise-file-storage
  pages/index.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.en-asia.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.en-au.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.en-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.en-gb.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.en-ie.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.en-sg.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.en-us.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.fr-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.fr-fr.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/meta.yaml
Labels: Guide creation

#6995 KevS-SK1754-KFT0014494-Update-DOA-for-DomainDNS
  pages/web_cloud/domains/trade_doa/guide.fr-fr.md
Labels: KFT / Issue

#6996 EFS - NFS - Fixes
  pages/index.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.fr-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.fr-fr.md
Labels: FIX

#6986 KevS-SK1749-Creation-Create-FTP-users-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/ftp_manage_users/guide.de-de.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-asia.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-au.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-ca.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-gb.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-ie.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-sg.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-us.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.es-es.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.es-us.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.it-it.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.pl-pl.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.pt-pt.md
Labels: Translations ONLY, Translations

#6997 KevS-Optimisation-title-SSL-EV-guide-for-WebHosting
  pages/web_cloud/web_hosting/ssl_ev/guide.de-de.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-asia.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-au.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-ca.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-gb.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-ie.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-sg.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-us.md
  pages/web_cloud/web_hosting/ssl_ev/guide.es-es.md
  pages/web_cloud/web_hosting/ssl_ev/guide.es-us.md
  pages/web_cloud/web_hosting/ssl_ev/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_ev/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_ev/guide.it-it.md
  pages/web_cloud/web_hosting/ssl_ev/guide.pl-pl.md
  pages/web_cloud/web_hosting/ssl_ev/guide.pt-pt.md
Labels: Minor update, Translations

#6992 KevS-SK1752-FB-Adding-diagnostic-description-into-multisite-guide-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.en-asia.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.en-au.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.en-ca.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.en-sg.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.en-us.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.es-us.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_configure_multisite/guide.pt-pt.md
Labels: Translations ONLY

#6998 Connectivity - Troubleshooting incidents - Modem lights analysis update
  pages/web_cloud/internet/internet_access/interruption_de_service/guide.fr-fr.md
Labels: KFT / Issue

#6999 SMS - Sending SMS from the Control Panel - Minor updated following KFT
  pages/web_cloud/messaging/sms/envoyer_des_sms_depuis_mon_espace_client/guide.en-gb.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_depuis_mon_espace_client/guide.en-ie.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_depuis_mon_espace_client/guide.es-es.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_depuis_mon_espace_client/guide.fr-fr.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_depuis_mon_espace_client/guide.it-it.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_depuis_mon_espace_client/guide.pl-pl.md
Labels: KFT / Issue

#7000 KevS-Optimisation-title-for-SEO-on-WebHosting
  pages/index.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.en-asia.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.en-au.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.en-ca.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.en-gb.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.en-ie.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.en-sg.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.en-us.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.es-es.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.es-us.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.it-it.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.pt-pt.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.de-de.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-asia.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-au.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-ca.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-gb.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-ie.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-sg.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.en-us.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.es-es.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.es-us.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.fr-ca.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.fr-fr.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.it-it.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.pl-pl.md
  pages/web_cloud/web_hosting/ftp_manage_users/guide.pt-pt.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.de-de.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-asia.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-au.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-ca.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-gb.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-ie.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-sg.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.en-us.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.es-es.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.es-us.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.fr-ca.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.fr-fr.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.it-it.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.pl-pl.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.pt-pt.md
Labels: Minor update, Translations

#6957 KevS-SK1739-Creation-Associate-Domain-with-Google-Site-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.de-de.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.de-de.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-asia.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-au.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-gb.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-ie.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-sg.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.es-es.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.es-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.fr-fr.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.it-it.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.pl-pl.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.pt-pt.md
Labels: Translations ONLY

#7002 IPLB: fix some typos
  pages/network/load_balancer/create_faq/guide.en-asia.md
  pages/network/load_balancer/create_faq/guide.en-au.md
  pages/network/load_balancer/create_faq/guide.en-ca.md
  pages/network/load_balancer/create_faq/guide.en-gb.md
  pages/network/load_balancer/create_faq/guide.en-sg.md
  pages/network/load_balancer/create_faq/guide.en-us.md
  pages/network/load_balancer/create_headers/guide.en-asia.md
  pages/network/load_balancer/create_headers/guide.en-au.md
  pages/network/load_balancer/create_headers/guide.en-ca.md
  pages/network/load_balancer/create_headers/guide.en-gb.md
  pages/network/load_balancer/create_headers/guide.en-sg.md
  pages/network/load_balancer/create_headers/guide.en-us.md
  pages/network/load_balancer/create_proxyprotocol/guide.en-asia.md
  pages/network/load_balancer/create_proxyprotocol/guide.en-au.md
  pages/network/load_balancer/create_proxyprotocol/guide.en-ca.md
  pages/network/load_balancer/create_proxyprotocol/guide.en-gb.md
  pages/network/load_balancer/create_proxyprotocol/guide.en-sg.md
  pages/network/load_balancer/create_proxyprotocol/guide.en-us.md
  pages/network/load_balancer/use_api_details/guide.en-asia.md
  pages/network/load_balancer/use_api_details/guide.en-au.md
  pages/network/load_balancer/use_api_details/guide.en-ca.md
  pages/network/load_balancer/use_api_details/guide.en-gb.md
  pages/network/load_balancer/use_api_details/guide.en-sg.md
  pages/network/load_balancer/use_api_details/guide.en-us.md
  pages/network/load_balancer/use_api_reference/guide.en-asia.md
  pages/network/load_balancer/use_api_reference/guide.en-au.md
  pages/network/load_balancer/use_api_reference/guide.en-ca.md
  pages/network/load_balancer/use_api_reference/guide.en-gb.md
  pages/network/load_balancer/use_api_reference/guide.en-sg.md
  pages/network/load_balancer/use_api_reference/guide.en-us.md
Labels: FIX

#6989 Dedicated Servers - Bridge IP mode - General update
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-fr.md
Labels: FIX

#6965 SK-1748-WEB-Emails-Zimbra-BETA_release_improvement
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_domain_add.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_domain_tab.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_emailaccounts_add.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_emailaccounts_tab.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_general_information.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_organization_add.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_organization_filter.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_organization_tab.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_mail_apps/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_mail_apps/meta.yaml
Labels: Guide creation, Do not merge yet

#7006 KevS-SK1760-KFT0021996-Update-manage-1-click-module-for-WebHosting
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.de-de.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.en-asia.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.en-au.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.en-ca.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.en-gb.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.en-ie.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.en-sg.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.en-us.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.es-es.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.es-us.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.fr-fr.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.it-it.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.pl-pl.md
  pages/web_cloud/web_hosting/cms_manage_1_click_module/guide.pt-pt.md
Labels: KFT / Issue

#7007 Hpc - Fix guide kms overall
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pt-pt.md
Labels: FIX, Priority: Low

#7012 Public Cloud FAQ - Date fix
  pages/public_cloud/compute/faq_pci/guide.en-asia.md
  pages/public_cloud/compute/faq_pci/guide.en-au.md
  pages/public_cloud/compute/faq_pci/guide.en-ca.md
  pages/public_cloud/compute/faq_pci/guide.en-gb.md
  pages/public_cloud/compute/faq_pci/guide.en-ie.md
  pages/public_cloud/compute/faq_pci/guide.en-sg.md
  pages/public_cloud/compute/faq_pci/guide.en-us.md
Labels: FIX

#7008 TRANSLATIONS - Enterprise File Storage - NFS client considerations
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.de-de.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.es-es.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.es-us.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.it-it.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.pl-pl.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_nfs_client_considerations/guide.pt-pt.md
Labels: Translations ONLY, Priority: Low

#7004 EN and Translations for network bridge - #PR 6989
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pt-pt.md
Labels: Do not merge yet, Translations

#7016 KevS-SK1758-Creation-SSL-Custom-for-WebHosting
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/order-an-ssl-certificate-step-1-custom.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/order-an-ssl-certificate-step-2-custom-empty.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/order-an-ssl-certificate-step-2-custom.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/ssl-certificate-custom-enable.png
  pages/index.md
  pages/web_cloud/web_hosting/ssl_custom/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_custom/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_custom/meta.yaml
Labels: Guide creation

#6936 Local Zones for Compute - Capabilities update
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.de-de.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-asia.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-au.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-ca.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-gb.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-ie.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-sg.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-us.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.es-es.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.es-us.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.fr-ca.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.fr-fr.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.it-it.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.pl-pl.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.pt-pt.md
Labels: Do not merge yet

#7013 FB - How to change admin CMS password
  pages/index.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-asia.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-au.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-ca.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-gb.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-ie.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-sg.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-us.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.fr-fr.md
  pages/web_cloud/web_hosting/cms-update-password-admin/meta.yaml
Labels: Guide creation

#7022 KevS-SSL-Gateway-link-fixes-for-asia
  links/web/ssl-gateway
Labels: FIX

#7017 Hpc - VCD Veeam guide update
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-backup/images/vcd_veeam_zones.png
Labels: Update request, Priority: Dependency

#7026 Dev/dghilleb/new guide mail sending
  pages/index.md
  pages/web_cloud/internet/internet_access/comment_activer_envoi_mail/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_activer_envoi_mail/images/MailSending-Disable.png
  pages/web_cloud/internet/internet_access/comment_activer_envoi_mail/images/MailSending-Status.png
  pages/web_cloud/internet/internet_access/comment_activer_envoi_mail/meta.yaml
Labels: Guide creation

#7005 Dedicated Servers - Adding Debian 12 steps - FR/EN - KFT0012726
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.pt-pt.md
Labels: KFT / Issue

#6958 Dedicated Servers - Netplan link aggregation for Debian 12 / Ubuntu 22.04
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/images/ControlPanel.png
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/meta.yaml
  pages/index.md
Labels: Guide creation

#7032 fix: typo
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.fr-fr.md
Labels: FIX

#7034 Links fixes on several guides
  links/web/ssl-gateway
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.pt-pt.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.pl-pl.md
Labels: FIX

#7036 Dedicated Servers - Windows admin psswd change - FR typo fix
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.fr-fr.md
Labels: FIX

#7041 New Guide - Configuring IPv6 on a virtual machine - KFT0007558
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/configure_ipv6_container.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/container_network.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/container_ubuntu.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/create_vm.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/create_vm_name.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/create_vm_proxmox.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/edit_network.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/ipv6_information.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/ls_command.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/select_iso.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/virtual_switch_1.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/vm_alma_rocky.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/vm_debian.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/images/vm_ubuntu.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-on-a-vm/meta.yaml
  pages/index.md
Labels: Guide creation, KFT / Issue, Quality Check

#7027 KevS-SK1758-Creation-SSL-Custom-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/ssl_custom/guide.de-de.md
  pages/web_cloud/web_hosting/ssl_custom/guide.en-asia.md
  pages/web_cloud/web_hosting/ssl_custom/guide.en-au.md
  pages/web_cloud/web_hosting/ssl_custom/guide.en-ca.md
  pages/web_cloud/web_hosting/ssl_custom/guide.en-gb.md
  pages/web_cloud/web_hosting/ssl_custom/guide.en-ie.md
  pages/web_cloud/web_hosting/ssl_custom/guide.en-sg.md
  pages/web_cloud/web_hosting/ssl_custom/guide.en-us.md
  pages/web_cloud/web_hosting/ssl_custom/guide.es-es.md
  pages/web_cloud/web_hosting/ssl_custom/guide.es-us.md
  pages/web_cloud/web_hosting/ssl_custom/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_custom/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_custom/guide.it-it.md
  pages/web_cloud/web_hosting/ssl_custom/guide.pl-pl.md
  pages/web_cloud/web_hosting/ssl_custom/guide.pt-pt.md
Labels: Translations ONLY

#7051 Hpc - Guide update Zerto vCpu ram
  links/hosted-private-cloud/vmware-prices
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto_virtual_replication_as_a_service/guide.pt-pt.md
Labels: Update request, Priority: Urgent

#7038 KevS-SK1765-FB-Create-How-to-change-admin-CMS-password-for-WebHosting
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.de-de.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-asia.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-au.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-ca.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-gb.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-ie.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-sg.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.en-us.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.es-es.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.es-us.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.fr-fr.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.it-it.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.pl-pl.md
  pages/web_cloud/web_hosting/cms-update-password-admin/guide.pt-pt.md
Labels: Translations ONLY

#7055 KevS-Quickfix-broken-link
  pages/web_cloud/web_hosting/ssl_custom/guide.pt-pt.md
Labels: FIX

#7043 KevS-SK1757-Creation-SSL-DV-for-WebHosting
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/ssl-certificate-dv-enable.png
  pages/index.md
  pages/web_cloud/web_hosting/ssl_dv/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_dv/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_dv/meta.yaml
Labels: Guide creation

#7056 DBaaS - Kubernetes operator - Typo fix
  pages/index.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_12_operator/guide.pt-pt.md
Labels: FIX

#6951 Hpc - Guide update vm encrypt fr guide + index + title
  pages/assets/screens/control_panel/product-selection/hosted-private-cloud/vmware/security/add_kms.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/add_kms.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_01.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_02.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_03.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_04.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_05.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_06.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_07.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt/images/vm-encrypt_09.png
  pages/index.md
Labels: Update request, Priority: Low

#7060 Update - VCD migration use case
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: Update request, FIX

#7046 KevS-SK1756-Create-SSL-Lets-encrypt-for-WebHosting
  pages/index.md
  pages/web_cloud/web_hosting/ssl_letsencrypt/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_letsencrypt/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_letsencrypt/meta.yaml
Labels: Guide creation

#7042 Hpc - Guide creation datamotive intro
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/images/datamotive_dashboard.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/images/datamotive_login.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/images/datamotive_schema.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/datamotive_intro/meta.yaml
  pages/index.md
Labels: Guide creation, Priority: Low

#7035 Hpc - Guide vcd network concepts update/fix
  links/network/network
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pt-pt.md
Labels: Update request, FIX, Priority: Low

#7067 Update - Hpc guide kms
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pt-pt.md
Labels: Update request, Priority: Low

#7073 Update - VCD faq trad
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-faq/guide.pt-pt.md
Labels: Update request, Priority: Low

#7084 KevS-Optimisation-log-for-WebCloudDatabases
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.de-de.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-asia.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-au.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-ca.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-ie.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-sg.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-us.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.es-es.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.es-us.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.fr-fr.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.it-it.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.pt-pt.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/meta.yaml
Labels: Minor update, Translations

#7089 IP Blocklist - Translation minor fix for IT version
  pages/network/additional_ip/blocklist_ip_delist/guide.it-it.md
Labels: FIX

#7092 Public Cloud FAQ - PL hierarchy fix
  pages/public_cloud/compute/faq_pci/guide.pl-pl.md
Labels: FIX

#7093 HDS certification - Updating info about Advance ranges
  pages/account_and_service_management/account_information/hds_certification/guide.de-de.md
  pages/account_and_service_management/account_information/hds_certification/guide.en-asia.md
  pages/account_and_service_management/account_information/hds_certification/guide.en-au.md
  pages/account_and_service_management/account_information/hds_certification/guide.en-ca.md
  pages/account_and_service_management/account_information/hds_certification/guide.en-gb.md
  pages/account_and_service_management/account_information/hds_certification/guide.en-ie.md
  pages/account_and_service_management/account_information/hds_certification/guide.en-sg.md
  pages/account_and_service_management/account_information/hds_certification/guide.en-us.md
  pages/account_and_service_management/account_information/hds_certification/guide.es-es.md
  pages/account_and_service_management/account_information/hds_certification/guide.es-us.md
  pages/account_and_service_management/account_information/hds_certification/guide.fr-ca.md
  pages/account_and_service_management/account_information/hds_certification/guide.fr-fr.md
  pages/account_and_service_management/account_information/hds_certification/guide.it-it.md
  pages/account_and_service_management/account_information/hds_certification/guide.pl-pl.md
  pages/account_and_service_management/account_information/hds_certification/guide.pt-pt.md
Labels: Minor update

#7079 FR rewrite overthebox network configuration guide
  pages/index.md
  pages/web_cloud/internet/overthebox/advanced_configuration_de_vlan/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/advanced_configuration_de_vlan/meta.yaml
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/4412.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/4413.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/4414.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/4415.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/4449.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step1-v2b-switchConfiguration-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step1-v3-1-removeInterface-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step1-v3-2-selectBridge-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step1-v3-3-addToBridge-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step1-v3-4-saveBridge-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step1-v3-5-confirmSchema-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-1-editInterface-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-ppp-2-editProtocol-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-ppp-2-generalSettings-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-ppp-3-advancedSettings-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-ppp-4-addVlan-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-ppp-5-configureVlan-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-ppp-6-useVlan-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-static-2-editProtocol-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step2-static-3-configureInterface-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-1-findDevice-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-2-addInterface-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-3-configureInterface-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-4-generalSettings-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-5-advancedSettings-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-6-firewallSettings-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-7-saveInterface-2024.png
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/images/step3-4g-8-confirmSettings-2024.png
Labels: Guides removal

#7090 SK-1516-TRANS-WEB-Email-configure_mail_apple
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_mail_macos/meta.yaml
Labels: Translations ONLY

#7062 Update - VM encryption on VMware with vNKP
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.pt-pt.md
Labels: Update request, Priority: Low

#7095 OverTheBox - Network interface configuration - Formats fixes
  pages/web_cloud/internet/overthebox/advanced_creer_une_interface_modem_manuellement/guide.fr-fr.md
Labels: FIX

#7097 SK-1691-TRANS-WEB-Emails-autoreply_responder
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/meta.yaml
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_automatic_replies/meta.yaml
Labels: Translations ONLY

#7074 KevS-SK1755-Update-manage-SSL-for-WebHosting
  pages/web_cloud/web_hosting/ssl_ev/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_ev/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.fr-fr.md
Labels: Update request

#7076 KevS-SK1778-Update-DNSSEC-for-DomainDNS
  pages/assets/screens/api/post-domain-zone-zonename-dnssec.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/ds-records/edit-plus-dashboard.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/ds-records/edit-plus.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/ds-records/not-empty.png
  pages/web_cloud/domains/dns_dnssec/guide.fr-ca.md
  pages/web_cloud/domains/dns_dnssec/guide.fr-fr.md
Labels: Update request

#7109 fix: add required credentials in guide use_object_storage_terraform_backend_state
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.de-de.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-asia.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-au.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-ca.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-gb.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-ie.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-sg.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-us.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.es-es.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.es-us.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.fr-ca.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.fr-fr.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.it-it.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.pl-pl.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.pt-pt.md
Labels: FIX

#7110 KevS-Primary-quickfix
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.fr-fr.md
Labels: FIX

#7104 update guide for configuring windows on VMs - KFT0022321
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/activate_windows_vm_hyperv/guide.fr-fr.md
Labels: Do not merge yet, Minor update

#7053 Update - Config vRack on PCI & Config vRack between SD & PCI
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/images/attach_network.png
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/images/configure_private_network.png
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/images/vrack2021-01.png
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/images/vrack2022-03.png
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/images/vrack2024-01.png
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/images/addprojectvrack.png
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/images/ordering_vrack_2024.png
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/images/vrack5-2024.png
Labels: Do not merge yet, Minor update
