Repository ovh/docs, pull requests merged in 2024-07, with the labels that each got.

#6514 fix: change messages to _doc in OpenSearch API documentation
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_opensearch_api_mutualized_input/guide.pt-pt.md
Labels: FIX

#6516 fix(ldp): clarify data gathering tools upgrade
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/getting_started_responsibility_model/guide.pt-pt.md
Labels: Minor update

#6518 [Web Hosting] Placeholder - Git integration
  pages/index.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pt-pt.md
  pages/web_cloud/web_hosting/git_integration_webhosting/meta.yaml
Labels: Guide creation

#6396 AI Training new tutorial: Extract 3D model from video
  pages/index.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.de-de.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-au.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-es.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.it-it.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/meta.yaml
Labels: Guide creation

#6524 Fixes on various pages
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.de-de.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-au.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-es.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.it-it.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pt-pt.md
Labels: FIX

#6527 Fix AI S3 datastore add command
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.de-de.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-au.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-es.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.it-it.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pt-pt.md
Labels: FIX

#6529 AI/Neuralangelo - Link to S3 usage help page
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.de-de.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-au.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.en-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-es.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.es-us.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.it-it.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/training_tuto_11_3d_model_from_video/guide.pt-pt.md
Labels: Minor update

#6528 KMS - various minor correction and screenshot update to remove pre-prod URL
  pages/manage_and_operate/kms/quick-start/guide.de-de.md
  pages/manage_and_operate/kms/quick-start/guide.en-asia.md
  pages/manage_and_operate/kms/quick-start/guide.en-au.md
  pages/manage_and_operate/kms/quick-start/guide.en-ca.md
  pages/manage_and_operate/kms/quick-start/guide.en-gb.md
  pages/manage_and_operate/kms/quick-start/guide.en-ie.md
  pages/manage_and_operate/kms/quick-start/guide.en-sg.md
  pages/manage_and_operate/kms/quick-start/guide.en-us.md
  pages/manage_and_operate/kms/quick-start/guide.es-es.md
  pages/manage_and_operate/kms/quick-start/guide.es-us.md
  pages/manage_and_operate/kms/quick-start/guide.fr-ca.md
  pages/manage_and_operate/kms/quick-start/guide.fr-fr.md
  pages/manage_and_operate/kms/quick-start/guide.it-it.md
  pages/manage_and_operate/kms/quick-start/guide.pl-pl.md
  pages/manage_and_operate/kms/quick-start/guide.pt-pt.md
  pages/manage_and_operate/kms/quick-start/images/order_kms_02.png
  pages/manage_and_operate/kms/quick-start/images/swagger.png
Labels: Minor update

#6531 Chore(k8s): Update reserved ressources
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pt-pt.md
Labels: Minor update

#6532 SK-1614-TRANS-EN-WEB-Domain-DNS-DKIM
  pages/web_cloud/domains/dns_zone_dkim/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_dkim/guide.en-au.md
  pages/web_cloud/domains/dns_zone_dkim/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_dkim/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_dkim/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_dkim/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_dkim/guide.en-us.md
  pages/web_cloud/domains/dns_zone_dkim/guide.fr-fr.md
Labels: Translations ONLY

#6536 SK-1614-TRANS-DE-WEB-Domain-DNS-DKIM
  pages/web_cloud/domains/dns_zone_dkim/guide.de-de.md
Labels: Translations ONLY

#6545 VMware - exporting logs to LDP - Minor fix on FR versions
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-fr.md
Labels: FIX

#6519 [S3 Object Storage] - S3 location - Updating regions table
  pages/storage_and_backup/object_storage/cold_archive_getting_started/guide.fr-ca.md
  pages/storage_and_backup/object_storage/cold_archive_getting_started/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_location/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_location/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_location/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_location/guide.pt-pt.md
Labels: Minor update, Quality Check

#6552 MKS - Software versions - Header fix
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pt-pt.md
Labels: FIX

#6550 KMS - Getting started - example update
  pages/manage_and_operate/kms/quick-start/guide.de-de.md
  pages/manage_and_operate/kms/quick-start/guide.en-asia.md
  pages/manage_and_operate/kms/quick-start/guide.en-au.md
  pages/manage_and_operate/kms/quick-start/guide.en-ca.md
  pages/manage_and_operate/kms/quick-start/guide.en-gb.md
  pages/manage_and_operate/kms/quick-start/guide.en-ie.md
  pages/manage_and_operate/kms/quick-start/guide.en-sg.md
  pages/manage_and_operate/kms/quick-start/guide.en-us.md
  pages/manage_and_operate/kms/quick-start/guide.es-es.md
  pages/manage_and_operate/kms/quick-start/guide.es-us.md
  pages/manage_and_operate/kms/quick-start/guide.fr-ca.md
  pages/manage_and_operate/kms/quick-start/guide.fr-fr.md
  pages/manage_and_operate/kms/quick-start/guide.it-it.md
  pages/manage_and_operate/kms/quick-start/guide.pl-pl.md
  pages/manage_and_operate/kms/quick-start/guide.pt-pt.md
Labels: Minor update

#6507 Hk public cloud versioning doc
  pages/index.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_versioning/images/Withversioningdisabled.png
  pages/storage_and_backup/object_storage/s3_versioning/images/Withversioningdisabled2.png
  pages/storage_and_backup/object_storage/s3_versioning/images/Withversioningenabled.png
  pages/storage_and_backup/object_storage/s3_versioning/images/Withversioningenabled2.png
  pages/storage_and_backup/object_storage/s3_versioning/images/Withversioningenabled3.png
  pages/storage_and_backup/object_storage/s3_versioning/images/versionning.png
  pages/storage_and_backup/object_storage/s3_versioning/meta.yaml
Labels: Guide creation

#6549 feat: add doc for monitoring PCI or VPS instances with MKS
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/images/add_user_1.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/images/add_user_2.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/images/download_openrc.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/images/ovh_creds.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/images/prom_targets_openstack.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/images/prom_targets_ovhcloud.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/images/prom_targets_static.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/monitoring-pci-instances-prometheus/meta.yaml
Labels: Guide creation

#6551 Dedicated Servers - Bridged Additional IP - Adding information about availability for HG/Scale/Advance - ESXi
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.pt-pt.md
Labels: Minor update

#6553 Dedicated Servers - Bridged Additional IP - Adding information about availability for HG/Scale/Advance - Proxmox
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.pt-pt.md
Labels: Minor update

#6544 PGA - HPC : Update/fix port (from 9081 to 9071) on Zerto guides
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.de-de.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.en-asia.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.en-au.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.en-ca.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.en-gb.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.en-ie.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.en-sg.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.en-us.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.es-es.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.es-us.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.fr-ca.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.fr-fr.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.pl-pl.md
  pages/bare_metal_cloud/managed_bare_metal/zerto-virtual-replication-customer-to-ovhcloud/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/zerto-virtual-replication-customer-to-ovhcloud/guide.pt-pt.md
Labels: Minor update

#6562 S3 Object Storage - Asynchronous replication - Table update
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_asynchronous_replication/guide.pt-pt.md
Labels: Minor update

#6564 Translations for deploying a GPU instance & image path update
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.de-de.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.en-asia.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.en-au.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.en-ca.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.en-gb.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.en-ie.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.en-sg.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.en-us.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.es-es.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.es-us.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.fr-ca.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.fr-fr.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.it-it.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.pl-pl.md
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.pt-pt.md
Labels: Translations ONLY

#6566 Public Cloud Instances - Deploy a GPU instance - PL image fix
  pages/public_cloud/compute/deploy_a_gpu_instance/guide.pl-pl.md
Labels: FIX

#6290 Web Hosting - Percona Server for MySQL migration informations
  pages/index.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.de-de.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.en-asia.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.en-au.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.en-ca.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.en-gb.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.en-ie.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.en-sg.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.en-us.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.es-es.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.es-us.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.fr-ca.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.fr-fr.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.it-it.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.pl-pl.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/guide.pt-pt.md
  pages/web_cloud/web_hosting/percona_server_mysql_migration_info/meta.yaml
Labels: Guide creation

#6563 DBaaS - MongoDB - Minor updates - SK1607 & SK1608
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pt-pt.md
Labels: Minor update

#6572 Hb raci trusted exchange
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/raci_dedicated_email_infrastructure/meta.yaml
Labels: Guide creation

#6576 Compute - Local Zones Capabilities - Adding Windows Images as unsupported for GA
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.de-de.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-asia.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-au.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-ca.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-gb.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-ie.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-sg.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.en-us.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.es-es.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.es-us.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.fr-ca.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.fr-fr.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.it-it.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.pl-pl.md
  pages/public_cloud/compute/local-zones-capabilities-limitations/guide.pt-pt.md
Labels: Minor update

#6579 VMware - VNKP - Minor fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vm_encrypt-vnkp/guide.pt-pt.md
Labels: FIX

#6596 remove "sudo" in file list
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.pt-pt.md
Labels: Priority: Low

#6598 KevS-SK1625-KFT0017854-Update-wordpress-getting-started-TRANSLATIONS
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.de-de.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.en-asia.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.en-au.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.en-ca.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.en-gb.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.en-ie.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.en-sg.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.en-us.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.es-es.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.es-us.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.it-it.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.pl-pl.md
  pages/web_cloud/web_hosting/wordpress_first-steps/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6580 Dedicated Servers - Network bridge - Updating applicable servers ranges
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pt-pt.md
Labels: Minor update, Translations, Quality Check

#6602 SK1627 - Loading OpenStack variables - Security update
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.de-de.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-asia.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-au.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-ca.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-gb.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-ie.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-sg.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.en-us.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.es-es.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.es-us.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.fr-ca.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.fr-fr.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.it-it.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.pl-pl.md
  pages/public_cloud/compute/loading_openstack_environment_variables/guide.pt-pt.md
Labels: Minor update

#6581 Dedicated Servers - IPv6 - Adding information about new ranges capacities
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.pt-pt.md
Labels: Minor update, Translations, Quality Check

#6601 IAM in Control Panel; minor fixes
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-asia.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-au.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-ca.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-gb.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-ie.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-sg.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-us.md
Labels: FIX, Priority: Low

#6604 Fixes on various pages
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_edit/guide.fr-fr.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.fr-fr.md
Labels: FIX

#6605 KevS-KFT0016460-SK1626-Update-php-version-ovhconfig-for-WebHosting
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.fr-fr.md
Labels: Minor update

#6603 Dedicated Servers - Configuring the network on Proxmox VE - Updating title & excerpt
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-network-HG-Scale/guide.pt-pt.md
  pages/index.md
Labels: Minor update

#6590 feat(bare_metal_cloud/api-os-installation): post-installation scripts
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/api-os-installation/guide.pt-pt.md
Labels: Do not merge yet

#6610 KevS-SK1628-KFT0018766-Update-Enable-emails-included-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/activate-email-hosting/guide.de-de.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.en-asia.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.en-au.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.en-ca.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.en-gb.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.en-ie.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.en-sg.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.en-us.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.es-es.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.es-us.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.it-it.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6613 KevS-SK1632-KFT0018830-Update-DNS-records-for-DomainDNS
  pages/web_cloud/domains/dns_zone_records/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_records/guide.fr-fr.md
Labels: Minor update

#6619 Fixes on various pages
  pages/bare_metal_cloud/dedicated_servers/rtm-uninstall/guide.pt-pt.md
  pages/web_cloud/internet/overthebox/plus_itv2_installation/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/plus_itv2_installation/images/step3-login.png
Labels: FIX

#6618 KevS-SK1632-KFT0018830-Update-DNS-records-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/dns_zone_records/guide.de-de.md
  pages/web_cloud/domains/dns_zone_records/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_records/guide.en-au.md
  pages/web_cloud/domains/dns_zone_records/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_records/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_records/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_records/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_records/guide.en-us.md
  pages/web_cloud/domains/dns_zone_records/guide.es-es.md
  pages/web_cloud/domains/dns_zone_records/guide.es-us.md
  pages/web_cloud/domains/dns_zone_records/guide.it-it.md
  pages/web_cloud/domains/dns_zone_records/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_records/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6624 Add billing information on revert a flex instance - KFT0018667
  pages/public_cloud/compute/revert_a_flex_instance/guide.de-de.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.en-asia.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.en-au.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.en-ca.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.en-gb.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.en-ie.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.en-sg.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.en-us.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.es-es.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.es-us.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.fr-ca.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.fr-fr.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.it-it.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.pl-pl.md
  pages/public_cloud/compute/revert_a_flex_instance/guide.pt-pt.md
Labels: KFT

#6609 Dedicated Servers - IPv6 Block in vRack - Beta updates
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/011.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/02.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/03.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/04.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/05.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/06.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/101.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/102.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/103.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/104.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/105.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/106.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/107.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/220.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/221.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/299.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/300.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/301.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/302.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/303.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/304.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/500.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/600.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/601.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/602.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/700.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/701.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/702.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/710.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/800.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/801.png
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/images/location.png
Labels: Priority: Dependency

#6632 fix(LDP): EN - bad indentation in config snippet
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_kubernetes_fluent_bit/guide.pt-pt.md
Labels: Priority: Dependency

#6629 Public Cloud Databases - add Kafka guide for Python developer
  pages/index.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.de-de.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.en-au.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.en-us.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.es-es.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.es-us.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.it-it.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/kafka_04_dev_python_basics/meta.yaml
Labels: Guide creation, Priority: Low

#6634 FR new overthebox migration offer
  pages/assets/screens/control_panel/product-selection/telecom/tpl-telecom-01-fr-internet.png
  pages/assets/screens/control_panel/product-selection/telecom/tpl-telecom-05-fr-otb.png
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/web_cloud/internet/overthebox/offer_migration/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/offer_migration/images/manager-changeOffer-2024.png
  pages/web_cloud/internet/overthebox/offer_migration/images/manager-confirmMigration-2024.png
  pages/web_cloud/internet/overthebox/offer_migration/images/manager-payment-2024.png
  pages/web_cloud/internet/overthebox/offer_migration/images/manager-selectAddress-2024.png
  pages/web_cloud/internet/overthebox/offer_migration/images/manager-selectOffer-2024.png
  pages/web_cloud/internet/overthebox/offer_migration/meta.yaml
Labels: Guide creation, Priority: Dependency

#6635 FR update overthebox faq for new offer
  pages/web_cloud/internet/overthebox/install_faq/guide.fr-fr.md
Labels: Priority: Dependency

#6638 OverTheBox - change offer - image fix
  pages/web_cloud/internet/overthebox/offer_migration/guide.fr-fr.md
Labels: FIX

#6623 KevS-SK1633-FB-Create-Git-Integration-for-WebHosting-EN-TRANSLATIONS
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pt-pt.md
Labels: FIX, Translations

#6633 KevS-SK1634-Create-SharedSQL-how-to-retrieve-dump-via-API-when-db-deleted-for-WebHosting
  links/api
  pages/assets/screens/api/get-hosting-web-servicename-dump-id-research.png
  pages/assets/screens/api/get-hosting-web-servicename-dump-id-response.png
  pages/assets/screens/api/get-hosting-web-servicename-dump-id.png
  pages/assets/screens/api/get-hosting-web-servicename-dump-research.png
  pages/assets/screens/api/get-hosting-web-servicename-dump-response.png
  pages/assets/screens/api/get-hosting-web-servicename-dump.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/find-webhosting-name.png
  pages/index.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.fr-fr.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/meta.yaml
Labels: Guide creation, Priority: Low

#6639 Public Cloud : Perform Forensics on Public Cloud Compute Instance
  pages/index.md
  pages/public_cloud/compute/forensics/guide.de-de.md
  pages/public_cloud/compute/forensics/guide.en-asia.md
  pages/public_cloud/compute/forensics/guide.en-au.md
  pages/public_cloud/compute/forensics/guide.en-ca.md
  pages/public_cloud/compute/forensics/guide.en-gb.md
  pages/public_cloud/compute/forensics/guide.en-ie.md
  pages/public_cloud/compute/forensics/guide.en-sg.md
  pages/public_cloud/compute/forensics/guide.en-us.md
  pages/public_cloud/compute/forensics/guide.es-es.md
  pages/public_cloud/compute/forensics/guide.es-us.md
  pages/public_cloud/compute/forensics/guide.fr-ca.md
  pages/public_cloud/compute/forensics/guide.fr-fr.md
  pages/public_cloud/compute/forensics/guide.it-it.md
  pages/public_cloud/compute/forensics/guide.pl-pl.md
  pages/public_cloud/compute/forensics/guide.pt-pt.md
  pages/public_cloud/compute/forensics/images/rc-file.png
  pages/public_cloud/compute/forensics/meta.yaml
Labels: Guide creation, Priority: Urgent

#6640 SAP Cookbook - Update the documentation
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.pt-pt.md
Labels: Minor update, Priority: Low

#6642 fix(LDP): EN - rewrite Rust guide for US launch
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_rust_loggers/guide.pt-pt.md
Labels: Priority: Dependency

#6645 Minor fix to be more precise
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_sap_hana_template_vmware/guide.pt-pt.md
Labels: Minor update, Priority: Low

#6648 KevS-Update-GIT-with-WebHosting-button-EN-corrections
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pt-pt.md
Labels: Minor update

#6643 EN-update-KMS architecture edit
  pages/manage_and_operate/kms/architecture-overview/guide.en-gb.md
Labels: Priority: Low

#6625 Migration to VCD
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/meta.yaml
  pages/index.md
Labels: Guide creation, Author review needed

#6650 KevS-SK1634-Create-SharedSQL-how-to-retrieve-dump-via-API-when-db-deleted-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.de-de.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.en-au.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.en-us.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.es-es.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.es-us.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.fr-fr.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.it-it.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.pt-pt.md
Labels: Translations ONLY

#6660 Fix migration to VCD
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: FIX

#6663 Fix 3 migration to VCD, 2 links in fr fr-ca tab
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: FIX

#6652 FB - Migrate Xara website to OVHcloud
  pages/index.md
  pages/web_cloud/web_hosting/migrate_xara_website_to_ovh/guide.fr-fr.md
  pages/web_cloud/web_hosting/migrate_xara_website_to_ovh/meta.yaml
Labels: Guide creation

#6678 fix(LDP): pattern and configuration for ldp-tail
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/cli_ldp_tail/guide.pt-pt.md
Labels: Priority: Low

#6668 Hk public cloud databases restore backup add region
  pages/public_cloud/public_cloud_databases/databases_06_restore_backup/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_06_restore_backup/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_06_restore_backup/images/selectRegion.png
Labels: Quality Check

#6677 Fix: update configuration to modern apache versions
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/ingestion_apache/guide.pt-pt.md
Labels: Quality Check, Priority: Low
