Repository ovh/docs, pull requests merged in 2024-09, with the labels that each got.

#6804 KevS-Quickfix-PT-into-ES-guide-index-of-diagnosis
  pages/web_cloud/web_hosting/diagnostic-index-of/guide.es-es.md
  pages/web_cloud/web_hosting/diagnostic-index-of/guide.es-us.md
Labels: Translations ONLY, Minor update

#6802 SK-1514-WEB-Domain-DNS-configuring-MX-Add_sentence_Ex_private_dedi
  pages/web_cloud/domains/dns_zone_mx/guide.de-de.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_mx/guide.es-es.md
  pages/web_cloud/domains/dns_zone_mx/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_mx/guide.it-it.md
  pages/web_cloud/domains/dns_zone_mx/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_mx/guide.pt-pt.md
Labels: Translations

#6812 NAS-HA - NFS mount - Last update translations
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.de-de.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.en-asia.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.en-au.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.en-ca.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.en-gb.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.en-ie.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.en-sg.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.en-us.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.es-es.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.es-us.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.fr-ca.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.fr-fr.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.it-it.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.pl-pl.md
  pages/storage_and_backup/file_storage/ha_nas/nas_nfs/guide.pt-pt.md
Labels: Translations ONLY

#6750 QuickFix-PublicCloud-Kubernetes-High_Speed_Gen2
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.pt-pt.md
Labels: FIX, Edition needed

#6816 VMware - VM Encrypt - Typo fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_overall_vm-encrypt/guide.pt-pt.md
Labels: FIX

#6817 KevS-SK1678-KFT0018241-Update-Create-sharedSQL-for-WebHosting
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#6818 KevS-SK1679-KFT00199C1-Update-Application-firewall-for-WebHosting
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#6819 KevS-SK1680-KFT0020126-Update-Dynhost-for-DomainDNS
  pages/web_cloud/domains/dns_dynhost/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#6821 MRS - Updating links to force a guide update
  links/public-cloud/compute
  links/public-cloud/prices
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.pt-pt.md
Labels: FIX, Minor update

#6824 Fixing links on various pages
  links/hosted-private-cloud/veeam-managed-backup
  pages/public_cloud/compute/create_restore_a_virtual_server_with_a_backup/guide.de-de.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.de-de.md
  pages/public_cloud/compute/managing_snapshots_in_horizon/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-ca.md
Labels: FIX

#6825 MRS - Forced update to troubleshoot an image issue
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/creating-kubernetes-pci-compute-instances/guide.pt-pt.md
Labels: FIX

#6801 KevS-SK1675-KFT19299-Update-EOS-EOL-SQL-Databases-for-WebHosting
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#6827 KevS-SK1640-Update-Automatic-emails-for-WebHosting
  pages/web_cloud/web_hosting/mail_function_script_records/guide.fr-ca.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.fr-fr.md
Labels: Minor update

#6814 FB - API webhosting guide
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/web_cloud/web_hosting/api_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/api_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/api_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/api_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/api_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/api_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/api_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/api_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/api_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/api_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/api_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/api_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/api_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/api_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/api_webhosting/guide.pt-pt.md
  pages/web_cloud/web_hosting/api_webhosting/meta.yaml
Labels: Guide creation

#6826 KevS-SK1678-SK1679-SK1680-TRANSLATIONS
  pages/web_cloud/domains/dns_dynhost/guide.de-de.md
  pages/web_cloud/domains/dns_dynhost/guide.en-gb.md
  pages/web_cloud/domains/dns_dynhost/guide.en-ie.md
  pages/web_cloud/domains/dns_dynhost/guide.es-es.md
  pages/web_cloud/domains/dns_dynhost/guide.it-it.md
  pages/web_cloud/domains/dns_dynhost/guide.pl-pl.md
  pages/web_cloud/domains/dns_dynhost/guide.pt-pt.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-asia.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-au.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-ca.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-ie.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-sg.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-us.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.es-us.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.pt-pt.md
  pages/web_cloud/web_hosting/sql_create_database/guide.de-de.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-au.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_create_database/guide.en-us.md
  pages/web_cloud/web_hosting/sql_create_database/guide.es-es.md
  pages/web_cloud/web_hosting/sql_create_database/guide.es-us.md
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_create_database/guide.fr-fr.md
  pages/web_cloud/web_hosting/sql_create_database/guide.it-it.md
  pages/web_cloud/web_hosting/sql_create_database/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_create_database/guide.pt-pt.md
Labels: KFT / Issue, Minor update, Translations

#6830 KevS-SK1640-Update-Automatic-emails-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/mail_function_script_records/guide.de-de.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-asia.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-au.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-ca.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-gb.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-ie.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-sg.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-us.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.es-es.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.es-us.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.fr-ca.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.fr-fr.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.it-it.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.pl-pl.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.pt-pt.md
Labels: Minor update, Translations

#6831 Translations for creating an instance in Horizon
  pages/public_cloud/compute/create_instance_in_horizon/guide.de-de.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.en-asia.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.en-au.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.en-ca.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.en-gb.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.en-ie.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.en-sg.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.en-us.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.es-es.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.es-us.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.fr-ca.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.fr-fr.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.it-it.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.pl-pl.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.pt-pt.md
Labels: Translations ONLY

#6832 KevS-SK1675-KFT19299-Update-EOS-EOL-SQL-Databases-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/sql_eos_eol/guide.de-de.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-au.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-us.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.es-es.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.es-us.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-fr.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.it-it.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.pt-pt.md
Labels: KFT / Issue, Minor update, Translations

#6813 KevS-SK1676-KFT0019234-Create-How-to-modify-domain-associated-with-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.en-asia.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.en-au.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.en-ca.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.en-ie.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.en-sg.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.en-us.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.es-us.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_modify_domain/guide.pt-pt.md
Labels: Guide creation, Translations ONLY, KFT / Issue

#6837 Dedicated Servers - SK-1644 - Updating monitoring IP list
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_ip_monitoring/guide.pt-pt.md
Labels: Minor update

#6838 Fixes on several guides following support agents feedback (KFT)
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/hyperv-network-HG-Scale/guide.en-us.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_avec_lapi_ovh_en_php/guide.en-gb.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_avec_lapi_ovh_en_php/guide.en-ie.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_avec_lapi_ovh_en_php/guide.fr-fr.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_avec_lapi_ovh_en_php/guide.it-it.md
  pages/web_cloud/messaging/sms/envoyer_des_sms_avec_lapi_ovh_en_php/guide.pl-pl.md
  pages/web_cloud/phone_and_fax/voip/configurer-consulter-repondeur-ligne-ovh/guide.fr-fr.md
Labels: FIX, KFT / Issue

#6841 Account management - Improvements following customers feedback
  pages/account_and_service_management/account_information/all_about_username/guide.de-de.md
  pages/account_and_service_management/account_information/all_about_username/guide.en-asia.md
  pages/account_and_service_management/account_information/all_about_username/guide.en-au.md
  pages/account_and_service_management/account_information/all_about_username/guide.en-ca.md
  pages/account_and_service_management/account_information/all_about_username/guide.en-gb.md
  pages/account_and_service_management/account_information/all_about_username/guide.en-ie.md
  pages/account_and_service_management/account_information/all_about_username/guide.en-sg.md
  pages/account_and_service_management/account_information/all_about_username/guide.en-us.md
  pages/account_and_service_management/account_information/all_about_username/guide.es-es.md
  pages/account_and_service_management/account_information/all_about_username/guide.es-us.md
  pages/account_and_service_management/account_information/all_about_username/guide.fr-ca.md
  pages/account_and_service_management/account_information/all_about_username/guide.fr-fr.md
  pages/account_and_service_management/account_information/all_about_username/guide.it-it.md
  pages/account_and_service_management/account_information/all_about_username/guide.pl-pl.md
  pages/account_and_service_management/account_information/all_about_username/guide.pt-pt.md
  pages/account_and_service_management/account_information/faq-account-management/guide.fr-fr.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.de-de.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.en-asia.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.en-au.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.en-ca.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.en-gb.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.en-ie.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.en-sg.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.en-us.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.es-es.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.es-us.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.fr-ca.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.fr-fr.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.it-it.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.pl-pl.md
  pages/account_and_service_management/account_information/ovhcloud-account-creation/guide.pt-pt.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.de-de.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.en-asia.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.en-au.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.en-ca.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.en-gb.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.en-ie.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.en-sg.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.en-us.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.es-es.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.es-us.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.fr-ca.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.fr-fr.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.it-it.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.pl-pl.md
  pages/account_and_service_management/account_information/ovhcloud-account-login/guide.pt-pt.md
Labels: KFT / Issue

#6843 Account management FAQ - Typo fix
  pages/account_and_service_management/account_information/faq-account-management/guide.fr-fr.md
Labels: FIX

#6846 VMware - SK-1688 - Maintenance operations - Format improvements
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-fr.md
Labels: Minor update

#6840 SK-1515-TRANS-WEB-Domain-DNS-SPF
  pages/web_cloud/domains/dns_zone_spf/guide.de-de.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-au.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-us.md
  pages/web_cloud/domains/dns_zone_spf/guide.es-es.md
  pages/web_cloud/domains/dns_zone_spf/guide.es-us.md
  pages/web_cloud/domains/dns_zone_spf/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_spf/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_spf/guide.it-it.md
  pages/web_cloud/domains/dns_zone_spf/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_spf/guide.pt-pt.md
Labels: Translations ONLY

#6845 SK-1660-WEB-Emails-Zimbra-Getting_started
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_organization.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_organization_filter.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/meta.yaml
Labels: Guide creation

#6848 VMware - SK1688 - Maintenance Operations - Format improvements
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.pt-pt.md
Labels: Minor update

#6858 Web Hosting - Clusters IPs - Table fix
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-asia.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-au.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-ca.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-gb.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-ie.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-sg.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-us.md
Labels: FIX

#6854 MRS - Supported versions and lifecycle policy
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_rancher_service/lifecycle-policy/meta.yaml
Labels: Guide creation, Priority: Dependency

#6855 [AI and Machine Learning] - Remove a useless AI Notebooks guide
  pages/index.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.de-de.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.en-au.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.en-us.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.es-es.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.es-us.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.it-it.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/notebook_guide_concepts_notebooks/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.de-de.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.en-au.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.en-us.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.es-es.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.es-us.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.it-it.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/notebook_tuto_01_first_ml_model_miniconda/meta.yaml
Labels: Guides removal

#6862 KevS-Quifix-SSL-guide
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.pt-pt.md
Labels: FIX

#6870 KevS-Bank-of-Screen-storage-corrections
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/ongoing-tasks/firewall-planned.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/ongoing-tasks/not-empty.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/ongoing-tasks/ongoing-task-git-activation.png
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pt-pt.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-asia.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-au.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-ca.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-ie.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-sg.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-us.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.es-us.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.pt-pt.md
Labels: FIX

#6865 Guide update KFT0018799 & KFT0020012
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/configure-ipv6/guide.pt-pt.md
Labels: KFT / Issue, Translations

#6868 Hk public cloud update load balancer
  pages/index.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/images/ChoiceOptionLoadBalancer.png
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/images/editButtonLoadBalancer.png
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/images/sizeLoadBalancer.png
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/meta.yaml
Labels: Guide creation

#6653 KevS-SK1639-Update-Modify-DNS-servers-for-DomainDNS
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/modify-my-dns-servers-1-apply-configuration.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/modify-my-dns-servers-1.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/modify-my-dns-servers-2-apply-configuration.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/modify-my-dns-servers-2.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/modify-my-dns-servers-3-apply-configuration.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/modify-my-dns-servers-3.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/modify-my-dns-servers.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/tab.png
  pages/web_cloud/domains/dns_server_edit/guide.de-de.md
  pages/web_cloud/domains/dns_server_edit/guide.en-asia.md
  pages/web_cloud/domains/dns_server_edit/guide.en-au.md
  pages/web_cloud/domains/dns_server_edit/guide.en-ca.md
  pages/web_cloud/domains/dns_server_edit/guide.en-gb.md
  pages/web_cloud/domains/dns_server_edit/guide.en-ie.md
  pages/web_cloud/domains/dns_server_edit/guide.en-sg.md
  pages/web_cloud/domains/dns_server_edit/guide.en-us.md
  pages/web_cloud/domains/dns_server_edit/guide.es-es.md
  pages/web_cloud/domains/dns_server_edit/guide.es-us.md
  pages/web_cloud/domains/dns_server_edit/guide.fr-ca.md
  pages/web_cloud/domains/dns_server_edit/guide.fr-fr.md
  pages/web_cloud/domains/dns_server_edit/guide.it-it.md
  pages/web_cloud/domains/dns_server_edit/guide.pl-pl.md
  pages/web_cloud/domains/dns_server_edit/guide.pt-pt.md
Labels: Translations

#6880 DNS - Editing DNS servers - DE title fix
  pages/web_cloud/domains/dns_server_edit/guide.de-de.md
Labels: FIX

#6879 Object Storage - Update S3 FAQ - Adding Asynchronous Replication info
  pages/storage_and_backup/object_storage/s3_faq/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_faq/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_faq/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_faq/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_faq/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_faq/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_faq/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_faq/guide.pt-pt.md
Labels: Minor update

#6882 Hpc - VCD Network : Guide update and fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_creation/guide.pt-pt.md
Labels: Update request, FIX, Priority: Low

#6885 Fixes on several pages
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.de-de.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.en-asia.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.en-au.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.en-ca.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.en-gb.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.en-ie.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.en-sg.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.en-us.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.es-es.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.es-us.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.fr-ca.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.it-it.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.pl-pl.md
  pages/account_and_service_management/account_information/security-specification-privatecloud-VMware/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/sgx-enable-and-use/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/sgx-enable-and-use/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/sgx-enable-and-use/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/sgx-enable-and-use/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/vps_legacy_control_panel/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_veeam_backup_sap_hana/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.fr-fr.md
Labels: FIX

#6767 Hpc - Guide creation datastore upload on managed vSphere
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_1.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_3.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_4.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_folder_upload.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_inventory_2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_move.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_upload_1.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/datastore_upload_rename.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/global_inventory.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/global_inventory_datastores.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/global_inventory_datastores_2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/inventory_datastore.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/images/vsphere_home.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/meta.yaml
  pages/index.md
Labels: Guide creation, Quality Check, Priority: Urgent

#6886 KFT0020698 - Fixing Discord links on all concerned pages
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.pt-pt.md
  pages/public_cloud/data_platform/general-signin_signup/guide.de-de.md
  pages/public_cloud/data_platform/general-signin_signup/guide.en-asia.md
  pages/public_cloud/data_platform/general-signin_signup/guide.en-au.md
  pages/public_cloud/data_platform/general-signin_signup/guide.en-ca.md
  pages/public_cloud/data_platform/general-signin_signup/guide.en-gb.md
  pages/public_cloud/data_platform/general-signin_signup/guide.en-ie.md
  pages/public_cloud/data_platform/general-signin_signup/guide.en-sg.md
  pages/public_cloud/data_platform/general-signin_signup/guide.en-us.md
  pages/public_cloud/data_platform/general-signin_signup/guide.es-es.md
  pages/public_cloud/data_platform/general-signin_signup/guide.es-us.md
  pages/public_cloud/data_platform/general-signin_signup/guide.fr-ca.md
  pages/public_cloud/data_platform/general-signin_signup/guide.fr-fr.md
  pages/public_cloud/data_platform/general-signin_signup/guide.it-it.md
  pages/public_cloud/data_platform/general-signin_signup/guide.pl-pl.md
  pages/public_cloud/data_platform/general-signin_signup/guide.pt-pt.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.de-de.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-asia.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-au.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-ca.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-gb.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-ie.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-sg.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.en-us.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.es-es.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.es-us.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.fr-ca.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.fr-fr.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.it-it.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.pl-pl.md
  pages/public_cloud/data_platform/general-what_is_the_data_platform/guide.pt-pt.md
Labels: FIX, KFT / Issue

#6790 Hpc/Ldp - Guide update LDP in managed vSphere
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.pt-pt.md
  pages/index.md
Labels: Update request, Priority: Dependency

#6894 UPD Snapshots for VPS
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/using-snapshots-on-a-vps/images/snapshot_vps_cancel.png
Labels: KFT / Issue, Minor update, Translations

#6725 Hk public cloud best practises project structuring
  pages/index.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.de-de.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-asia.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-au.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-ca.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-gb.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-ie.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-sg.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-us.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.es-es.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.es-us.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.fr-ca.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.fr-fr.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.it-it.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.pl-pl.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.pt-pt.md
  pages/public_cloud/compute/securing_and_structuring_projects/images/Actions.png
  pages/public_cloud/compute/securing_and_structuring_projects/images/Add_user_groups.png
  pages/public_cloud/compute/securing_and_structuring_projects/images/Product_types_resources.png
  pages/public_cloud/compute/securing_and_structuring_projects/meta.yaml
Labels: Guide creation

#6903 Fixing web links
  pages/web_cloud/email_and_collaborative_solutions/migrating/migration_omm/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_delegation/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_filters/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/using_the_outlook_web_app_webmail/owa_directory_sharing/guide.en-gb.md
Labels: FIX

#6898 Public Cloud - Local Zone VPN-as-a-Service (VPNaaS) with Tailscale integration
  pages/index.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.de-de.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.en-asia.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.en-au.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.en-ca.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.en-gb.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.en-ie.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.en-sg.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.en-us.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.es-es.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.es-us.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.fr-ca.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.fr-fr.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.it-it.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.pl-pl.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/guide.pt-pt.md
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/images/tailscale01.png
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/images/tailscale02.png
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/images/tailscale03.png
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/images/tailscale04.png
  pages/public_cloud/compute/local-zones-vpn-tailscale-integration/meta.yaml
Labels: Guide creation

#6910 Public Cloud - Projects security-structure - Image fix attempt
  pages/public_cloud/compute/securing_and_structuring_projects/guide.de-de.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-asia.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-au.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-ca.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-gb.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-ie.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-sg.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.en-us.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.es-es.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.es-us.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.fr-ca.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.fr-fr.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.it-it.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.pl-pl.md
  pages/public_cloud/compute/securing_and_structuring_projects/guide.pt-pt.md
  pages/public_cloud/compute/securing_and_structuring_projects/images/actions2.png
Labels: FIX

#6911 MKS - Typo fix
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pt-pt.md
Labels: FIX

#6884 Hpc - VCD migration guide update and fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: Update request, FIX

#6917 Update API log forward route
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.de-de.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.en-asia.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.en-au.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.en-ca.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.en-gb.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.en-ie.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.en-sg.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.en-us.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.es-es.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.es-us.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.fr-ca.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.fr-fr.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.it-it.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.pl-pl.md
  pages/manage_and_operate/iam/iam-logs-forwarding/guide.pt-pt.md
Labels: Minor update, Priority: Low

#6901 Hpc/Backup - Guide update : Add update credentials control panel and api
  links/hosted-private-cloud/veeam-enterprise
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.de-de.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.en-asia.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.en-au.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.en-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.en-gb.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.en-ie.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.en-sg.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.en-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.es-es.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.es-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.fr-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.fr-fr.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.it-it.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.pl-pl.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/guide.pt-pt.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/images/veeam_update_cred.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_veeam_backup_replication/images/veeam_update_cred_2.png
Labels: Update request

#6896 FB - Link OVHcloud domain to a Google Site
  pages/index.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-asia.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-au.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-gb.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-ie.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-sg.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.en-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.fr-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/guide.fr-fr.md
  pages/web_cloud/domains/how_to_connect_domain_to_google_site/meta.yaml
Labels: Guide creation

#6915 KevS-SK1687-Update-Database-diagnosis-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.de-de.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.en-asia.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.en-au.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.en-ca.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.en-gb.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.en-ie.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.en-sg.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.en-us.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.es-es.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.es-us.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.fr-ca.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.fr-fr.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.it-it.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.pl-pl.md
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.pt-pt.md
Labels: Minor update, Translations

#6918 KevS-SK1729-Update-CDN-for-WebHosting
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.fr-ca.md
  pages/web_cloud/web_hosting/cdn_how_to_use_cdn/guide.fr-fr.md
Labels: Minor update

#6920 removing obselete OS and minor update on Network IP aliasing
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.pt-pt.md
Labels: Update request, Translations

#6922 KevS-Broken-links-quickfixes
  pages/web_cloud/web_hosting/diagnosis_database_errors/guide.pt-pt.md
Labels: FIX

#6930 Typo fix in configure an ipv6 in a vrack
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pt-pt.md
Labels: FIX
