Repository ovh/docs, pull requests merged in 2024-12, with the labels that each got.

#7232 S3 Object Storage - SSE-C encryption - Minor update
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_encrypt_your_objects_with_sse_c/guide.pt-pt.md
Labels: Minor update

#7238 KevS-Integration-ES-video-change-offer-webhosting
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.es-es.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.es-us.md
  pages/web_cloud/web_hosting/how_to_upgrade_web_hosting_offer/guide.pt-pt.md
Labels: Update request, Minor update

#7234 fix(volume snapshot): update instructions and images
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.de-de.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.en-asia.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.en-au.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.en-ca.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.en-gb.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.en-ie.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.en-sg.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.en-us.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.es-es.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.es-us.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.fr-ca.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.fr-fr.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.it-it.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.pl-pl.md
  pages/public_cloud/compute/creating_a_volume_snapshot/guide.pt-pt.md
  pages/public_cloud/compute/creating_a_volume_snapshot/images/volume_snapshot01.png
  pages/public_cloud/compute/creating_a_volume_snapshot/images/volume_snapshot02.png
  pages/public_cloud/compute/creating_a_volume_snapshot/meta.yaml
Labels: FIX, Minor update

#7201 fix(windows instances): add instructions to configure the backup transfer of a windows instance
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.de-de.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-asia.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-au.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-ca.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-gb.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-ie.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-sg.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.en-us.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.es-es.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.es-us.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.fr-ca.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.fr-fr.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.it-it.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.pl-pl.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/guide.pt-pt.md
  pages/public_cloud/compute/transfer_instance_backup_from_one_datacentre_to_another/meta.yaml
Labels: Minor update

#7237 KevS-Update-EOL-redis-for-WebCloudDatabases
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.de-de.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.en-asia.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.en-au.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.en-ca.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.en-ie.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.en-sg.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.en-us.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.es-es.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.es-us.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.fr-fr.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.it-it.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/clouddb-eos-eol/guide.pt-pt.md
Labels: Update request, Minor update

#7243 SSH Introduction - PL image link fix
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.pl-pl.md
Labels: FIX

#7250 Add new KB Import keys CP
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/images/importkey1.png
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/images/importkey2.png
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/images/importkey3.png
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/meta.yaml
  pages/index.md
Labels: Guide creation, Translations

#7247 Translations for moving an additional IP
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/meta.yaml
Labels: Do not merge yet, Translations ONLY

#7252 VMware - VCD migration use case
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
  test.txt
Labels: Minor update

#7254 add omitted images
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/images/manageIPs2024.png
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/images/move_ip.png
Labels: FIX

#7255 Deleting test file
  test.txt
Labels: FIX

#7260 KevS-SK1827-KFT0023539-Update-connecting-wcdb-and-overquota-guides
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.fr-fr.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#7261 KevS-SK1826-KFT0023816-Update-Enabling-included-emails-for-WebHosting
  pages/web_cloud/web_hosting/activate-email-hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#7259 SK-1802-Email-Exchange-Private-Backup_Veeam
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup01-2.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup01.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup02.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup03.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup04.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup05.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup05bis.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup06.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup07.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup08.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup09.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup10.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup11.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup12.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup13.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup14.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup15.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup16.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup17.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup18.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup19.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup20.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup21.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup22.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup23.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup24.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup25.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup26.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup27.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup28.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup29.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/images/exchange_veeam_backup30.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/meta.yaml
Labels: Guide creation

#7267 VPS/DS -Getting started - Adding link to SSK key importation guide
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/meta.yaml
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.pt-pt.md
Labels: Minor update

#7274 Nutanix / HYCU - Links fix
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.de-de.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-gb.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-ie.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.es-es.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.es-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.pl-pl.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.pt-pt.md
Labels: FIX

#7256 KevS-SK1819-KFT0023464-Update-Enable-100m-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/activate_start10m/guide.de-de.md
  pages/web_cloud/web_hosting/activate_start10m/guide.en-gb.md
  pages/web_cloud/web_hosting/activate_start10m/guide.en-ie.md
  pages/web_cloud/web_hosting/activate_start10m/guide.es-es.md
  pages/web_cloud/web_hosting/activate_start10m/guide.fr-fr.md
  pages/web_cloud/web_hosting/activate_start10m/guide.it-it.md
  pages/web_cloud/web_hosting/activate_start10m/guide.pl-pl.md
  pages/web_cloud/web_hosting/activate_start10m/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue

#7275 Public Cloud LB - Resizing via Horizon - Adding XL size
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/update-load-balancer-size/images/sizeLoadBalancer.png
Labels: Minor update

#7265 Public Cloud - Compute - Add Delete token command to ALL files - KFT0006825
  pages/public_cloud/compute/managing_tokens/guide.de-de.md
  pages/public_cloud/compute/managing_tokens/guide.en-asia.md
  pages/public_cloud/compute/managing_tokens/guide.en-au.md
  pages/public_cloud/compute/managing_tokens/guide.en-ca.md
  pages/public_cloud/compute/managing_tokens/guide.en-gb.md
  pages/public_cloud/compute/managing_tokens/guide.en-ie.md
  pages/public_cloud/compute/managing_tokens/guide.en-sg.md
  pages/public_cloud/compute/managing_tokens/guide.en-us.md
  pages/public_cloud/compute/managing_tokens/guide.es-es.md
  pages/public_cloud/compute/managing_tokens/guide.es-us.md
  pages/public_cloud/compute/managing_tokens/guide.fr-ca.md
  pages/public_cloud/compute/managing_tokens/guide.fr-fr.md
  pages/public_cloud/compute/managing_tokens/guide.it-it.md
  pages/public_cloud/compute/managing_tokens/guide.pl-pl.md
  pages/public_cloud/compute/managing_tokens/guide.pt-pt.md
  pages/public_cloud/compute/managing_tokens/meta.yaml
Labels: Translations

#7276 removing ESXI guide for HG and Scale servers
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/esxi-end-of-support/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/images/schema_esxi_A01_2022.png
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/images/schema_esxi_A02_2022.png
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/images/schema_esxi_A03_2022.png
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/images/schema_esxi_A04_2022.png
  pages/bare_metal_cloud/dedicated_servers/esxi-network-HG-Scale/meta.yaml
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pt-pt.md
  pages/index.md
Labels: Guides removal

#7280 Veeam Cloud Connect - Migration to Object Storage - guide creation
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam-cloud-connect-migration/meta.yaml
  pages/index.md
Labels: Guide creation, Priority: Urgent

#7244 dbaas: add new guide about prometheus endpoints for database services
  links/public-cloud/databases
  pages/index.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.en-us.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/databases_17_metrics_via_prometheus/meta.yaml
Labels: Guide creation

#7279 SK-1788-TRANSLATION-WEB-Emails-MXplan-Outlook-mobile-Android
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/meta.yaml
Labels: Translations ONLY

#7290 [FIX] several fixies
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.it-it.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.es-es.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.es-es.md
Labels: FIX

#7257 [Dedicated Servers] VMAC availability update
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/meta.yaml
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/meta.yaml
Labels: Minor update

#7284 SK-1802-TRANSLATION-Exchange-Private-Veeam-EN
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_veeam_backup/guide.pt-pt.md
Labels: Translations ONLY

#7295 resize images for better rendering
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/accessing-a-notebook-using-UI-3.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/accessing-a-notebook-using-UI-4.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/creating-a-notebook-using-UI-01.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/creating-a-notebook-using-UI-02.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/creating-a-notebook-using-UI-03.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/creating-a-notebook-using-UI-04.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/creating-a-notebook-using-UI-05.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/notebook-authentication-creds.png
  pages/public_cloud/ai_machine_learning/notebook_guide_introduction_definition/images/notebook-authentication-token.png
Labels: Minor update

#7301 DNS DynHost - PL translation fix
  pages/web_cloud/domains/dns_dynhost/guide.pl-pl.md
Labels: FIX

#7304 KevS-SK1832-KFT0023807-Update-Automatic-emails-for-WebHosting
  pages/web_cloud/web_hosting/mail_function_script_records/guide.de-de.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-gb.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.fr-ca.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#7302 VMware Cloud Director - Updating migration dates
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: Minor update

#7303 KevS-SK1827-KFT0023539-Update-connecting-wcdb-and-overquota-guides-TRANSLATIONS
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.de-de.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.en-asia.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.en-au.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.en-ca.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.en-ie.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.en-sg.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.en-us.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.es-es.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.es-us.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.it-it.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/connecting-to-database-on-database-server/guide.pt-pt.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.de-de.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-au.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-us.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.es-es.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.es-us.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.it-it.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue, Minor update

#7309 KFT0023215 - Minor update - Enabling and configuring the Edge Network Firewall
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/meta.yaml
Labels: Translations

#7308 [Image update] Users - Manage AI users and roles
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.de-de.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.en-au.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.en-us.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.es-es.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.es-us.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.it-it.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/gi_01_manage_users/images/05_edit_user_roles.png
Labels: Minor update, Priority: Low

#7305 KevS-SK1832-KFT0023807-Update-Automatic-emails-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/mail_function_script_records/guide.de-de.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-asia.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-au.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-ca.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-gb.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-ie.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-sg.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-us.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.es-es.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.es-us.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.fr-ca.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.it-it.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.pl-pl.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue, Minor update

#7312 KevS-SK1864-KFT000024186-Update-Database-Overquota-for-WebHosting
  pages/assets/screens/control_panel/product-selection/web-cloud/web-cloud-databases/general-information/refresh-your-database-quota.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/databases/recalculate-quota-validation.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/databases.png
  pages/web_cloud/web_hosting/sql_overquota_database/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.fr-fr.md
Labels: Update request, KFT / Issue

#7313 KevS-SK1864-KFT0024186-Update-Database-Overquota-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/sql_overquota_database/guide.de-de.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-au.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-us.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.es-es.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.es-us.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.it-it.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue

#7323 Object Storage - Compliancy - Fixing the excerpt
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.pt-pt.md
Labels: FIX

#7333 Update of the Rclone & Object Storage guide in EN-GB and FR
  pages/storage_and_backup/object_storage/s3_rclone/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_rclone/guide.pt-pt.md
Labels: Minor update, Priority: Low

#7332 VCD Concept - Updating Networking table
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.pt-pt.md
Labels: Minor update, Priority: Low

#7324 SK-1788-WEB-Emails-EmailPro-outlook-android
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-add-step01.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-add-step02.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-add-step021.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-add-step03-imap-emailpro.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-add-step03-pop-emailpro.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-add01.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-add02.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-delete-account-01.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/images/outlook-app-android-delete-account-02.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/emailpro_outlook_app_android/meta.yaml
Labels: Guide creation

#7328 Minor Fix on Guides & Iptables configuration - KFT0023583
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/ssh_introduction/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/meta.yaml
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-asia.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-au.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-gb.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-ie.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-sg.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-us.md
Labels: Translations

#7233 Feat(Load Balancer): create documentation for using an external certificate with load balancer
  pages/index.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.fr- ca.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/l7policycreation.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/listenerhttpcreation1.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/listenerhttpcreation2.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/listenerhttpscreation1.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/listenerhttpscreation2.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/listenerhttpscreation3.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/listenerhttpscreation4.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/listenerpolicieslist.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/images/loadbalancerlistenerslist.png
  pages/public_cloud/public_cloud_network_services/tutorials-02-secure-lb-external-certificat/meta.yaml
Labels: Guide creation

#7350 fix(db): update UI explanations and images
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.en-us.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/images/cluster-overview.png
  pages/public_cloud/public_cloud_databases/databases_11_resize_your_cluster_storage/images/edit-additional-storage.png
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.en-us.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/images/cluster_overview.png
  pages/public_cloud/public_cloud_databases/databases_13_update_your_cluster_flavor/images/flavor_change_view.png
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.en-us.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/images/cluster_overview.png
  pages/public_cloud/public_cloud_databases/databases_14_upgrade_your_cluster_plan/images/plan_change_view.png
Labels: FIX
