Repository ovh/docs, pull requests merged in 2024-11, with the labels that each got.

#7114 KevS-SK1778-Update-DNSSEC-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/dns_dnssec/guide.de-de.md
  pages/web_cloud/domains/dns_dnssec/guide.en-asia.md
  pages/web_cloud/domains/dns_dnssec/guide.en-au.md
  pages/web_cloud/domains/dns_dnssec/guide.en-ca.md
  pages/web_cloud/domains/dns_dnssec/guide.en-gb.md
  pages/web_cloud/domains/dns_dnssec/guide.en-ie.md
  pages/web_cloud/domains/dns_dnssec/guide.en-sg.md
  pages/web_cloud/domains/dns_dnssec/guide.en-us.md
  pages/web_cloud/domains/dns_dnssec/guide.es-es.md
  pages/web_cloud/domains/dns_dnssec/guide.es-us.md
  pages/web_cloud/domains/dns_dnssec/guide.it-it.md
  pages/web_cloud/domains/dns_dnssec/guide.pl-pl.md
  pages/web_cloud/domains/dns_dnssec/guide.pt-pt.md
  pages/web_cloud/domains/dns_dnssec/meta.yaml
Labels: Translations ONLY

#7111 FR OverTheBox rewrite and merge LAN configurations related guides
  pages/index.md
  pages/web_cloud/internet/overthebox/advanced_ajouter_un_serveur_active_directory_dans_les_options_dhcp/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/advanced_ajouter_un_serveur_active_directory_dans_les_options_dhcp/images/4434.png
  pages/web_cloud/internet/overthebox/advanced_ajouter_un_serveur_active_directory_dans_les_options_dhcp/images/4435.png
  pages/web_cloud/internet/overthebox/advanced_ajouter_un_serveur_active_directory_dans_les_options_dhcp/meta.yaml
  pages/web_cloud/internet/overthebox/advanced_configurer_votre_propre_serveur_dns/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/advanced_configurer_votre_propre_serveur_dns/images/4416.png
  pages/web_cloud/internet/overthebox/advanced_configurer_votre_propre_serveur_dns/images/4417.png
  pages/web_cloud/internet/overthebox/advanced_configurer_votre_propre_serveur_dns/meta.yaml
  pages/web_cloud/internet/overthebox/advanced_dmz_couplage_overthebox_avec_un_autre_routeur/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/4375.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-1-edit-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-10-OptionsDHCP-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-2-generalSettings-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-3-DHCPSettings-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-4-DisableDHCP-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-5-DisableDynamicDHCP-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-6-AddDHCPLease-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-7-ConfigureDHCPLease-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-8-ConfigureDNS-2024.png
  pages/web_cloud/internet/overthebox/middle_configurer_votre_lan/images/step1-lan-9-ConfigureDomain-2024.png
  pages/web_cloud/internet/overthebox/middle_desactiver_le_serveur_dhcp_doverthebox/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/middle_desactiver_le_serveur_dhcp_doverthebox/images/4405.png
  pages/web_cloud/internet/overthebox/middle_desactiver_le_serveur_dhcp_doverthebox/images/4406.png
  pages/web_cloud/internet/overthebox/middle_desactiver_le_serveur_dhcp_doverthebox/meta.yaml
  pages/web_cloud/internet/overthebox/start-with-overthebox/guide.fr-fr.md
Labels: Guides removal

#7121 Dedicated Servers - Game Firewall - DE header fix
  pages/bare_metal_cloud/dedicated_servers/firewall_game_ddos/guide.de-de.md
Labels: FIX

#7100 FB - migrate web site from Mutu to VPS
  pages/index.md
  pages/web_cloud/web_hosting/migrate_website_to_vps/guide.fr-fr.md
  pages/web_cloud/web_hosting/migrate_website_to_vps/meta.yaml
Labels: Guide creation

#7086 Update - Managed VMware vsphere guide login manager
  pages/assets/screens/control_panel/product-selection/hosted-private-cloud/vmware/vmware_users.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_interface_connexion/images/managed_vsphere_all.png
Labels: Update request, Priority: Low

#7105 Update - Hpc VMware connect iso
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_connect_an_iso_image_to_a_vm/guide.pt-pt.md
Labels: Update request, Priority: Low

#7117 KevS-SK1755-Update-manage-SSL-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/ssl_ev/guide.de-de.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-asia.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-au.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-ca.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-gb.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-ie.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-sg.md
  pages/web_cloud/web_hosting/ssl_ev/guide.en-us.md
  pages/web_cloud/web_hosting/ssl_ev/guide.es-es.md
  pages/web_cloud/web_hosting/ssl_ev/guide.es-us.md
  pages/web_cloud/web_hosting/ssl_ev/guide.it-it.md
  pages/web_cloud/web_hosting/ssl_ev/guide.pl-pl.md
  pages/web_cloud/web_hosting/ssl_ev/guide.pt-pt.md
  pages/web_cloud/web_hosting/ssl_ev/meta.yaml
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/guide.pt-pt.md
  pages/web_cloud/web_hosting/ssl_on_webhosting/meta.yaml
Labels: Translations ONLY

#7141 FR ISP Update Zyxel web ui screenshot
  pages/web_cloud/internet/internet_access/ftth_fix_access/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/ftth_fix_access/images/acces-internet-box-ovh-test-internet-step1.png
  pages/web_cloud/internet/internet_access/ftth_fix_access/images/acces-internet-box-ovh-test-internet-step2.png
  pages/web_cloud/internet/internet_access/ftth_fix_access/images/acces-internet-box-ovh-test-internet-step3.png
Labels: Minor update

#7143 Fixes on various pages
  pages/account_and_service_management/account_information/secure-ovhcloud-account-with-2fa/guide.fr-ca.md
  pages/account_and_service_management/account_information/secure-ovhcloud-account-with-2fa/guide.fr-fr.md
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/guide.de-de.md
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/guide.es-es.md
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/guide.es-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/guide.it-it.md
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/guide.pl-pl.md
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/guide.pt-pt.md
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/meta.yaml
  pages/web_cloud/internet/overthebox/config_qos/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/config_qos/images/step2-tc-1-selectInterface-2024.png
Labels: FIX

#7147 Fixing broken lists and links on various pages
  pages/account_and_service_management/managing_billing_payments_and_services/managing_ovh_orders/guide.pt-pt.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.en-asia.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.en-au.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.en-ca.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.en-gb.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.en-ie.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.en-sg.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.en-us.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.es-es.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.es-us.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.fr-ca.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.fr-fr.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.it-it.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.pl-pl.md
  pages/public_cloud/data_analytics/data_processing/42_TUTORIAL_notebook-data-cleaning/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_mx/guide.de-de.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-au.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_mx/guide.en-us.md
  pages/web_cloud/domains/dns_zone_mx/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_mx/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_mx/guide.pt-pt.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.es-es.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.es-us.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.it-it.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_recovering_deleted_db_backup/guide.pt-pt.md
Labels: FIX

#7152 MInor fixes following CSM report
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.pl-pl.md
Labels: Do not merge yet

#6748 FB - autorenew domain name
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.fr-fr.md
  pages/index.md
  pages/web_cloud/domains/autorenew_domain_name/guide.fr-fr.md
  pages/web_cloud/domains/autorenew_domain_name/meta.yaml
Labels: Update request

#7156 KevS-Fix-SSL-DV
  pages/web_cloud/web_hosting/ssl_dv/guide.es-es.md
  pages/web_cloud/web_hosting/ssl_dv/guide.es-us.md
Labels: FIX

#6772 Object Storage - Local Zones specifications - SK-1652
  pages/index.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_limitations/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_local_zones_limitations/meta.yaml
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.pt-pt.md
Labels: Guide creation, Priority: Dependency

#7145 Translations for SK1782 - Compute- Suspend/Shelve an instance - Clarifications
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.de-de.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.es-es.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.es-us.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.it-it.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.pt-pt.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/meta.yaml
Labels: Translations ONLY, Quality Check

#7161 Kimsufi - Additional IP availability update - KFT0022747
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/meta.yaml
Labels: KFT / Issue, Minor update

#7162 Public Cloud - Secure LB with Let-s Encrypt - FR Certbot link fix
  pages/public_cloud/public_cloud_network_services/tutorials-01-secure-lb-letsencrypt/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/tutorials-01-secure-lb-letsencrypt/guide.fr-fr.md
Labels: FIX, KFT / Issue

#7163 VoIP - Yellow Pages publication - Minor wording update
  pages/web_cloud/phone_and_fax/voip/publication_annuaire/guide.fr-fr.md
Labels: KFT / Issue, Minor update

#7164 SMS - Adding information about URL sending / accepted senders
  pages/web_cloud/messaging/sms/envoyer_des_sms_depuis_mon_espace_client/guide.fr-fr.md
Labels: KFT / Issue

#7137 SK-1764-WEB-Email-Zimbra-mobile-app
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/images/zimbra_app_burger_menu01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/images/zimbra_app_burger_menu02.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/images/zimbra_app_connect01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/images/zimbra_app_connect02.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/images/zimbra_app_inbox01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/images/zimbra_app_logout01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/images/zimbra_app_settings01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/mail_app_zimbra_for_android_ios/meta.yaml
Labels: Guide creation

#7177 VMware DRS - Fix FR title and a few typos
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_drs_distributed_ressource_scheduler_new/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_drs_distributed_ressource_scheduler_new/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_drs_distributed_ressource_scheduler_new/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_drs_distributed_ressource_scheduler_new/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_drs_distributed_ressource_scheduler_new/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_drs_distributed_ressource_scheduler_new/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_drs_distributed_ressource_scheduler_new/guide.pt-pt.md
Labels: FIX, Priority: Low

#7176 Mb ai endpoints getting started
  pages/index.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/meta.yaml
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/meta.yaml
Labels: Guide creation, Priority: Urgent

#7166 Guide update - PCI - Test your disk speed - KFT0022677
  pages/public_cloud/compute/test_disk_speed/guide.en-asia.md
  pages/public_cloud/compute/test_disk_speed/guide.en-au.md
  pages/public_cloud/compute/test_disk_speed/guide.en-ca.md
  pages/public_cloud/compute/test_disk_speed/guide.en-gb.md
  pages/public_cloud/compute/test_disk_speed/guide.en-ie.md
  pages/public_cloud/compute/test_disk_speed/guide.en-sg.md
  pages/public_cloud/compute/test_disk_speed/guide.en-us.md
  pages/public_cloud/compute/test_disk_speed/guide.fr-ca.md
  pages/public_cloud/compute/test_disk_speed/guide.fr-fr.md
Labels: Do not merge yet, KFT / Issue

#7184 cookbook_install_ovhcloud_backint_agent: fix Markdown
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/cookbook_install_ovhcloud_backint_agent/guide.pt-pt.md
Labels: FIX, Minor update

#7185 WEB-Email-Zimbra-FAQ-evolution_update-151124-TRANSLATE
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/meta.yaml
Labels: Translations ONLY

#7191 Upd PuTTY for all univ
  pages/assets/screens/other/web-tools/putty/pageant1.png
  pages/assets/screens/other/web-tools/putty/pageant2.png
  pages/assets/screens/other/web-tools/putty/pageant3.png
  pages/assets/screens/other/web-tools/putty/pterminal.png
  pages/assets/screens/other/web-tools/putty/putty1.png
  pages/assets/screens/other/web-tools/putty/putty2.png
  pages/assets/screens/other/web-tools/putty/putty3.png
  pages/assets/screens/other/web-tools/putty/puttygen.gif
  pages/assets/screens/other/web-tools/putty/puttygen1.png
  pages/assets/screens/other/web-tools/putty/puttygen2.png
  pages/assets/screens/other/web-tools/putty/puttygen3.png
  pages/assets/screens/other/web-tools/putty/puttygen4.png
  pages/assets/screens/other/web-tools/putty/puttygen5.png
  pages/assets/screens/other/web-tools/putty/puttygen6.png
  pages/assets/screens/other/web-tools/putty/puttygen7.png
  pages/assets/screens/other/web-tools/putty/sessions1.png
  pages/assets/screens/other/web-tools/putty/sessions2.png
  pages/assets/screens/other/web-tools/putty/sessions3.png
  pages/assets/screens/other/web-tools/putty/sessions4.png
  pages/assets/screens/other/web-tools/putty/sessions5.png
  pages/assets/screens/other/web-tools/putty/systray.png
  pages/index.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.de-de.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-asia.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-au.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-ca.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-gb.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-ie.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-sg.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-us.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.es-es.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.es-us.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.it-it.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.pl-pl.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.pt-pt.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/meta.yaml
Labels: Translations

#7187 Translations and meta file update for Test your disk speed - PCI
  pages/public_cloud/compute/test_disk_speed/guide.de-de.md
  pages/public_cloud/compute/test_disk_speed/guide.es-es.md
  pages/public_cloud/compute/test_disk_speed/guide.es-us.md
  pages/public_cloud/compute/test_disk_speed/guide.it-it.md
  pages/public_cloud/compute/test_disk_speed/guide.pl-pl.md
  pages/public_cloud/compute/test_disk_speed/guide.pt-pt.md
  pages/public_cloud/compute/test_disk_speed/meta.yaml
Labels: Translations ONLY

#7195 Links and index fixes
  pages/bare_metal_cloud/dedicated_servers/changing_root_password_linux_ds/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/changing_root_password_linux_ds/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/installing_lamp_debian9_ubuntu18/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/restore-bdd-rescue/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/restore-bdd-rescue/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/increase_additional_disk/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/increase_additional_disk/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/rescue/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/rescue/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/meta.yaml
Labels: FIX

#7125 KevS-SK1780-Update-Retriving-logs-for-WebCloudDatabases
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/logs-data-platform/data-stream/add-data-stream.png
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.de-de.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-asia.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-au.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-ca.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-ie.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-sg.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-us.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.es-es.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.es-us.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.fr-fr.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.it-it.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.pt-pt.md
Labels: Update request, Translations

#7196 Important migration important xDSL to FTTH
  pages/web_cloud/internet/internet_access/comment_changer_mon_offre_xdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_demenager_mon_acces_xdsl/guide.fr-fr.md
Labels: Priority: Low

#7200 FR OverTheBox update v0.8 channel name
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
Labels: Minor update

#7146 3-AZ deployment mode arrival on S3 Object Storage
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_location/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_location/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_location/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_location/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_regions_comparison/guide.pt-pt.md
Labels: Guide creation

#7203 KevS-SK1780-Update-Retrieving-logs-for-WebCloudDatabases-screen
  pages/assets/screens/control_panel/product-selection/web-cloud/web-cloud-databases/logs/data-stream.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-cloud-databases/logs/tab-subscribe.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-cloud-databases/logs/tab.png
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.de-de.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-asia.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-au.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-ca.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-ie.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-sg.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.en-us.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.es-es.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.es-us.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.fr-fr.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.it-it.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/retrieve-logs/guide.pt-pt.md
Labels: FIX

#7204 Add new image - bucket creation FR-EN
  pages/storage_and_backup/object_storage/s3_create_bucket/images/object_storage-bucke_creation_step2.png
Labels: Minor update

#7206 Fix( 'configuring IPV6' documentation ): update the mistake of netplan command
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/configuration-02-how-to-configure-ipv6/guide.pt-pt.md
Labels: FIX, Minor update

#7208 fix(L3 services SNAT documentation): update the old version of the command
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/configuration-01-snat-configuration/guide.pt-pt.md
Labels: FIX, Minor update

#7209 Add proper key auth section at SD reinstall
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/choosedisk.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/monitoring-your-server.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/monitoring-your-server2.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/rebooting-your-server.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/reinstalling-your-server-01.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/reinstalling-your-server-02.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/reinstalling-your-server-03.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/reinstalling-your-server-04.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/reinstalling-your-server-05.png
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/dedicated-servers/general-information/sshkeyds.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/images/monitoring-your-server-alt.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/images/monitoring-your-service.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server-eco/images/reinstalling-your-server-05.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/monitoring-your-server-alt.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/monitoring-your-server.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/monitoring-your-server2.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/monitoring-your-service.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/rebooting-your-server.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/reinstalling-your-server-01.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/reinstalling-your-server-02.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/reinstalling-your-server-03.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/reinstalling-your-server-04.png
  pages/bare_metal_cloud/dedicated_servers/getting-started-with-dedicated-server/images/reinstalling-your-server-05.png
Labels: Minor update, Translations

#7207 SK-1788-WEB-Emails-mxplan-outlook-android
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add-step01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add-step02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add-step021.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add-step03-imap-ca.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add-step03-imap-eu.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add-step03-pop-ca.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add-step03-pop-eu.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-add02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/images/outlook-app-android-delete-account-01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/meta.yaml
Labels: Guide creation

#7215 FR/EN Add Hold an automatic EFS snapshot
  pages/index.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.en-asia.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.en-au.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.en-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.en-gb.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.en-ie.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.en-sg.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.en-us.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.fr-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.fr-fr.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/images/hold_snapshot_step_1.png
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/images/hold_snapshot_step_2.png
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/meta.yaml
Labels: Guide creation

#7226 KevS-SK1804-My-Services-REVAMP-Guides-fix
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.de-de.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-asia.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-au.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-gb.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-ie.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-sg.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.es-es.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.es-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.it-it.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.pl-pl.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.pt-pt.md
Labels: FIX

#7223 FR OverTheBox Update Reset/Restore guide
  pages/index.md
  pages/web_cloud/internet/overthebox/config_reset/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/config_reset/images/luci-reset-2024.png
  pages/web_cloud/internet/overthebox/config_reset/images/luci-restore-1-2024.png
  pages/web_cloud/internet/overthebox/config_reset/images/luci-restore-2-2024.png
  pages/web_cloud/internet/overthebox/config_reset/images/luci-save-2024.png
  pages/web_cloud/internet/overthebox/config_reset/images/reset-method1_OTBv1.png
  pages/web_cloud/internet/overthebox/config_reset/images/reset-method1_OTBv2a.jpg
  pages/web_cloud/internet/overthebox/config_reset/images/reset-method1_OTBv2c.jpg
  pages/web_cloud/internet/overthebox/config_reset/images/reset-method2.png
  pages/web_cloud/internet/overthebox/middle_exporter_et_importer_une_configuration/guide.fr-fr.md
  pages/web_cloud/internet/overthebox/middle_exporter_et_importer_une_configuration/images/4407.png
  pages/web_cloud/internet/overthebox/middle_exporter_et_importer_une_configuration/images/4408.png
  pages/web_cloud/internet/overthebox/middle_exporter_et_importer_une_configuration/meta.yaml
Labels: Guides removal

#7229 Add translations EFS hold snap
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.de-de.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.es-es.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.es-us.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.it-it.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.pl-pl.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/guide.pt-pt.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_hold_automatic_snapshot/meta.yaml
Labels: Translations ONLY
