Repository ovh/docs, pull requests merged in 2024-06, with the labels that each got.

#6395 Raci data processing
  pages/index.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.de-de.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.en-asia.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.en-au.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.en-ca.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.en-gb.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.en-ie.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.en-sg.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.en-us.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.es-es.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.es-us.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.fr-ca.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.fr-fr.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.it-it.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.pl-pl.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/guide.pt-pt.md
  pages/public_cloud/data_analytics/data_processing/responsibility_model/meta.yaml
Labels: Guide creation

#6399 KevS-SK1568-KFT0017356-Update-Shared-SQL-EOS-EOL-for-WebHosting
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-fr.md
Labels: KFT, Minor update

#6398 KevS-SK1552-Update-Glue-records-for-DomainDNS
  pages/web_cloud/domains/glue_registry/guide.fr-ca.md
  pages/web_cloud/domains/glue_registry/guide.fr-fr.md
Labels: Minor update

#6406 S3 Object Storage - S3 location - target mapping date update
  pages/storage_and_backup/object_storage/s3_location/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_location/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_location/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_location/guide.pt-pt.md
Labels: Minor update

#6404 EN - add guide for upcoming OpenSearch 2 upgrade - observability/LDP
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/guide.pt-pt.md
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/images/grafana-1.png
  pages/manage_and_operate/observability/logs_data_platform/upgrade_upgrade_to_opensearch_2/meta.yaml
Labels: Guide creation, Quality Check

#6283 first version of KMS quick start guide and architecture guide
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/manage_and_operate/kms/architecture-overview/guide.de-de.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-asia.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-au.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-ca.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-gb.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-ie.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-sg.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-us.md
  pages/manage_and_operate/kms/architecture-overview/guide.es-es.md
  pages/manage_and_operate/kms/architecture-overview/guide.es-us.md
  pages/manage_and_operate/kms/architecture-overview/guide.fr-ca.md
  pages/manage_and_operate/kms/architecture-overview/guide.fr-fr.md
  pages/manage_and_operate/kms/architecture-overview/guide.it-it.md
  pages/manage_and_operate/kms/architecture-overview/guide.pl-pl.md
  pages/manage_and_operate/kms/architecture-overview/guide.pt-pt.md
  pages/manage_and_operate/kms/architecture-overview/images/KMS_Overview.png
  pages/manage_and_operate/kms/architecture-overview/meta.yaml
  pages/manage_and_operate/kms/quick-start/guide.de-de.md
  pages/manage_and_operate/kms/quick-start/guide.en-asia.md
  pages/manage_and_operate/kms/quick-start/guide.en-au.md
  pages/manage_and_operate/kms/quick-start/guide.en-ca.md
  pages/manage_and_operate/kms/quick-start/guide.en-gb.md
  pages/manage_and_operate/kms/quick-start/guide.en-ie.md
  pages/manage_and_operate/kms/quick-start/guide.en-sg.md
  pages/manage_and_operate/kms/quick-start/guide.en-us.md
  pages/manage_and_operate/kms/quick-start/guide.es-es.md
  pages/manage_and_operate/kms/quick-start/guide.es-us.md
  pages/manage_and_operate/kms/quick-start/guide.fr-ca.md
  pages/manage_and_operate/kms/quick-start/guide.fr-fr.md
  pages/manage_and_operate/kms/quick-start/guide.it-it.md
  pages/manage_and_operate/kms/quick-start/guide.pl-pl.md
  pages/manage_and_operate/kms/quick-start/guide.pt-pt.md
  pages/manage_and_operate/kms/quick-start/images/Datakey_decrypt.png
  pages/manage_and_operate/kms/quick-start/images/Datakey_encrypt.png
  pages/manage_and_operate/kms/quick-start/images/access_to_the_KMS_menu_01.png
  pages/manage_and_operate/kms/quick-start/images/access_to_the_KMS_menu_02.png
  pages/manage_and_operate/kms/quick-start/images/order_kms_01.png
  pages/manage_and_operate/kms/quick-start/images/order_kms_02.png
  pages/manage_and_operate/kms/quick-start/images/order_kms_03.png
  pages/manage_and_operate/kms/quick-start/images/swagger.png
  pages/manage_and_operate/kms/quick-start/meta.yaml
Labels: Do not merge yet

#6361 WEB-Microsoft-ofice365-csp1-SK1379
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.pt-pt.md
Labels: KFT, Translations

#6411 KevS-SK1568-Update-Shared-SQL-EOS-EOL-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/sql_eos_eol/guide.de-de.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-au.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.en-us.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.es-es.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.es-us.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.fr-fr.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.it-it.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_eos_eol/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6414 fix: Update the screenshots to show the new API console
  pages/manage_and_operate/api/first-steps/guide.de-de.md
  pages/manage_and_operate/api/first-steps/guide.en-asia.md
  pages/manage_and_operate/api/first-steps/guide.en-au.md
  pages/manage_and_operate/api/first-steps/guide.en-ca.md
  pages/manage_and_operate/api/first-steps/guide.en-gb.md
  pages/manage_and_operate/api/first-steps/guide.en-ie.md
  pages/manage_and_operate/api/first-steps/guide.en-sg.md
  pages/manage_and_operate/api/first-steps/guide.en-us.md
  pages/manage_and_operate/api/first-steps/guide.es-es.md
  pages/manage_and_operate/api/first-steps/guide.es-us.md
  pages/manage_and_operate/api/first-steps/guide.fr-ca.md
  pages/manage_and_operate/api/first-steps/guide.fr-fr.md
  pages/manage_and_operate/api/first-steps/guide.it-it.md
  pages/manage_and_operate/api/first-steps/guide.pl-pl.md
  pages/manage_and_operate/api/first-steps/guide.pt-pt.md
  pages/manage_and_operate/api/first-steps/images/api-displayed.png
  pages/manage_and_operate/api/first-steps/images/api-list-ca.png
  pages/manage_and_operate/api/first-steps/images/api-list.png
  pages/manage_and_operate/api/first-steps/images/login-ca.png
  pages/manage_and_operate/api/first-steps/images/login.png
  pages/manage_and_operate/api/first-steps/images/parameters.png
  pages/manage_and_operate/api/first-steps/images/result.png
Labels: Minor update

#6424 FR update overthebox version matrix with v1.0.0
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
Labels: Minor update

#6423 Hosted Private Cloud - VCD : Update get concet guide v2 vrack support in roadmap
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-get-concepts/guide.pt-pt.md
Labels: Minor update

#6358 WEB-Email-MXplan-auto-replies-SK1378
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_auto_responses/guide.pt-pt.md
Labels: KFT, Translations

#6416 EN: Update guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/using_ipmi_on_dedicated_servers/guide.en-gb.md
Labels: Minor update

#6427 [PROD] - Testing details collapsible markdown extension
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.de-de.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.en-au.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.en-us.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.es-es.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.es-us.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.it-it.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/ecosystem_02_lettria_models/guide.pt-pt.md
Labels: Minor update

#6433 mks: update csi-plugin version to 1.29.0
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pt-pt.md
Labels: Minor update

#6431 Order options for Enterprise File Storage on Control Panel guide
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.de-de.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-asia.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-au.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-gb.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-ie.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-sg.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.en-us.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.es-es.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.es-us.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.fr-ca.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.fr-fr.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.it-it.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.pl-pl.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.pt-pt.md
Labels: KFT

#6386 WEB-Email-all_offers-update_3_guides-SK1446
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pt-pt.md
Labels: Translations

#6432 FB - How to connect an OVH domain to Webflow and GoDaddy webhosting
  pages/index.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.en-asia.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.en-au.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.en-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.en-gb.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.en-ie.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.en-sg.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.en-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.fr-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/guide.fr-fr.md
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/images/filter-a.png
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/images/filter-aaaa.png
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/images/filter-cname.png
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/images/filter-txt.png
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/images/tab.png
  pages/web_cloud/domains/how_to_connect_domain_to_godaddy/meta.yaml
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.en-asia.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.en-au.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.en-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.en-gb.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.en-ie.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.en-sg.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.en-us.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.fr-ca.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/guide.fr-fr.md
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/images/field-cname.png
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/images/field-txt.png
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/images/filter-a.png
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/images/filter-aaaa.png
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/images/filter-cname.png
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/images/filter-txt.png
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/images/tab.png
  pages/web_cloud/domains/how_to_connect_domain_to_webflow/meta.yaml
Labels: Guide creation

#6436 SK-1580 - Dedicated Servers - IP block in vRack - Configuration fix
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.pt-pt.md
Labels: FIX

#6422 SK-1473-WEB-Email-alloffers-manage_redirections_alias
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/images/email-del-legacy-redirect01.png
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/images/owa-redirect-del-01.png
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/images/owa-redirect-del-02.png
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/images/schema-redirect00.png
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/images/schema-redirect01.png
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/images/schema-redirect02.png
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/images/schema-redirect03.png
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_office/office_csp1/guide.pl-pl.md
Labels: Translations

#6437 Correction on misstranlation in FR
  pages/account_and_service_management/account_information/iam-policies-api/guide.fr-ca.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.fr-fr.md
Labels: FIX

#6444 SK-1487-WEB-Emails-all_offers-manage_password
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pt-pt.md
Labels: Minor update

#6451 Minor fixes on various pages
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_cancel_services/guide.pl-pl.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/firewall_game_ddos/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.pl-pl.md
  pages/web_cloud/internet/internet_access/configuration_du_modem_a_partir_de_votre_espace_client/guide.fr-fr.md
Labels: FIX

#6455 Fixes on various pages - Web & Telecom
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/feature_delegation/guide.en-asiamd
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/feature_delegation/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/feature_delegation/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_delegation/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_delegation/guide.it-it.md
  pages/web_cloud/phone_and_fax/voip/modifier-musiques-sonneries-ligne/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/voip/modifier-musiques-sonneries-ligne/images/gestion-musiques.png
Labels: FIX

#6458 Dedicated Servers - Translations for Network Bridge guide update
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pt-pt.md
Labels: Translations ONLY

#6463 EN Create Persistent Volume with Cloud Disk Array for MKS
  links/public-cloud/kubernetes
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/images/add-acl.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/images/add-user-permissions.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/images/create-ceph-csi-user.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/images/create-fs.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/images/get-ceph-monitor-ip.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/images/get-user-key.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/images/list-cloud-disk-array.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/meta.yaml
Labels: Guide creation

#6468 Fixes on various pages
  pages/bare_metal_cloud/dedicated_servers/network_bridging/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-cloud-disk-array/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/feature_delegation/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pt-pt.md
Labels: FIX

#6479 DNS Zone General information - DE image fix
  pages/web_cloud/domains/dns_zone_general_information/guide.de-de.md
Labels: FIX

#6354 Hosted Private Cloud : New maintenance guide
  pages/assets/screens/manager/hosted_private_cloud/VMware/private_cloud/operation/Maintenance-filter.png
  pages/assets/screens/manager/hosted_private_cloud/VMware/private_cloud/pcc/Maintenance.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/meta.yaml
  pages/index.md
Labels: Guide creation

#6480 FB - Update CMS guide's title
  pages/web_cloud/web_hosting/cms_manual_installation_grav/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_grav/guide.fr-fr.md
  pages/web_cloud/web_hosting/cms_manual_installation_pico/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_pico/guide.fr-fr.md
  pages/web_cloud/web_hosting/cms_manual_installation_spip/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_spip/guide.fr-fr.md
  pages/web_cloud/web_hosting/cms_manual_installation_typo3/guide.fr-ca.md
  pages/web_cloud/web_hosting/cms_manual_installation_typo3/guide.fr-fr.md
Labels: Minor update

#6486 KevS-SK1590-FB-migration-website-to-ovh-for-WebHosting
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.de-de.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.en-asia.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.en-au.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.en-ca.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.en-gb.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.en-ie.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.en-sg.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.en-us.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.es-es.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.es-us.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.fr-ca.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.fr-fr.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.it-it.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.pl-pl.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.pt-pt.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/images/dashboard-a-txt-cname-ca.png
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/images/dashboard-mx-a-cname-ca.png
Labels: Translations

#6493 KevS-SK1593-Update-Objective-parts-for-DNS-guides-TRANSLATIONS
  pages/web_cloud/domains/dns_dynhost/guide.de-de.md
  pages/web_cloud/domains/dns_dynhost/guide.en-gb.md
  pages/web_cloud/domains/dns_dynhost/guide.en-ie.md
  pages/web_cloud/domains/dns_dynhost/guide.es-es.md
  pages/web_cloud/domains/dns_dynhost/guide.it-it.md
  pages/web_cloud/domains/dns_dynhost/guide.pl-pl.md
  pages/web_cloud/domains/dns_dynhost/guide.pt-pt.md
  pages/web_cloud/domains/dns_server_edit/guide.it-it.md
  pages/web_cloud/domains/dns_server_general_information/guide.it-it.md
  pages/web_cloud/domains/dns_zone_create/guide.de-de.md
  pages/web_cloud/domains/dns_zone_create/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_create/guide.en-au.md
  pages/web_cloud/domains/dns_zone_create/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_create/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_create/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_create/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_create/guide.en-us.md
  pages/web_cloud/domains/dns_zone_create/guide.es-es.md
  pages/web_cloud/domains/dns_zone_create/guide.es-us.md
  pages/web_cloud/domains/dns_zone_create/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_create/guide.it-it.md
  pages/web_cloud/domains/dns_zone_create/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_create/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_deletion/guide.de-de.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-au.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_deletion/guide.en-us.md
  pages/web_cloud/domains/dns_zone_deletion/guide.es-es.md
  pages/web_cloud/domains/dns_zone_deletion/guide.es-us.md
  pages/web_cloud/domains/dns_zone_deletion/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_deletion/guide.it-it.md
  pages/web_cloud/domains/dns_zone_deletion/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_deletion/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_edit/guide.it-it.md
  pages/web_cloud/domains/dns_zone_history/guide.de-de.md
  pages/web_cloud/domains/dns_zone_history/guide.en-asia.md
  pages/web_cloud/domains/dns_zone_history/guide.en-au.md
  pages/web_cloud/domains/dns_zone_history/guide.en-ca.md
  pages/web_cloud/domains/dns_zone_history/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_history/guide.en-ie.md
  pages/web_cloud/domains/dns_zone_history/guide.en-sg.md
  pages/web_cloud/domains/dns_zone_history/guide.en-us.md
  pages/web_cloud/domains/dns_zone_history/guide.es-es.md
  pages/web_cloud/domains/dns_zone_history/guide.es-us.md
  pages/web_cloud/domains/dns_zone_history/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_history/guide.it-it.md
  pages/web_cloud/domains/dns_zone_history/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_history/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_records/guide.it-it.md
  pages/web_cloud/domains/dns_zonemaster/guide.it-it.md
Labels: Translations ONLY, Minor update

#6353 Domains & DNS - DNS guides titles update
  pages/bare_metal_cloud/dedicated_servers/mail_sending_optimization/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/mail_sending_optimization/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_deletion/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_deletion/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_dkim/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_dkim/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_dmarc/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_dmarc/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_mx/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_mx/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_spf/guide.fr-ca.md
  pages/web_cloud/domains/dns_zone_spf/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/first_config/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/feature_filters/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/diagnostic_advanced/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/diagnostic_advanced/guide.fr-fr.md
  pages/web_cloud/web_hosting/hosting_first_steps_with_web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/hosting_first_steps_with_web_hosting/guide.fr-fr.md
Labels: Minor update

#6494 KMS - removing mention of PCI entry
  pages/manage_and_operate/kms/quick-start/guide.de-de.md
  pages/manage_and_operate/kms/quick-start/guide.en-asia.md
  pages/manage_and_operate/kms/quick-start/guide.en-au.md
  pages/manage_and_operate/kms/quick-start/guide.en-ca.md
  pages/manage_and_operate/kms/quick-start/guide.en-gb.md
  pages/manage_and_operate/kms/quick-start/guide.en-ie.md
  pages/manage_and_operate/kms/quick-start/guide.en-sg.md
  pages/manage_and_operate/kms/quick-start/guide.en-us.md
  pages/manage_and_operate/kms/quick-start/guide.es-es.md
  pages/manage_and_operate/kms/quick-start/guide.es-us.md
  pages/manage_and_operate/kms/quick-start/guide.fr-ca.md
  pages/manage_and_operate/kms/quick-start/guide.fr-fr.md
  pages/manage_and_operate/kms/quick-start/guide.it-it.md
  pages/manage_and_operate/kms/quick-start/guide.pl-pl.md
  pages/manage_and_operate/kms/quick-start/guide.pt-pt.md
Labels: Minor update

#6499 KevS-SK1595-FAQs-email-and-hosting
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-fr.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-fr.md
Labels: Minor update

#6500 KevS-SK1595-FAQs-email-and-hosting-TRANSLATIONS
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pt-pt.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-asia.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-au.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-gb.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ie.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-sg.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-es.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.it-it.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pt-pt.md
Labels: Translations ONLY, Minor update

#6491 FB - Migrate your WordPress website to OVHcloud
  pages/index.md
  pages/web_cloud/web_hosting/migrate_wordpress_website_to_ovh/guide.fr-fr.md
  pages/web_cloud/web_hosting/migrate_wordpress_website_to_ovh/meta.yaml
Labels: Guide creation

#6501 Index fix for WordPress migration
  pages/index.md
Labels: FIX

#6504 Fixes on various pages
  links/community
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_edit/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_spf/guide.en-asia.md
Labels: FIX

#6403 Hosted Private Cloud : New fr-fr guide for LDP in PCC Guide creation
  links/manage-operate/ldp
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/meta.yaml
  pages/index.md
Labels: Guide creation

#6505 Fixes on various pages
  links/manage-operate/ldp
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/intervention-support/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/tanzu_ce_install/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_ldp/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/09-advanced-tools/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/09-advanced-tools/guide.fr-fr.md
  pages/network/ovhcloud_connect/occ-setup-diagnostics/guide.fr-ca.md
  pages/network/ovhcloud_connect/occ-setup-diagnostics/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.de-de.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.en-au.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.en-us.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.es-es.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.es-us.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.it-it.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/information_01_security_overview/guide.pt-pt.md
  pages/web_cloud/web_hosting/diagnostic_errors_module1clic/guide.it-it.md
Labels: FIX

#6506 KevS-SK1599-Update-add-warning-paragraph-into-transfer-domain-guides
  pages/web_cloud/domains/transfer_incoming_couk/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_couk/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_gandi/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_gandi/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_godaddy/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_godaddy/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_homepl/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_hostinger/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_hostinger/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_ionos/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_ionos/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_o2switch/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_o2switch/guide.fr-fr.md
  pages/web_cloud/domains/transfer_incoming_wix/guide.fr-ca.md
  pages/web_cloud/domains/transfer_incoming_wix/guide.fr-fr.md
  pages/web_cloud/domains/transfer_pl/guide.fr-fr.md
Labels: Minor update

#6511 Fixes on various pages
  pages/bare_metal_cloud/virtual_private_servers/configuring-ip-aliasing/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/configuring-ip-aliasing/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/voip/register-sip-softphone-zoiper/guide.fr-fr.md
Labels: FIX
