Repository ovh/docs, pull requests merged in 2025-04, with the labels that each got.

#7701 Fixing typo in connectivity pages
  pages/web_cloud/internet/internet_access/advanced_config_router_manually/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_activer_backup_LTE/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_activer_bridge_zyxel/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_activer_envoi_mail/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_activer_mes_lignes_telephoniques_offre_adsl_vdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_changer_backend_acs/guide.fr-fr.md
Labels: FIX

#7700 feat(share images): add informations
  pages/public_cloud/compute/share_images_between_projects/guide.de-de.md
  pages/public_cloud/compute/share_images_between_projects/guide.en-asia.md
  pages/public_cloud/compute/share_images_between_projects/guide.en-au.md
  pages/public_cloud/compute/share_images_between_projects/guide.en-ca.md
  pages/public_cloud/compute/share_images_between_projects/guide.en-gb.md
  pages/public_cloud/compute/share_images_between_projects/guide.en-ie.md
  pages/public_cloud/compute/share_images_between_projects/guide.en-sg.md
  pages/public_cloud/compute/share_images_between_projects/guide.en-us.md
  pages/public_cloud/compute/share_images_between_projects/guide.es-es.md
  pages/public_cloud/compute/share_images_between_projects/guide.es-us.md
  pages/public_cloud/compute/share_images_between_projects/guide.fr-ca.md
  pages/public_cloud/compute/share_images_between_projects/guide.fr-fr.md
  pages/public_cloud/compute/share_images_between_projects/guide.it-it.md
  pages/public_cloud/compute/share_images_between_projects/guide.pl-pl.md
  pages/public_cloud/compute/share_images_between_projects/guide.pt-pt.md
  pages/public_cloud/compute/share_images_between_projects/meta.yaml
Labels: Minor update

#7709 Emails - Adding a domain - Fixing image and numbered list
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/exchange_adding_domain/images/add_domain_exchange_step2-1b.png
Labels: FIX

#7705 feat: add proxy cache guide for registry
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/images/registry-proxy-cache-001.png
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/images/registry-proxy-cache-002.png
  pages/public_cloud/containers_orchestration/managed_private_registry/configure-proxy-cache/meta.yaml
Labels: Guide creation

#7572 Object Storage - Lifecycle Rules (Recreation)
  pages/index.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/meta.yaml
Labels: Guide creation

#7716 Ls hot fix doc lifecycle about availability of feature on endpoint .perf
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pt-pt.md
Labels: FIX, Priority: Urgent

#7719 FR update overthebox version matrix
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
Labels: Minor update

#7718 Telecom - spelling updates & minor other updates
  pages/web_cloud/internet/internet_access/comment_activer_backup_LTE/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_activer_bridge_zyxel/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_activer_mes_lignes_telephoniques_offre_adsl_vdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_commander_et_gerer_un_bloc_ip_29/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_configurer_le_reverse_dns_de_ma_connexion/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_demenager_mon_acces_xdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_gerer_ipv6/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_gerer_mes_adresses_e_mails/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_resilier_mon_acces_xdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_reutiliser_wifi_zyxel_otb/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/configuration_du_modem_a_partir_de_votre_espace_client/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/connectivity-api/guide.en-gb.md
  pages/web_cloud/internet/internet_access/connectivity-api/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/end_of_copper_migration_ftth/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/faq/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/ftth_fix_access/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/interruption_de_service/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/la_desserte_interne/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/modification_du_profil_de_synchronisation/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/monitoring/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/obtenir_id_ppp/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/reestablish-synchronization/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/resoudre-interruption-lenteurs-navigation/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/restart_reboot_modem/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/verifier-lien-xdsl-sature/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/verifier_stabilite_acces/guide.fr-fr.md
Labels: FIX

#7722 Fixing - VCD limitations guide
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pt-pt.md
Labels: FIX, Priority: Urgent

#7733 Remove the 'soon' flag for MongoDB 8.0
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.pt-pt.md
Labels: Minor update

#7676 feat(object storage): create guide for connect other resource in a vrack
  pages/index.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.de-de.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.en-asia.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.en-au.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.en-ca.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.en-gb.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.en-ie.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.en-sg.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.en-us.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.es-es.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.es-us.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.fr-ca.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.fr-fr.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.it-it.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.pl-pl.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/guide.pt-pt.md
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/images/object_storage_buckets_vrack_private.png
  pages/storage_and_backup/object_storage/connect_other_ressources_in_vrack_private_network/meta.yaml
Labels: Guide creation, Quality Check

#7724 fixes on various guides
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.pt-pt.md
Labels: Do not merge yet, FIX

#7757 Guide Fix - VCD Limitations
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pt-pt.md
Labels: FIX, Priority: Urgent

#7760 Upgrade knative doc for MKS
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-knative/images/ovhcloud-entry-dns.png
Labels: Minor update

#7739 Ls update transition to include new storage class STANDARD_IA
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pt-pt.md
Labels: Minor update

#7618 FB - Softphone GA version
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/images/add_logo_manager.png
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/images/configuration_code_popup.png
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/images/download_softcall_manager_button.png
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/images/get_configuration_code_button.png
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/images/send_mail_manager.png
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/images/toggle_activation_sip.png
Labels: Do not merge yet

#7753 text update
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.de-de.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.en-asia.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.en-au.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.en-ca.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.en-gb.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.en-ie.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.en-sg.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.en-us.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.es-es.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.es-us.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.fr-ca.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.fr-fr.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.it-it.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/suspend_or_pause_an_instance/guide.pt-pt.md
Labels: Do not merge yet, FIX

#7761 Add new guide: Updating ESXi hosts with vSphere Lifecycle Manager (vLCM)
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/images/vlcm_00.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/images/vlcm_01.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/images/vlcm_02.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/images/vlcm_03.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/images/vlcm_04.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/images/vlcm_05.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/meta.yaml
  pages/index.md
Labels: Guide creation, Priority: High

#7768 VMware - Update ESXi hosts with vLCM - Index fix
  pages/index.md
Labels: FIX

#7769 Fixes on several guides
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx-02-segment-management/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.pt-pt.md
  pages/web_cloud/web_hosting/ftp_change_password/guide.en-asia.md
  pages/web_cloud/web_hosting/ftp_change_password/guide.en-au.md
  pages/web_cloud/web_hosting/ftp_change_password/guide.en-ca.md
  pages/web_cloud/web_hosting/ftp_change_password/guide.en-gb.md
  pages/web_cloud/web_hosting/ftp_change_password/guide.en-ie.md
  pages/web_cloud/web_hosting/ftp_change_password/guide.en-sg.md
  pages/web_cloud/web_hosting/ftp_change_password/guide.en-us.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.de-de.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.en-asia.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.en-au.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.en-ca.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.en-gb.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.en-ie.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.en-sg.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.en-us.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.es-es.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.es-us.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.fr-ca.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.fr-fr.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.it-it.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.pl-pl.md
  pages/web_cloud/web_hosting/logs_and_statistics/guide.pt-pt.md
Labels: FIX

#7731 Bare Metal Recovery with Veeam Agent – Guide creation
  pages/index.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.de-de.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-asia.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-au.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-gb.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-ie.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-sg.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.es-es.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.es-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.fr-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.fr-fr.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.it-it.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.pl-pl.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.pt-pt.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/bare_metal_recovery_01.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/bare_metal_recovery_02.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/bare_metal_recovery_03.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/bare_metal_recovery_04.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/bare_metal_recovery_05.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_01.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_02.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_03.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_04.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_05.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_06.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_07.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_08.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_09.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/images/step2_10.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/meta.yaml
Labels: Guide creation, Quality Check

#7755 fix(ceph create user): upadte guide
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.de-de.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.en-asia.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.en-au.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.en-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.en-gb.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.en-ie.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.en-sg.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.en-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.es-es.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.es-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.fr-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.fr-fr.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.it-it.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.pl-pl.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/guide.pt-pt.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/images/create_a_user_1.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/images/create_a_user_2.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_user/images/create_a_user_3.png
Labels: FIX, Quality Check

#7770 Guide Update - Vmware Maintenance
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.pt-pt.md
Labels: FIX, Priority: Urgent

#7735 Guide creation - Migrating VMware Workloads to OVHcloud SecNumCloud with Veeam Replication
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/images/secnumcloud.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam_secnumcloud/meta.yaml
  pages/index.md
Labels: Guide creation, Quality Check

#7773 Fixes and missing duplications
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_tuto_08_streaming_chatbot_langchain4j_quarkus/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.de-de.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.en-au.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.en-us.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.es-es.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.es-us.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.it-it.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/databases_07_cross_service_integration/guide.pt-pt.md
Labels: FIX

#7695 Encrypting backup jobs with Veeam and OKMS - Guide creation
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/console_1.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/console_2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_1.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_10.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_3.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_4.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_5.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_6.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_7.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_8.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/images/veeam_okms_9.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/meta.yaml
  pages/index.md
Labels: Guide creation

#7778 Veeam encrypt backup jobs - Format fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/veeam_encrypt_backup_job_with_okms/guide.pt-pt.md
Labels: FIX

#7737 Deleting guide - Logging in via SFTP
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.de-de.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.en-asia.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.en-au.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.en-ca.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.en-gb.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.en-ie.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.en-sg.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.en-us.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.es-es.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.es-us.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.fr-ca.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.fr-fr.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.it-it.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.pl-pl.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/guide.pt-pt.md
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/SFTP.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/SFTP1.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/SFTP3.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/SFTP4.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/SFTP5.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/SFTP6.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/SFTP7.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/connection_sftp_browse_datastore.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/connection_sftp_filezilla.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/connection_sftp_filezilla_log.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/sftpconnection.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/images/sftpconnexion.png
  pages/bare_metal_cloud/managed_bare_metal/sftp-connexion/meta.yaml
  pages/index.md
Labels: Guides removal

#7781 RM obsolete link
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.de-de.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.en-asia.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.en-au.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.en-ca.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.en-gb.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.en-ie.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.en-sg.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.en-us.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.es-es.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.es-us.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.fr-ca.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.fr-fr.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.it-it.md
  pages/bare_metal_cloud/managed_bare_metal/deploy-a-vm/guide.pt-pt.md
  pages/public_cloud/public_cloud_cross_functional/using_openstack_tokens_for_multiple_calls/guide.de-de.md
Labels: FIX

#7785 [PNRv2] - Guided Tour documentation
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.de-de.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.en-asia.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.en-au.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.en-ca.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.en-gb.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.en-ie.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.en-sg.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.en-us.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.es-es.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.es-us.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.fr-ca.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.fr-fr.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.it-it.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.pl-pl.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.pt-pt.md
  pages/account_and_service_management/account_information/new-control-panel-navigation/images/01-account-access.png
  pages/account_and_service_management/account_information/new-control-panel-navigation/images/02-account-menu.png
  pages/account_and_service_management/account_information/new-control-panel-navigation/images/03-services.png
  pages/account_and_service_management/account_information/new-control-panel-navigation/images/04-shortcuts.png
  pages/account_and_service_management/account_information/new-control-panel-navigation/meta.yaml
  pages/index.md
Labels: Guide creation

#7740 Remove Data Platform demo guide
  pages/index.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.de-de.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-asia.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-au.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-ca.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-gb.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-ie.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-sg.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.en-us.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.es-es.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.es-us.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.fr-ca.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.fr-fr.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.it-it.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.pl-pl.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/guide.pt-pt.md
  pages/public_cloud/data_platform/general-data-platform-video-demo/meta.yaml
Labels: Guides removal

#7783 Fixing images links - VCD limitation use cases
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: FIX, Priority: High

#7789 Fixes on several guides
  pages/account_and_service_management/account_information/new-control-panel-navigation/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.pt-pt.md
Labels: FIX

#7791 Updating VMware lifecyle policy guide
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.pt-pt.md
Labels: Priority: High

#7780 Add new guide: Move2Cloud - Migrating VMware Workloads to OVHcloud HPC with Veeam Replication (SK-1818)
  links/hosted-private-cloud/vmware-zerto
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/images/Move2PCC_Veam.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_migration_veeam/meta.yaml
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
Labels: Guide creation

#7744 KevS-SK1979-Full-update-Revamp-FAQ-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/faq-web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-asia.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-au.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-gb.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ie.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-sg.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-es.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.it-it.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pt-pt.md
Labels: Translations ONLY

#7798 Web Hosting FAQ - Fixing broken links
  pages/web_cloud/web_hosting/faq-web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pl-pl.md
Labels: FIX

#7794 OCC Diagnostics - New feature documentation
  pages/index.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.de-de.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.en-asia.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.en-au.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.en-ca.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.en-gb.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.en-ie.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.en-sg.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.en-us.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.es-es.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.es-us.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.fr-ca.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.fr-fr.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.it-it.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.pl-pl.md
  pages/network/ovhcloud_connect/occ-diagnostics/guide.pt-pt.md
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_cpanel.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_diag_choice.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_diag_tab_BGP.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_diag_tab_MAC.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_diag_view_button.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_service_BGP.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_service_MAC.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_service_test_button_BGP.png
  pages/network/ovhcloud_connect/occ-diagnostics/images/OCC_service_test_button_MAC.png
  pages/network/ovhcloud_connect/occ-diagnostics/meta.yaml
Labels: Guide creation

#7801 Guide Update - VCD migration uses case - SK-2083
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: Priority: High

#7805 VoIP and billing guides - Links & headers fixes
  pages/account_and_service_management/managing_billing_payments_and_services/faq-billing/guide.es-es.md
  pages/account_and_service_management/managing_billing_payments_and_services/faq-billing/guide.es-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/faq-billing/guide.fr-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/faq-billing/guide.fr-fr.md
  pages/account_and_service_management/managing_billing_payments_and_services/faq-billing/guide.it-it.md
  pages/web_cloud/phone_and_fax/voip/redirection_avec_presentation/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/voip/register-sip-softphone/guide.fr-fr.md
Labels: FIX

#7806 VMware - Guide Update - maintenance operations - Change estimated duration for hosts
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_maintenance/guide.pt-pt.md
Labels: FIX, Priority: High

#7803 fix(dedicated_servers/bring-your-own-{image,linux}): gentoo efibootloaderpath
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.pt-pt.md
Labels: FIX, Minor update

#7811 Fixes on several pages
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/images/login.png
  pages/public_cloud/public_cloud_network_services/additional-ip-import/guide.en-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.de-de.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-asia.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-au.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-ie.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-sg.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.es-es.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.es-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.fr-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.it-it.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.pl-pl.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.pt-pt.md
Labels: FIX
