Repository ovh/docs, pull requests merged in 2025-07, with the labels that each got.

#8110 Filename fix
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/meta.yaml
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/meta.yml
Labels: FIX

#8120 Quickfix-030725
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_mail_app_ios/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_app_ios/guide.en-gb.md
Labels: FIX

#8123 Ag Fixing typo - Arctera
  pages/storage_and_backup/object_storage/s3_ecosystem/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_ecosystem/guide.fr-fr.md
Labels: FIX, Priority: High

#8081 feat : add mks 1.33
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/software-versions-reserved-resources/guide.pt-pt.md
Labels: Minor update

#8093 FB - Git association - Better explain private key and private repo step
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/field-ssh-key-copy.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/field-ssh-key.png
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-asia.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-au.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-gb.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-ie.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-sg.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.en-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pt-pt.md
Labels: Minor update

#8128 Native support disclaimer
  pages/network/load_balancer/case_http2/guide.de-de.md
  pages/network/load_balancer/case_http2/guide.en-asia.md
  pages/network/load_balancer/case_http2/guide.en-au.md
  pages/network/load_balancer/case_http2/guide.en-ca.md
  pages/network/load_balancer/case_http2/guide.en-gb.md
  pages/network/load_balancer/case_http2/guide.en-sg.md
  pages/network/load_balancer/case_http2/guide.en-us.md
  pages/network/load_balancer/case_http2/guide.es-es.md
  pages/network/load_balancer/case_http2/guide.es-us.md
  pages/network/load_balancer/case_http2/guide.fr-ca.md
  pages/network/load_balancer/case_http2/guide.fr-fr.md
  pages/network/load_balancer/case_http2/guide.it-it.md
  pages/network/load_balancer/case_http2/guide.pl-pl.md
  pages/network/load_balancer/case_http2/guide.pt-pt.md
Labels: Minor update, Translations

#8135 Zimbra - Oulook on Windows - Image fix
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/images/outlook-windows-add-step-07.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_outlook_windows/images/outlook-windows-add-step07.png
Labels: FIX

#8108 Feat improve versioningbucket guide
  pages/storage_and_backup/object_storage/s3_versioning/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_versioning/images/bucket_creation_versioning.png
  pages/storage_and_backup/object_storage/s3_versioning/images/bucket_delete_object_versions.png
  pages/storage_and_backup/object_storage/s3_versioning/images/bucket_download_versions.png
  pages/storage_and_backup/object_storage/s3_versioning/images/bucket_enable_versions.png
  pages/storage_and_backup/object_storage/s3_versioning/images/bucket_modification_versioning.png
  pages/storage_and_backup/object_storage/s3_versioning/images/bucket_versions_object_details.png
Labels: Minor update

#8134 SK-2228-WEB-Emails-Zimbra_Pro-Briefcase-FR
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/images/zimbra-storage-01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/images/zimbra-storage-add-01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/images/zimbra-storage-share-01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/images/zimbra-storage-share-02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/images/zimbra-storage-share-invite-01.png
Labels: Priority: High

#8109 HB POL de reversbilibilité LDP + data platform
  pages/account_and_service_management/reversibility/18-logs-data-platform-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/18-logs-data-platform-reversibility/guide.fr-fr.md
  pages/account_and_service_management/reversibility/18-logs-data-platform-reversibility/meta.yaml
  pages/account_and_service_management/reversibility/19-data-platform-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/19-data-platform-reversibility/guide.fr-fr.md
  pages/account_and_service_management/reversibility/19-data-platform-reversibility/meta.yaml
  pages/index.md
Labels: Guide creation

#8142 Zimbra-Pro-Briefcase-Translations
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.pt-pt.md
Labels: Translations ONLY

#8145 Zimbra - List fix
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.pl-pl.md
Labels: FIX

#8148 KMS architecture guide typo fixing
  pages/manage_and_operate/kms/architecture-overview/guide.de-de.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-asia.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-au.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-ca.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-gb.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-ie.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-sg.md
  pages/manage_and_operate/kms/architecture-overview/guide.en-us.md
  pages/manage_and_operate/kms/architecture-overview/guide.es-es.md
  pages/manage_and_operate/kms/architecture-overview/guide.es-us.md
  pages/manage_and_operate/kms/architecture-overview/guide.fr-ca.md
  pages/manage_and_operate/kms/architecture-overview/guide.fr-fr.md
  pages/manage_and_operate/kms/architecture-overview/guide.it-it.md
  pages/manage_and_operate/kms/architecture-overview/guide.pl-pl.md
  pages/manage_and_operate/kms/architecture-overview/guide.pt-pt.md
Labels: FIX

#8136 Hb ia reversbility
  pages/account_and_service_management/reversibility/20-ai-notebook-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/20-ai-notebook-reversibility/guide.fr-fr.md
  pages/account_and_service_management/reversibility/20-ai-notebook-reversibility/meta.yaml
  pages/account_and_service_management/reversibility/21-ai-managed-containers-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/21-ai-managed-containers-reversibility/guide.fr-fr.md
  pages/account_and_service_management/reversibility/21-ai-managed-containers-reversibility/meta.yaml
  pages/index.md
Labels: Guide creation

#8126 KevS-SK2215-LLMCB-Your-IP-Has-been-banned-for-WebHosting
  pages/assets/screens/other/browsers/errors/your-ip-has-been-banned.png
  pages/index.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/guide.de-de.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/guide.en-gb.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/guide.es-es.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/guide.fr-fr.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/guide.it-it.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/guide.pl-pl.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/guide.pt-pt.md
  pages/web_cloud/web_hosting/diagnostic_ip_banned/meta.yaml
Labels: Guide creation, Translations

#8151 Object Storage Ecosystem - Adding Backint for SAP HANA
  pages/storage_and_backup/object_storage/s3_ecosystem/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_ecosystem/guide.fr-fr.md
Labels: Update request, Priority: Low

#8122 EN/FR Manage EFS with Terraform
  pages/index.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_terraform/guide.en-gb.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_terraform/guide.fr-fr.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_terraform/meta.yaml
Labels: Guide creation

#8156 AG - s3:ListAllMyBuckets - user policies
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.fr-fr.md
Labels: Update request, Priority: Low

#8166 Fixes on several pages
  pages/account_and_service_management/reversibility/23-mutualized-virtualization-vcd-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/23-mutualized-virtualization-vcd-reversibility/guide.fr-fr.md
  pages/index.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_terraform/guide.fr-fr.md
  pages/storage_and_backup/file_storage/ha_nas/nas_faq/guide.pt-pt.md
Labels: FIX

#8152 Attach Floating IP to Instance - Adding Horizon steps
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/associate_floating_ip.png
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/confirm_disassociate_ip.png
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/disassociate_floating_ip.png
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/instance_floating_ip.png
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/network_floating_ip.png
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/region2021.png
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/release_floating_ip.png
  pages/public_cloud/public_cloud_network_services/getting-started-03-attach-floating-ip-to-instance/images/select_port.png
Labels: Do not merge yet, Minor update

#8173 Guide Update - Vmware Lifecycle policy
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/lifecycle_policy/guide.pt-pt.md
Labels: Update request, Priority: Urgent

#8195 feat(cross functional): update terraform guide getting started
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.de-de.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.en-asia.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.en-au.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.en-ca.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.en-gb.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.en-ie.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.en-sg.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.en-us.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.es-es.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.es-us.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.fr-ca.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.fr-fr.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.it-it.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.pl-pl.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/guide.pt-pt.md
  pages/public_cloud/public_cloud_cross_functional/how_to_use_terraform/images/TF1.txt
Labels: Minor update

#8197 IAM For Logs Data Platform
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/basic_policy_1.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/basic_policy_2.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/carousel_policy_sub_1.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/carousel_policy_sub_2.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/carousel_policy_sub_3.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/carousel_policy_sub_4.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/create_group.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/create_policy_service_1.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/create_policy_service_2.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/create_rg.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/create_user.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/local_user_control_panel.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/policy_create_actions.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/policy_streams.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/policy_sub_product_types.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/service_empty.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/meta.yaml
  pages/manage_and_operate/observability/logs_data_platform/iam_migration_to_iam/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/iam_migration_to_iam/images/graylog_legacy.png
  pages/manage_and_operate/observability/logs_data_platform/iam_migration_to_iam/meta.yaml
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/activate_iam_existing_service.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/activate_iam_new_service.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/activated_iam.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/grafana_header.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/graylog_iam_ca.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/graylog_iam_eu.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/graylog_legacy.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/iam_policies.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/images/osd_iam_eu.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/meta.yaml
Labels: Guide creation

#8199 IAM for LDP - fixes
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/carousel_policy_sub_0.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/create_group01.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/create_rg01.png
  pages/manage_and_operate/observability/logs_data_platform/iam_access_management/images/local_user_control_panel01.png
  pages/manage_and_operate/observability/logs_data_platform/iam_migration_to_iam/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/iam_migration_to_iam/images/graylog-legacy.png
  pages/manage_and_operate/observability/logs_data_platform/iam_presentation_faq/guide.en-gb.md
Labels: FIX

#8144 FB - EOS Plesk & cPanel VPS - Assurer la continuité de vos services.
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/images/vpshome.png
  pages/bare_metal_cloud/virtual_private_servers/eos-cpanel-plesk/meta.yaml
  pages/index.md
Labels: Guide creation

#8200 FR internet edit profile name
  pages/web_cloud/internet/internet_access/advanced_config_router_manually/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/advanced_config_router_manually/images/profil-2025.png
Labels: Minor update

#8212 AG-terraform object storage-update
  pages/storage_and_backup/object_storage/s3_terraform/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.pt-pt.md
Labels: FIX, Minor update, Priority: Low

#8222 Ag versioning fix
  pages/storage_and_backup/object_storage/s3_versioning/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_versioning/guide.pt-pt.md
Labels: FIX

#8228 Quickfix-310725
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/images/vcd-link-ip-vrack-01.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/images/vcd-link-ip-vrack-02.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/images/vcd-link-ip-vrack-03.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_link_ip_to_vrack/images/vcd-link-ip-vrack-04.png
Labels: FIX
