Repository ovh/docs, pull requests merged in 2025-09, with the labels that each got.

#8333 delete(mongo): delete guide 11
  pages/index.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/mongodb_11_howto_migrate_to_discovery/meta.yaml
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pt-pt.md
Labels: Guides removal

#8338 fix(databases): delete mongodb_12 call
  pages/index.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pt-pt.md
Labels: FIX

#8330 feat(databases): guide about migration
  pages/index.md
  pages/public_cloud/public_cloud_databases/databases_20_move_to_cloud/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_20_move_to_cloud/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/databases_20_move_to_cloud/images/schema.png
  pages/public_cloud/public_cloud_databases/databases_20_move_to_cloud/meta.yaml
Labels: Guide creation

#8327 SK-1708-WEB-Emails-MXplan-How_to_create_email--how_extend_emails]_DE_ES_IT_PL_PT
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_creation/guide.pt-pt.md
Labels: Translations ONLY

#8356 [AI Endpoints] - Pricing for new models
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.pt-pt.md
Labels: Minor update

#8323 FB - Import/export n8n
  pages/bare_metal_cloud/virtual_private_servers/import-export-n8n/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/import-export-n8n/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/import-export-n8n/images/credentials_successfully_copied.png
  pages/bare_metal_cloud/virtual_private_servers/import-export-n8n/images/credentials_successfully_exported.png
  pages/bare_metal_cloud/virtual_private_servers/import-export-n8n/images/workflow_successfully_copied.png
  pages/bare_metal_cloud/virtual_private_servers/import-export-n8n/images/workflow_successfully_exported.png
  pages/bare_metal_cloud/virtual_private_servers/import-export-n8n/meta.yaml
  pages/index.md
Labels: Guide creation

#8362 Minor updats on various guides
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.de-de.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.en-asia.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.en-au.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.en-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.en-gb.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.en-ie.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.en-sg.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.en-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.es-es.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.es-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.fr-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.fr-fr.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.it-it.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.pl-pl.md
  pages/account_and_service_management/managing_billing_payments_and_services/changing_hourly_monthly_billing/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/hardware-diagnose/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/resetting_a_windows_password/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/getting-source-ip-behind-loadbalancer/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/responsibility_model_private_email_server_exchange/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/responsibility_model_private_email_server_exchange/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/responsibility_model_private_email_server_exchange/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/responsibility_model_private_email_server_exchange/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/responsibility_model_private_email_server_exchange/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/responsibility_model_private_email_server_exchange/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/microsoft_exchange/responsibility_model_private_email_server_exchange/guide.pt-pt.md
Labels: FIX

#8373 typo fixing on IAM conditions
  pages/account_and_service_management/account_information/iam-policies-api/guide.de-de.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-asia.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-au.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-ca.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-gb.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-ie.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-sg.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.en-us.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.es-es.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.es-us.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.fr-ca.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.fr-fr.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.it-it.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.pl-pl.md
  pages/account_and_service_management/account_information/iam-policies-api/guide.pt-pt.md
Labels: FIX

#8334 feat(mks): renaming of premium and standard plans
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/known-limits/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/images/creating-a-cluster5.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/setting-up-a-persistent-volume/guide.pt-pt.md
Labels: Minor update

#8380 MKS Standard - Missing duplication
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.pt-pt.md
Labels: FIX

#8393 update(Object Storage): update UI for the getting started guide
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/01-object-storage-bucket-listing.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-Getting-started-20211123123335113.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028090916484.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028091015710.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028091254996.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028091356617.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028091456850.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028093009189.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028093103226.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-2021102809321218.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/HighPerf-S3-getting-started-20211028093408437.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/create-container-20211005102334181.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/create-container-20211005115040834.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/delete-bucket.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/delete-file.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/download-file-from-bucket.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/go-in-bucket.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/highperf-create-container-20220928091433895.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/highperf-s3-getting-started-20220502112813860.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/highperf-s3-getting-started-20220721141708221.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/highperf-s3-getting-started-20220721141829843.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step1.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step2.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step3.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step4.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step4_1.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step4_2.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step4_3.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step4_4.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step5.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step6.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-bucket-creation-step7.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object-storage-creation-step-offsite-replication.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_add_object.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_add_object_window.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_information_panel.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_items_delete.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_items_download.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_list.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_list_delete.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/object_storage_list_selection.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/upload-file.png
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/images/upload-files-window.png
Labels: Minor update

#8400 testing(octavia lb): testing the guide
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/technical-resources-01-using-lbaas-in-openstack-environment/guide.pt-pt.md
Labels: Minor update

#8405 Cold Archive minimum duration typo
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/guide.pt-pt.md
Labels: FIX, Priority: High

#8367 Feat ceph cephs refacto
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.de-de.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.en-asia.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.en-au.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.en-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.en-gb.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.en-ie.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.en-sg.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.en-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.es-es.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.es-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.fr-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.fr-fr.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.it-it.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.pl-pl.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/guide.pt-pt.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/image.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/images/api_request_01.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/images/api_request_02.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/images/api_request_03.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/images/api_request_04.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/images/api_request_05.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_cephfs/images/api_request_06.png
Labels: Update request

#8410 feat(3az guide): delete comingsoon text
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.de-de.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-asia.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-au.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-ca.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-gb.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-ie.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-sg.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-us.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.es-es.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.es-us.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.fr-ca.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.fr-fr.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.it-it.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.pl-pl.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.pt-pt.md
Labels: Minor update

#8394 OKMS : Moving certificate creation to a dedicated guide
  pages/index.md
  pages/manage_and_operate/kms/okms-certificate-management/guide.en-gb.md
  pages/manage_and_operate/kms/okms-certificate-management/guide.fr-fr.md
  pages/manage_and_operate/kms/okms-certificate-management/images/create_certificat_01.png
  pages/manage_and_operate/kms/okms-certificate-management/images/create_certificat_02.png
  pages/manage_and_operate/kms/okms-certificate-management/images/create_certificat_03.png
  pages/manage_and_operate/kms/okms-certificate-management/images/create_certificat_04.png
  pages/manage_and_operate/kms/okms-certificate-management/images/create_certificat_05.png
  pages/manage_and_operate/kms/okms-certificate-management/images/create_certificat_06.png
  pages/manage_and_operate/kms/okms-certificate-management/meta.yaml
  pages/manage_and_operate/kms/quick-start/guide.de-de.md
  pages/manage_and_operate/kms/quick-start/guide.en-asia.md
  pages/manage_and_operate/kms/quick-start/guide.en-au.md
  pages/manage_and_operate/kms/quick-start/guide.en-ca.md
  pages/manage_and_operate/kms/quick-start/guide.en-gb.md
  pages/manage_and_operate/kms/quick-start/guide.en-ie.md
  pages/manage_and_operate/kms/quick-start/guide.en-sg.md
  pages/manage_and_operate/kms/quick-start/guide.en-us.md
  pages/manage_and_operate/kms/quick-start/guide.es-es.md
  pages/manage_and_operate/kms/quick-start/guide.es-us.md
  pages/manage_and_operate/kms/quick-start/guide.fr-ca.md
  pages/manage_and_operate/kms/quick-start/guide.fr-fr.md
  pages/manage_and_operate/kms/quick-start/guide.it-it.md
  pages/manage_and_operate/kms/quick-start/guide.pl-pl.md
  pages/manage_and_operate/kms/quick-start/guide.pt-pt.md
Labels: Guide creation

#8414 delete(mongo): delete guide about automated migration
  pages/index.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/meta.yaml
Labels: Guides removal

#8417 Update_MST_documentation
  pages/hosted_private_cloud/nutanix_on_ovhcloud/81-multi-snapshot-technologie/guide.en-gb.md
Labels: FIX

#8403 fix(Block Storage): add warning in additional disk guide for luks type
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.de-de.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-asia.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-au.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-gb.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ie.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-sg.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-es.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-fr.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.it-it.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pt-pt.md
Labels: Minor update

#8441 KevS-SK2373-Revamp_multisite_and_1_clic_modules-screens-of-secondary-guides-concerned-for-WebHosting
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/databases/go-to-phpmyadmin.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/email-scripts/tab.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/find-webhosting-name.png
Labels: Minor update

#8444 Add guide SD firmware update Micron
  pages/bare_metal_cloud/dedicated_servers/micron-7500-fw-upgrade/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/micron-7500-fw-upgrade/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/micron-7500-fw-upgrade/meta.yaml
  pages/index.md
Labels: Guide creation, Priority: High

#8445 Minor fix
  pages/bare_metal_cloud/dedicated_servers/micron-7500-fw-upgrade/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/micron-7500-fw-upgrade/guide.fr-fr.md
Labels: FIX

#8453 Guide update - Bare Metal recovery with Veeam Backup Agent - Sk-2379
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.de-de.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-asia.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-au.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-gb.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-ie.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-sg.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.en-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.es-es.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.es-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.fr-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.fr-fr.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.it-it.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.pl-pl.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/veeam_agent_bare_metal_recovery/guide.pt-pt.md
Labels: Minor update

#8457 Add proofs
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_windows_10/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_windows_10/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_windows_10/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/how_to_configure_windows_10/guide.en-us.md
Labels: Minor update
