Repository ovh/docs, pull requests merged in 2025-02, with the labels that each got.

#7481 Web Hosting - Using git - Last update translations
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.de-de.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-es.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.es-us.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.it-it.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/git_integration_webhosting/guide.pt-pt.md
Labels: Translations ONLY

#7458 KevS-SK-1892-KFT0023064-KFT0023202-Update-How-to-renew-OVHcloud-services-for-Account-and-service-managment-TRANSLATIONS
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.de-de.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-asia.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-au.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-gb.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-ie.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-sg.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.en-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.es-es.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.es-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.fr-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.fr-fr.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.it-it.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.pl-pl.md
  pages/account_and_service_management/managing_billing_payments_and_services/how_to_use_automatic_renewal/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue

#7488 fix(analytics): add images for terraform init
  pages/public_cloud/data_analytics/analytics/analytics_getting_started_terraform/images/api-rights.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started_terraform/images/get-service-name.png
Labels: FIX

#7489 Analytics - Minor edits
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.de-de.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.en-asia.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.en-au.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.en-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.en-ie.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.en-sg.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.en-us.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.es-es.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.es-us.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.fr-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.fr-fr.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.it-it.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.pl-pl.md
  pages/public_cloud/data_analytics/analytics/analytics_restore_backup/guide.pt-pt.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.de-de.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-asia.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-au.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-ie.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-sg.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-us.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.es-es.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.es-us.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.fr-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.fr-fr.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.it-it.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.pl-pl.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.pt-pt.md
Labels: FIX

#7490 KevS-SK1901-FullUpdate-Change-owner-for-DomainDNS-TRANSLATIONS
  pages/web_cloud/domains/trade_domain/guide.de-de.md
  pages/web_cloud/domains/trade_domain/guide.en-asia.md
  pages/web_cloud/domains/trade_domain/guide.en-au.md
  pages/web_cloud/domains/trade_domain/guide.en-ca.md
  pages/web_cloud/domains/trade_domain/guide.en-gb.md
  pages/web_cloud/domains/trade_domain/guide.en-ie.md
  pages/web_cloud/domains/trade_domain/guide.en-sg.md
  pages/web_cloud/domains/trade_domain/guide.en-us.md
  pages/web_cloud/domains/trade_domain/guide.es-es.md
  pages/web_cloud/domains/trade_domain/guide.es-us.md
  pages/web_cloud/domains/trade_domain/guide.fr-ca.md
  pages/web_cloud/domains/trade_domain/guide.fr-fr.md
  pages/web_cloud/domains/trade_domain/guide.it-it.md
  pages/web_cloud/domains/trade_domain/guide.pl-pl.md
  pages/web_cloud/domains/trade_domain/guide.pt-pt.md
Labels: Translations ONLY, Priority: Urgent

#7501 Fixes on several pages
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.es-us.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.de-de.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-asia.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-au.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-ie.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-sg.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-us.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.es-es.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.es-us.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.fr-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.fr-fr.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.it-it.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.pl-pl.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.pt-pt.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.de-de.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-asia.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-au.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-ie.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-sg.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-us.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.es-es.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.es-us.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.fr-ca.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.fr-fr.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.it-it.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.pl-pl.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.pt-pt.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/images/flavor_change.png
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/images/flavor_change_view.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/guide.pt-pt.md
Labels: FIX

#7495 S3 - FAQ - Offsite Replication option details
  pages/storage_and_backup/object_storage/s3_faq/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_faq/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_faq/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_faq/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_faq/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_faq/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_faq/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_faq/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_faq/guide.pt-pt.md
Labels: Priority: Urgent

#7503 KevS-SK1901-Fix-change-owner
  pages/web_cloud/domains/trade_domain/guide.de-de.md
  pages/web_cloud/domains/trade_domain/guide.en-asia.md
  pages/web_cloud/domains/trade_domain/guide.en-au.md
  pages/web_cloud/domains/trade_domain/guide.en-ca.md
  pages/web_cloud/domains/trade_domain/guide.en-gb.md
  pages/web_cloud/domains/trade_domain/guide.en-ie.md
  pages/web_cloud/domains/trade_domain/guide.en-sg.md
  pages/web_cloud/domains/trade_domain/guide.en-us.md
  pages/web_cloud/domains/trade_domain/guide.es-es.md
  pages/web_cloud/domains/trade_domain/guide.es-us.md
  pages/web_cloud/domains/trade_domain/guide.fr-ca.md
  pages/web_cloud/domains/trade_domain/guide.fr-fr.md
  pages/web_cloud/domains/trade_domain/guide.it-it.md
  pages/web_cloud/domains/trade_domain/guide.pl-pl.md
  pages/web_cloud/domains/trade_domain/guide.pt-pt.md
Labels: Minor update, Translations

#7498 Minor text adjusments on various guides
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/antispam_best_practices/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_ipv6/guide.pt-pt.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.de-de.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-asia.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-au.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-ca.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-gb.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-ie.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-sg.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-us.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.es-es.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.es-us.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.fr-ca.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.fr-fr.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.it-it.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.pl-pl.md
  pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.pt-pt.md
Labels: Do not merge yet, Quality Check

#7506 Fixes
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/config_additional_disk/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.de-de.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.de-de.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-asia.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-au.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-ca.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-gb.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-ie.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-sg.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.en-us.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.es-es.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.es-us.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.fr-ca.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.fr-fr.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.it-it.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.pl-pl.md
  pages/public_cloud/compute/public-cloud-first-steps/guide.pt-pt.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.de-de.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-asia.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-au.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-ca.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-gb.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-ie.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-sg.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.en-us.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.es-es.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.es-us.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.fr-ca.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.fr-fr.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.it-it.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.pl-pl.md
  pages/web_cloud/web_hosting/ssh_using_putty_on_windows/guide.pt-pt.md
Labels: Minor update

#7507 Update Object Storage - Create Bucket - Bucket Name
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_create_bucket/guide.pt-pt.md
Labels: Minor update

#7508 KevS-SK1911-Update-How-to-create-subdomain-for-DomainDNS-TRANSLATIONS
  pages/assets/schemas/domains/url-composition.png
  pages/web_cloud/domains/domain_create_subdomains/guide.de-de.md
  pages/web_cloud/domains/domain_create_subdomains/guide.en-asia.md
  pages/web_cloud/domains/domain_create_subdomains/guide.en-au.md
  pages/web_cloud/domains/domain_create_subdomains/guide.en-ca.md
  pages/web_cloud/domains/domain_create_subdomains/guide.en-gb.md
  pages/web_cloud/domains/domain_create_subdomains/guide.en-ie.md
  pages/web_cloud/domains/domain_create_subdomains/guide.en-sg.md
  pages/web_cloud/domains/domain_create_subdomains/guide.en-us.md
  pages/web_cloud/domains/domain_create_subdomains/guide.es-es.md
  pages/web_cloud/domains/domain_create_subdomains/guide.es-us.md
  pages/web_cloud/domains/domain_create_subdomains/guide.fr-ca.md
  pages/web_cloud/domains/domain_create_subdomains/guide.it-it.md
  pages/web_cloud/domains/domain_create_subdomains/guide.pl-pl.md
  pages/web_cloud/domains/domain_create_subdomains/guide.pt-pt.md
Labels: Translations ONLY

#7509 SK-1788-WEB-Emails-mxplan-outlook-ios
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add-step01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add-step02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add-step021.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add-step03-imap-ca.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add-step03-imap-eu.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add-step03-pop-ca.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add-step03-pop-eu.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-add02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-delete-account-01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/images/outlook-app-android-delete-account-02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android/meta.yaml
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/images/outlook-app-ios-add-step01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/images/outlook-app-ios-add-step02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/images/outlook-app-ios-add-step03-imap-eu.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/images/outlook-app-ios-add01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/images/outlook-app-ios-add02.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/images/outlook-app-ios-modify-account-01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/images/outlook-app-ios-modify-delete-01.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_ios/meta.yaml
Labels: Guide creation

#7492 Feat(OS lifecycle): improve os lifecycle guide
  pages/public_cloud/compute/image-life-cycle/guide.de-de.md
  pages/public_cloud/compute/image-life-cycle/guide.en-asia.md
  pages/public_cloud/compute/image-life-cycle/guide.en-au.md
  pages/public_cloud/compute/image-life-cycle/guide.en-ca.md
  pages/public_cloud/compute/image-life-cycle/guide.en-gb.md
  pages/public_cloud/compute/image-life-cycle/guide.en-ie.md
  pages/public_cloud/compute/image-life-cycle/guide.en-sg.md
  pages/public_cloud/compute/image-life-cycle/guide.en-us.md
  pages/public_cloud/compute/image-life-cycle/guide.es-es.md
  pages/public_cloud/compute/image-life-cycle/guide.es-us.md
  pages/public_cloud/compute/image-life-cycle/guide.fr-ca.md
  pages/public_cloud/compute/image-life-cycle/guide.fr-fr.md
  pages/public_cloud/compute/image-life-cycle/guide.it-it.md
  pages/public_cloud/compute/image-life-cycle/guide.pl-pl.md
  pages/public_cloud/compute/image-life-cycle/guide.pt-pt.md
Labels: FIX

#7518 Updating Swift x S3 API AWS CLI configuration
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.de-de.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.en-asia.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.en-au.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.en-ca.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.en-gb.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.en-ie.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.en-sg.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.en-us.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.es-es.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.es-us.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.fr-ca.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.fr-fr.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.it-it.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.pl-pl.md
  pages/storage_and_backup/object_storage/pcs_getting_started_with_the_swift_s3_api/guide.pt-pt.md
Labels: Minor update

#7519 Updating S3 API AWS CLI configuration
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pt-pt.md
Labels: Minor update

#7524 Upd KVM VPS
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/vps/open-kvm.png
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/images/kvm-new1.png
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/images/kvm-new2.png
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/images/kvm_screen.png
  pages/bare_metal_cloud/virtual_private_servers/using_kvm_for_vps/meta.yaml
  pages/index.md
Labels: KFT / Issue, Translations

#7522 KevS-SK1916-Update-Multisite-geolocation-IP-for-WebHosting
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/multisite.png
  pages/web_cloud/web_hosting/multisites_geolocation/guide.fr-fr.md
Labels: Update request

#7486 feat(Savinsg plan): create guide about how create SVP
  pages/index.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.de-de.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-asia.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-au.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-ca.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-gb.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-ie.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-sg.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-us.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.es-es.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.es-us.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.fr-ca.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.fr-fr.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.it-it.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.pl-pl.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.pt-pt.md
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_duration_name.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_menu.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_service.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_terms_and_creation.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_update_menu.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_update_name.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_update_renewal.png
  pages/public_cloud/compute/how_to_manage_savings_plan/meta.yaml
Labels: Guide creation

#7532 Minor updates on Public Cloud & Email articles to trigger their produ…
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.de-de.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-asia.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-au.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-ca.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-gb.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-ie.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-sg.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-us.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.es-es.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.es-us.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.fr-ca.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.fr-fr.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.it-it.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.pl-pl.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.pt-pt.md
  pages/public_cloud/compute/savings_plans/guide.de-de.md
  pages/public_cloud/compute/savings_plans/guide.en-asia.md
  pages/public_cloud/compute/savings_plans/guide.en-au.md
  pages/public_cloud/compute/savings_plans/guide.en-ca.md
  pages/public_cloud/compute/savings_plans/guide.en-gb.md
  pages/public_cloud/compute/savings_plans/guide.en-ie.md
  pages/public_cloud/compute/savings_plans/guide.en-sg.md
  pages/public_cloud/compute/savings_plans/guide.en-us.md
  pages/public_cloud/compute/savings_plans/guide.es-es.md
  pages/public_cloud/compute/savings_plans/guide.es-us.md
  pages/public_cloud/compute/savings_plans/guide.fr-ca.md
  pages/public_cloud/compute/savings_plans/guide.fr-fr.md
  pages/public_cloud/compute/savings_plans/guide.it-it.md
  pages/public_cloud/compute/savings_plans/guide.pl-pl.md
  pages/public_cloud/compute/savings_plans/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.fr-fr.md
Labels: Minor update

#7536 fix(savings plan creation): add images and fix
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.de-de.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-asia.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-au.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-ca.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-gb.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-ie.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-sg.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.en-us.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.es-es.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.es-us.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.fr-ca.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.fr-fr.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.it-it.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.pl-pl.md
  pages/public_cloud/compute/how_to_manage_savings_plan/guide.pt-pt.md
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_list_service.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_list_service_details.png
  pages/public_cloud/compute/how_to_manage_savings_plan/images/savings_plan_list_svp.png
Labels: FIX

#7535 KevS-SK1918-Update-FAQ-WebHosting
  pages/web_cloud/web_hosting/faq-web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-asia.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-au.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-gb.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ie.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-sg.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-es.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.it-it.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pt-pt.md
Labels: Translations

#7539 Nutanix - KMS configuration
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.de-de.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.en-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.en-gb.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.en-ie.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.en-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.es-es.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.es-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.pl-pl.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/guide.pt-pt.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/01-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/02-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/03-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/04-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/05-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/06-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/07-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/08-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/09-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/10-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/11-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/images/12-kms-configuration.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/13-kms-configuration/meta.yaml
  pages/index.md
Labels: Guide creation

#7543 Fixes and improvements on several guides
  links/hosted-private-cloud/nutanix
  pages/web_cloud/web_hosting/backup_ftp_cloud_web/guide.fr-fr.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-asia.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-au.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-gb.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ie.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-sg.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-es.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.es-us.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.it-it.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pl-pl.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.pt-pt.md
Labels: FIX

#7544 Dedicated Servers - LACP Netplan guide update and link addition
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/lacp-enable-netplan/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/ola-enable-manager/guide.pt-pt.md
Labels: Minor update

#7529 KevS-SK1916-Update-Multisite-geolocation-IP-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-asia.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-au.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-ca.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-gb.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-ie.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-sg.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.en-us.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.en-ie.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.pt-pt.md
Labels: Translations

#7531 KevS-SK1917-Creation-carbon-footprint-guide
  links/bare-metal/eco
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-asia.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-au.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-gb.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-ie.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-sg.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.fr-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.fr-fr.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/meta.yaml
  pages/assets/screens/api/get-me-carboncalculator-task-taskid-response.png
  pages/assets/screens/api/get-me-carboncalculator-task-taskid.png
  pages/assets/screens/api/post-me-carboncalculator-task-response.png
  pages/assets/screens/api/post-me-carboncalculator-task.png
  pages/assets/screens/control_panel/product-selection/right-column/carbon-footprint/my-carbon-footprint.png
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
Labels: Guide creation

#7537 Public Cloud - translations for feat-add-interface-matrice
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.de-de.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.en-asia.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.en-au.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.en-ca.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.en-gb.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.en-ie.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.en-sg.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.en-us.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.es-es.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.es-us.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.fr-ca.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.fr-fr.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.it-it.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.pl-pl.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/guide.pt-pt.md
  pages/public_cloud/compute/03-public-cloud-interface-walk-me/meta.yaml
Labels: Translations ONLY

#7553 Carbon footprint - FR fixes
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.fr-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.fr-fr.md
Labels: FIX

#7300 New Guide - PCI - Configuring a Public IP block in a vRack on an Instance - KFT0023215
  pages/index.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/addIPblock.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/addprojectvrack.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/attach_interface.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/attach_network.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/attach_public_IP.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/compute_instances.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/configure_private_network.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/create-network.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/create_subnet.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/create_subnet_1.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/display_subnet.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/network_configuration.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/region2021.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/step5_private_network.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/vrack2021-01.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/vrack2022-03.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/images/vrack2024-01.png
  pages/public_cloud/public_cloud_network_services/configuration-06-configure-ip-block-vrack-to-instance/meta.yaml
Labels: Guide creation, KFT / Issue, Quality Check

#7566 Guides deletion - Heat + Blackberry
  pages/index.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.en-asia.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.en-au.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.en-ca.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.en-gb.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.en-ie.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.en-sg.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.en-us.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.fr-ca.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/guide.fr-fr.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure-modularity/meta.yaml
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.en-asia.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.en-au.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.en-ca.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.en-gb.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.en-ie.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.en-sg.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.en-us.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.fr-ca.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/guide.fr-fr.md
  pages/public_cloud/compute/heat-openstack-deploy-infrastructure/meta.yaml
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/1.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/10.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/11.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/12.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/13.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/14.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/15.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/2.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/3.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/4.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/5.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/6.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/7.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/8.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/images/9.png
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_blackberry/meta.yaml
Labels: Guides removal

#7576 HDS warranties - Tables fix
  pages/account_and_service_management/account_information/hds_garanties/guide.fr-fr.md
Labels: FIX

#7577 HDS Warranties - Tables addition and fixes
  pages/account_and_service_management/account_information/hds_garanties/guide.fr-fr.md
Labels: FIX

#7580 Upd SFTP for BM
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/images/sftp_ds_01.png
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/images/sftp_ds_02.png
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/images/sftp_ds_03.png
  pages/bare_metal_cloud/dedicated_servers/comment-deposer-ou-recuperer-des-donnees-sur-un-serveur-dedie-via-sftp/meta.yaml
  pages/index.md
Labels: Translations

#7581 MKS - Installing OpenFaaS - Format patches
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/installing-openfaas/guide.pt-pt.md
Labels: FIX

#7583 Compute - Start instance on attached volume - Fixes
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.en-asia.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.en-au.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.en-ca.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.en-gb.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.en-ie.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.en-sg.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.en-us.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.es-es.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.es-us.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.fr-ca.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.fr-fr.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.it-it.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.pl-pl.md
  pages/public_cloud/compute/start_instance_on_attached_volume/guide.pt-pt.md
Labels: FIX

#7557 BYOIP - APNIC support update
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.de-de.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-asia.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-au.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-ca.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-gb.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-ie.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-sg.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-us.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.es-es.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.es-us.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.fr-ca.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.fr-fr.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.it-it.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.pl-pl.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.pt-pt.md
Labels: Do not merge yet

#7586 VSPC - Getting Started
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.de-de.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-asia.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-au.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-gb.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-ie.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-sg.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.es-es.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.es-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.fr-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.fr-fr.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.it-it.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.pl-pl.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.pt-pt.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/VSPC-console.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/assigning-policy-step01.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/assigning-policy-step02.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/assigning-policy-step03.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/backup-policy-step01.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/backup-policy-step02.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/backup-policy-step03.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/download-agent-step01.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/download-agent-step02.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/download-agent-step03.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/installing-agent-progress-bar.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_1.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_2.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_3.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_4.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_5.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_6.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_7.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/images/restoration_8.png
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/meta.yaml
Labels: Guide creation

#7592 VSCP first steps guide - Fixing typos
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.de-de.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-asia.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-au.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-gb.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-ie.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-sg.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.en-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.es-es.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.es-us.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.fr-ca.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.fr-fr.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.it-it.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.pl-pl.md
  pages/storage_and_backup/backup_and_disaster_recovery_solutions/veeam/VSPC_first_steps/guide.pt-pt.md
Labels: Minor update

#7595 [MKS] - Migrate load balancer fix
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/migrate-loadbalancer-iolb-to-octavia/guide.pt-pt.md
Labels: FIX

#7593 BYOIP - Campus to Regions + WHOIS Record
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.de-de.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-asia.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-au.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-ca.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-gb.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-ie.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-sg.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.en-us.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.es-es.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.es-us.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.fr-ca.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.fr-fr.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.it-it.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.pl-pl.md
  pages/network/bring_your_own_ip/bring-your-own-IP/guide.pt-pt.md
Labels: Minor update
