Repository ovh/docs, pull requests merged in 2025-05, with the labels that each got.

#7818 Format fixes on several pages
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/images/network-creation.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/premium/images/network-creation01.png
Labels: FIX

#7807 Update PostgreSQL extension list
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.de-de.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.en-au.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.en-us.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.es-es.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.es-us.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.it-it.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/postgresql_02_extensions/guide.pt-pt.md
Labels: Minor update

#7703 Feat(object storage): add OVHcloud provider to create bucket
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.de-de.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.en-asia.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.en-au.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.en-ca.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.en-gb.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.en-ie.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.en-sg.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.en-us.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.es-es.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.es-us.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.fr-ca.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.fr-fr.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.it-it.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.pl-pl.md
  pages/manage_and_operate/terraform/terraform-at-ovhcloud/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_terraform/images/get-service-name.png
Labels: Minor update

#7787 feat(block storage): create 3az guide for classic 3AZ type
  pages/index.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.de-de.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.en-asia.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.en-au.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.en-ca.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.en-gb.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.en-ie.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.en-sg.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.en-us.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.es-es.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.es-us.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.fr-ca.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.fr-fr.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.it-it.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.pl-pl.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/guide.pt-pt.md
  pages/public_cloud/compute/classic_block_multi_az_limitations/images/create_volume_type.png
  pages/public_cloud/compute/classic_block_multi_az_limitations/meta.yml
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.de-de.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-asia.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-au.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-ca.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-gb.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-ie.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-sg.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-us.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.es-es.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.es-us.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.fr-ca.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.fr-fr.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.it-it.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.pl-pl.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.pt-pt.md
Labels: Guide creation

#7825 Fixes on various pages
  pages/public_cloud/compute/classic_block_multi_az_limitations/meta.yaml
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/images/mxplan-starter-legacy-step4.png
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/images/mxplan-starter-new-step4.png
Labels: FIX

#7823 VCD Migration Guide - Fixing dates in french guides
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
Labels: FIX, Priority: Urgent

#7826 Fixing Guide - VCD migration update (error in table)
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_migration_use-cases/guide.pt-pt.md
Labels: FIX, Priority: Urgent

#7827 fix(end-of-life-for-personal-installation-templates): wording
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.fr-fr.md
Labels: FIX

#7828 Feat( ceph guide): update the ceph pool guide
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.de-de.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.en-asia.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.en-au.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.en-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.en-gb.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.en-ie.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.en-sg.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.en-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.es-es.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.es-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.fr-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.fr-fr.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.it-it.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.pl-pl.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/guide.pt-pt.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/images/ceph-add-pool-1.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/images/create_a_pool_1.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/images/create_a_pool_2.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/images/create_a_pool_3.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_a_pool/images/create_a_pool_4.png
Labels: Minor update

#7830 Fixes and improvements on several pages
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_an_ip_acl/guide.fr-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_create_an_ip_acl/guide.fr-fr.md
  pages/web_cloud/web_hosting/diagnostic_slownesses/guide.pl-pl.md
Labels: FIX, Minor update

#7820 Feat(managed kubernetes): merge hello world guides
  links/console
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/datacenters-nodes-storage-flavors/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kube-api-01.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kube-api-02.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kube-api-03.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kube-api-04.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kube-api-05.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kube-api-06.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kube-api-07.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/images/kubernetes-quickstart-api-ovh-com-001.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world-ovh-api/meta.yaml
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/deploying-hello-world/guide.pt-pt.md
Labels: Minor update, Guides removal

#7842 Updating VCD limitations guide - Jira: SK-2084
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pt-pt.md
Labels: FIX

#7845 Nutanix - HYCU Backup - Fixing ISCSI IP configuration step
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.de-de.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-gb.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-ie.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.en-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.es-es.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.es-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.pl-pl.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/guide.pt-pt.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/40-hycu-backup/images/00-configureiscsi04b.png
Labels: FIX

#7855 Add DE versions 2 Network Services tutorials
  pages/public_cloud/public_cloud_network_services/getting-started-04-configure-additional-ip-to-instance/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/images/old_dns-vrack.png
  pages/web_cloud/web_hosting/configure_your_web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/handle_sftp_connexion_vscode/guide.de-de.md
Labels: Translations ONLY

#7857 Object Storage - S3 Location - Infrequent access ETA update
  pages/storage_and_backup/object_storage/s3_location/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_location/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_location/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_location/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_location/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_location/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_location/guide.pt-pt.md
Labels: Minor update

#7853 feat(ceph service): new guide about how to grow service
  pages/index.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.de-de.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.en-asia.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.en-au.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.en-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.en-gb.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.en-ie.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.en-sg.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.en-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.es-es.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.es-us.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.fr-ca.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.fr-fr.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.it-it.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.pl-pl.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/guide.pt-pt.md
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/images/ceph_details.png
  pages/storage_and_backup/block_storage/cloud_disk_array/ceph_grow_with_api/meta.yaml
Labels: Guide creation

#7862 Fixes on translations and images
  pages/manage_and_operate/api/first-steps/guide.pl-pl.md
  pages/web_cloud/domains/autorenew_domain_name/guide.pl-pl.md
  pages/web_cloud/domains/autorenew_domain_name/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_dkim/guide.pl-pl.md
Labels: FIX

#7809 KevS-SK2092-Update-GLUE-for-DomainDNS
  pages/web_cloud/domains/dns_server_edit/guide.it-it.md
  pages/web_cloud/domains/glue_registry/guide.de-de.md
  pages/web_cloud/domains/glue_registry/guide.en-asia.md
  pages/web_cloud/domains/glue_registry/guide.en-au.md
  pages/web_cloud/domains/glue_registry/guide.en-ca.md
  pages/web_cloud/domains/glue_registry/guide.en-gb.md
  pages/web_cloud/domains/glue_registry/guide.en-ie.md
  pages/web_cloud/domains/glue_registry/guide.en-sg.md
  pages/web_cloud/domains/glue_registry/guide.en-us.md
  pages/web_cloud/domains/glue_registry/guide.es-es.md
  pages/web_cloud/domains/glue_registry/guide.es-us.md
  pages/web_cloud/domains/glue_registry/guide.fr-ca.md
  pages/web_cloud/domains/glue_registry/guide.fr-fr.md
  pages/web_cloud/domains/glue_registry/guide.it-it.md
  pages/web_cloud/domains/glue_registry/guide.pl-pl.md
  pages/web_cloud/domains/glue_registry/guide.pt-pt.md
Labels: Translations

#7847 KevS-SK2119-Creation-How-to-verify-informations-of-contact-owner-for-DomainDNS
  pages/assets/screens/control_panel/product-selection/web-cloud/ongoing-operations.png
  pages/assets/screens/control_panel/product-selection/web-cloud/ongoing-operations/contact-correction-relaunch-operation.png
  pages/assets/screens/control_panel/product-selection/web-cloud/ongoing-operations/contact-correction.png
  pages/index.md
  pages/web_cloud/domains/domain_verify_holder/guide.fr-ca.md
  pages/web_cloud/domains/domain_verify_holder/guide.fr-fr.md
  pages/web_cloud/domains/domain_verify_holder/meta.yaml
Labels: Guide creation

#7872 [PNRv2] - Upd asset images Control Panel
  pages/assets/screens/control_panel/product-selection/public-cloud/tpl-pci-en.png
  pages/assets/screens/control_panel/product-selection/right-column/contact-management.png
  pages/assets/screens/control_panel/product-selection/right-column/invoices.png
  pages/assets/screens/control_panel/product-selection/right-column/products-services-fr.png
  pages/assets/screens/control_panel/product-selection/right-column/products-services.png
  pages/assets/screens/control_panel/product-selection/right-column/right-menu-my-solutions-and-services.png
  pages/assets/screens/control_panel/product-selection/right-column/service_emails.png
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/import-keys-control-panel/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_edit/guide.de-de.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.de-de.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.en-asia.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.en-au.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.en-ca.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.en-gb.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.en-ie.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.en-sg.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.en-us.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.es-es.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.es-us.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.fr-ca.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.fr-fr.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.it-it.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.pl-pl.md
  pages/web_cloud/web_hosting/diagnostic-website-not-accessible/guide.pt-pt.md
Labels: Minor update

#7861 KevS-SK2128-LLMCB-81-Creation-How-to-find-Cluster-and-filerz-for-WebHosting
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/filer.png
  pages/index.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.fr-ca.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.fr-fr.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/meta.yaml
Labels: Guide creation

#7851 SK-2093-WEB-Emails-Zimbra-first_step-alias_redirection-ALL
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_autoreply01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_redirection03.png
Labels: Translations ONLY

#7879 fix(end-of-life-for-personal-installation-templates): update email date
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/end-of-life-for-personal-installation-templates/guide.pt-pt.md
Labels: FIX

#7886 Guide Update - Managed Bare Metal - Technical capabilities - SK 2142
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.de-de.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.en-asia.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.en-au.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.en-ca.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.en-gb.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.en-ie.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.en-sg.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.en-us.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.es-es.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.es-us.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.fr-ca.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.fr-fr.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.it-it.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.pl-pl.md
  pages/bare_metal_cloud/managed_bare_metal/service-limits/guide.pt-pt.md
Labels: Priority: Urgent

#7865 SK-2066-WEB-Emails-MXplan-Getting_Started-Translation_ALL
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_generalities/images/mxplan-creation-new-step3-roundcube.png
Labels: Translations ONLY

#7899 Guide Update - Nutanix Scale IN/OUT - Jira SK-2118
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.de-de.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-gb.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-ie.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.es-es.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.es-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.pl-pl.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.pt-pt.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode01.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode02.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode03.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode04.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode05.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode06.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode07.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode08.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode09.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/AddNode10.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/CheckBeforeAdd01.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/CheckBeforeAdd02.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/CheckBeforeAdd03.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/ClusterDetailAfterFromDashboard.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/ClusterDetailBFromDashboard.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/DisplayDashboardAfter.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/DisplayDashboardBefore.PNG
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/adding-nodes-03.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/adding-nodes-04.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/adding-nodes-05.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/control-panel.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/install-os-01.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/install-os-02.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/install-os-03.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/manage-nodes.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/powerdown-nodes-01.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/powerdown-nodes-02.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/powerdown-nodes-03.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/remove-nodes-01.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/remove-nodes-02.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/remove-nodes-03.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/remove-nodes-04.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/scaleup1.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/scaleup2.png
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/images/scaleup3.png
  pages/index.md
Labels: Priority: High

#7897 KevS-SK2021-Update-First-steps-for-CloudWeb
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.de-de.md
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.en-gb.md
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.en-ie.md
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.es-es.md
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.fr-fr.md
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.it-it.md
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.pl-pl.md
  pages/web_cloud/web_hosting/getting_started_cloud_web/guide.pt-pt.md
Labels: Minor update, Translations

#7902 Fixes on several pages
  pages/account_and_service_management/managing_billing_payments_and_services/faq-billing/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.de-de.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-gb.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-ie.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.es-es.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.es-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.pl-pl.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.pt-pt.md
Labels: FIX

#7903 Nutanix - Scale in/out - API fixes
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.de-de.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-gb.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-ie.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.en-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.es-es.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.es-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.pl-pl.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/33-add-node/guide.pt-pt.md
Labels: FIX

#7908 Fixes - Public Cloud
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.es-es.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.es-us.md
  pages/public_cloud/compute/configuring_additional_ssh_keys/guide.pl-pl.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-es.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.it-it.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pt-pt.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.de-de.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.es-es.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.es-us.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.it-it.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.pl-pl.md
  pages/public_cloud/compute/create_instance_in_horizon/guide.pt-pt.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.pl-pl.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.de-de.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.en-asia.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.en-au.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.en-ca.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.en-gb.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.en-ie.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.en-sg.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.en-us.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.es-es.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.es-us.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.fr-ca.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.fr-fr.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.it-it.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.pl-pl.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/guide.pt-pt.md
  pages/public_cloud/compute/first_steps_with_public_cloud_instance/images/compute-2025.png
  pages/public_cloud/public_cloud_cross_functional/analyze_billing/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/tutorial-stormshield_network_security_vrack/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/tutorial-ubika_vrack/guide.pt-pt.md
Labels: Do not merge yet

#7915 Duplicating links and banners for India
  links/storage/cloud-disk-array
  templates/banners/training-certification/banner.en-in.html
Labels: Minor update

#7883 KevS-SK2128-LLMCB-81-Creation-How-to-find-Cluster-and-filerz-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.es-es.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.de-de.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.en-gb.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.es-es.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.fr-ca.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.fr-fr.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.it-it.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.pl-pl.md
  pages/web_cloud/web_hosting/how_to_know_cluster_and_filer/guide.pt-pt.md
Labels: Translations ONLY

#7884 SK-1976-WEB-Emails-FAQ-update-ALL
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-emails/images/zimbra01.png
Labels: Translations ONLY
