Repository ovh/docs, pull requests merged in 2025-08, with the labels that each got.

#8219 [AI Deploy] - New guide - Deploy FLUX models with ComfyUI
  pages/index.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.de-de.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.en-au.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.en-us.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.es-es.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.es-us.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.it-it.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/images/flux-ai-deploy-demo.gif
  pages/public_cloud/ai_machine_learning/deploy_tuto_19_flux/meta.yaml
Labels: Guide creation

#8256 SK-2091-WEB-Email_Pro-Config_Outlook-iOS-ALL-[QuickFix]
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.pt-pt.md
Labels: FIX

#8241 SK-1693-WEB-Emails-alloffers-Alias_Redirections-TRANS_EN-DE-ES-IT-PT-PL
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-asia.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-au.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-ca.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-sg.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.en-us.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.es-us.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.fr-ca.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/common_email_features/feature_redirections/guide.pt-pt.md
Labels: Translations ONLY

#8262 Update guide.fr-fr.md - vLCM usage with Zerto option
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_update_esxi_vlcm/images/vlcm_step2.png
Labels: Update request

#8276 Guide creation - VCD declare public gateway
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-01.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-02.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-03.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-04.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-05.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-06.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-07.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/images/vcd-declare-public-gateway-08.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_declare_public_gateway/meta.yaml
  pages/index.md
Labels: Guide creation, Priority: Urgent

#8287 SK-2257-Emails-all_offers-change_password-Zimbra_update-DE-EN_ES_IT_PL_PT
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.pt-pt.md
Labels: Translations ONLY

#8294 Quickfix-190825
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_change_password/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/troubleshooting/email_manage_quota/guide.pl-pl.md
Labels: FIX

#8303 KevS-SK2278-Update-Screens-IP-Geolocation-for-WebHosting-revamp-SSL-project
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/multisite.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/country-ip-selection.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/modify-a-domain.png
  pages/web_cloud/web_hosting/multisites_geolocation/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.en-ie.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_geolocation/guide.pt-pt.md
Labels: Minor update

#8305 Fixes
  pages/index.md
  pages/web_cloud/domains/dns_ips_update/guide.de-de.md
  pages/web_cloud/domains/dns_ips_update/guide.en-gb.md
  pages/web_cloud/domains/dns_ips_update/guide.es-es.md
  pages/web_cloud/domains/dns_ips_update/guide.it-it.md
  pages/web_cloud/domains/dns_ips_update/guide.pl-pl.md
  pages/web_cloud/domains/dns_ips_update/guide.pt-pt.md
  pages/web_cloud/domains/dns_ips_update/meta.yaml
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.en-asia.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.en-au.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.en-ca.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.en-gb.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.en-ie.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.en-sg.md
  pages/web_cloud/domains/transfer_incoming_generic_domain/guide.en-us.md
  pages/web_cloud/web_hosting/diagnostic_request_blocked/guide.en-gb.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.de-de.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-asia.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-au.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-gb.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-ie.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-sg.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.en-us.md
Labels: FIX

#8306 KevS-SK2279-Update-Screens-Application-firewall-for-WebHosting-revamp-SSL-project
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/firewall-enabled.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/modify-a-domain-enable-firewall-step-1.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/modify-domain-2.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/ongoing-tasks/firewall-planned.png
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-asia.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-au.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-ca.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-ie.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-sg.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.en-us.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.es-us.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_activating_application_firewall/guide.pt-pt.md
Labels: Minor update

#8295 Feat frversion landingzone
  pages/public_cloud/public_cloud_cross_functional/landing_zone_migration/guide.en-gb.md
  pages/public_cloud/public_cloud_cross_functional/landing_zone_migration/guide.fr-fr.md
Labels: Translations

#8274 KevS-SK2254-KFT-xls-lines-227-278-and-375-Full-Update-Diagnostic-uninstalled-page-for-WebHosting
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.de-de.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.en-asia.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.en-au.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.en-ca.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.en-gb.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.en-ie.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.en-sg.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.en-us.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.es-es.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.es-us.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.it-it.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.pl-pl.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.pt-pt.md
Labels: KFT / Issue, Translations

#7941 FB - Install N8N on a VPS
  pages/bare_metal_cloud/virtual_private_servers/install_n8n_on_vps/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/install_n8n_on_vps/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/install_n8n_on_vps/images/login_n8n.png
  pages/bare_metal_cloud/virtual_private_servers/install_n8n_on_vps/images/setup_n8n.png
  pages/bare_metal_cloud/virtual_private_servers/install_n8n_on_vps/meta.yaml
  pages/index.md
Labels: Guide creation

#8311 Delete mongo12
  pages/index.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/images/change-solution.png
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/images/choose-flavor.png
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/images/general-information.png
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/images/migration-complete.png
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/images/migration-in-progress.png
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/images/service-list.png
  pages/public_cloud/public_cloud_databases/mongodb_12_howto_migrate_to_production_or_advanced/meta.yaml
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.de-de.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-au.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.en-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-es.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.es-us.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.it-it.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/mongodb_16_automated_migration_new_offers/guide.pt-pt.md
Labels: Guides removal

#8316 KevS-SK2288-Update-screens-multisites-website-not-installed-for-WebHosting-revamp-SSL-project
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/find-ipv4-and-ipv6.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/multisite/tab.png
Labels: Minor update

#8321 VoIP FAQ - Updating the Softphone information
  pages/web_cloud/phone_and_fax/voip/faq-voip/guide.fr-fr.md
Labels: Minor update
