Repository ovh/docs, pull requests merged in 2025-06, with the labels that each got.

#7788 feat(block storage multi attach): add informations
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.de-de.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-asia.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-au.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-gb.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ie.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-sg.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-es.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-fr.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.it-it.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pt-pt.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.de-de.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-asia.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-au.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-ca.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-gb.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-ie.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-sg.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.en-us.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.es-es.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.es-us.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.fr-ca.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.fr-fr.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.it-it.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.pl-pl.md
  pages/public_cloud/public_cloud_cross_functional/3az_ref_architecture/guide.pt-pt.md
Labels: Minor update

#7945 Links fixes on several pages
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/use_iam_with_vSphere/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_terraform/guide.pt-pt.md
Labels: FIX

#7946 fix(netbackup guide) update image name
  pages/storage_and_backup/object_storage/s3_cohesity_netbackup/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_cohesity_netbackup/guide.fr-fr.md
Labels: FIX

#7955 fix(aws warning): following update, warning removed
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.de-de.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-asia.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-au.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-ca.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-gb.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-ie.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-sg.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.en-us.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.es-es.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.es-us.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.fr-ca.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.fr-fr.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.it-it.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.pl-pl.md
  pages/public_cloud/compute/use_object_storage_terraform_backend_state/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_getting_started_with_object_storage/guide.pt-pt.md
Labels: Minor update

#7943 feat(s3 optimize perf guide): update guide to add upload not completed part
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_performance_optimization/guide.pt-pt.md
Labels: Minor update

#7963 Fixes on several pages
  pages/bare_metal_cloud/dedicated_servers/configuring-an-ip-block-in-a-vrack/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/responsibility-model/meta.yaml
  pages/storage_and_backup/object_storage/s3_s3_compliancy/guide.en-gb.md
Labels: FIX

#7967 Index fixes
  pages/index.md
Labels: FIX

#7969 Fixes on several pages
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/meta.yaml
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/meta.yaml
Labels: FIX

#7971 AI POC - SSH guide - Videos URLs update
  pages/account_and_service_management/account_information/ssh-key-creation/guide.de-de.md
  pages/account_and_service_management/account_information/ssh-key-creation/guide.en-gb.md
  pages/account_and_service_management/account_information/ssh-key-creation/guide.es-es.md
  pages/account_and_service_management/account_information/ssh-key-creation/guide.fr-fr.md
  pages/account_and_service_management/account_information/ssh-key-creation/guide.it-it.md
  pages/account_and_service_management/account_information/ssh-key-creation/guide.pl-pl.md
  pages/account_and_service_management/account_information/ssh-key-creation/guide.pt-pt.md
Labels: FIX

#7975 Guide Update - Nutanix Veam backup
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.de-de.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.en-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.en-gb.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.en-ie.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.en-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.es-es.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.es-us.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.fr-ca.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.fr-fr.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.it-it.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.pl-pl.md
  pages/hosted_private_cloud/nutanix_on_ovhcloud/41-nutanix-veeam-backup/guide.pt-pt.md
Labels: Priority: Low

#7980 KevS-SK2173-EOL-Net2FTP-add-banner-information-for-filezilla-and-cyberduck-guide
  pages/web_cloud/web_hosting/ftp_connection/guide.de-de.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-asia.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-au.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-ca.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-gb.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-ie.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-sg.md
  pages/web_cloud/web_hosting/ftp_connection/guide.en-us.md
  pages/web_cloud/web_hosting/ftp_connection/guide.es-es.md
  pages/web_cloud/web_hosting/ftp_connection/guide.es-us.md
  pages/web_cloud/web_hosting/ftp_connection/guide.fr-ca.md
  pages/web_cloud/web_hosting/ftp_connection/guide.fr-fr.md
  pages/web_cloud/web_hosting/ftp_connection/guide.it-it.md
  pages/web_cloud/web_hosting/ftp_connection/guide.pl-pl.md
  pages/web_cloud/web_hosting/ftp_connection/guide.pt-pt.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.de-de.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.en-asia.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.en-au.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.en-ca.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.en-gb.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.en-ie.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.en-sg.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.en-us.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.es-es.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.es-us.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.fr-ca.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.fr-fr.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.it-it.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.pl-pl.md
  pages/web_cloud/web_hosting/ftp_cyberduck_user_guide_on_mac/guide.pt-pt.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.de-de.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.en-asia.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.en-au.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.en-ca.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.en-gb.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.en-ie.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.en-sg.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.en-us.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.es-es.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.es-us.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.fr-ca.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.fr-fr.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.it-it.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.pl-pl.md
  pages/web_cloud/web_hosting/ftp_filezilla_user_guide/guide.pt-pt.md
Labels: Minor update, Priority: Urgent

#7984 AI Endpoints - Getting started - Keys creation information
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_01_getting_started/guide.pt-pt.md
Labels: Minor update

#7979 FR & EN new guide on Object Storage ecosystem - compatibility matrix with 3rd-party applications
  pages/index.md
  pages/storage_and_backup/object_storage/s3_ecosystem/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_ecosystem/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_ecosystem/meta.yaml
Labels: Guide creation

#7876 feat(databases): new guide about comparison of the databases deployment
  pages/index.md
  pages/public_cloud/public_cloud_databases/databases_18_regions_comparison/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/databases_18_regions_comparison/meta.yaml
Labels: Guide creation

#7974 Hb pol reversibility for product « Managed Relational Database »
  pages/account_and_service_management/reversibility/06-ddb_mongo/guide.en-gb.md
  pages/account_and_service_management/reversibility/06-ddb_mongo/guide.fr-fr.md
  pages/account_and_service_management/reversibility/06-ddb_mongo/meta.yaml
  pages/account_and_service_management/reversibility/07-rdb_mysql_postgre/guide.en-gb.md
  pages/account_and_service_management/reversibility/07-rdb_mysql_postgre/guide.fr-fr.md
  pages/account_and_service_management/reversibility/07-rdb_mysql_postgre/meta.yaml
  pages/index.md
Labels: Guide creation

#7998 Linkfixes
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/starting_with_a_vps/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/upsize_vps_partition/guide.pt-pt.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.de-de.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-asia.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-au.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-ca.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-gb.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-ie.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-sg.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-us.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.es-es.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.es-us.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.fr-ca.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.fr-fr.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.it-it.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.pl-pl.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.pt-pt.md
Labels: FIX

#7981 Hb reversibility storage for 3 products : file storage , cold storage and 3az object storage
  pages/account_and_service_management/reversibility/08-file-storage-reversibility-policy/guide.en-gb.md
  pages/account_and_service_management/reversibility/08-file-storage-reversibility-policy/guide.fr-fr.md
  pages/account_and_service_management/reversibility/08-file-storage-reversibility-policy/meta.yaml
  pages/account_and_service_management/reversibility/09-cold-storage-reversibility-policy/guide.en-gb.md
  pages/account_and_service_management/reversibility/09-cold-storage-reversibility-policy/guide.fr-fr.md
  pages/account_and_service_management/reversibility/09-cold-storage-reversibility-policy/meta.yaml
  pages/account_and_service_management/reversibility/10-object-storage-3az-reversibility-policy/guide.en-gb.md
  pages/account_and_service_management/reversibility/10-object-storage-3az-reversibility-policy/guide.fr-fr.md
  pages/account_and_service_management/reversibility/10-object-storage-3az-reversibility-policy/meta.yaml
  pages/index.md
Labels: Guide creation

#8000 [AI Endpoints] - Move updated features from planned to available
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_02_capabilities/guide.pt-pt.md
Labels: Minor update

#8008 Orchestration Reversibility Policy - Adding guide into MRS
  pages/index.md
Labels: Minor update

#7995 OVHcloud Load Balancer - TCP / HTTP / HTTPS Logs forwarding
  pages/index.md
  pages/network/load_balancer/use_api_logs_2_customers/guide.en-gb.md
  pages/network/load_balancer/use_api_logs_2_customers/guide.fr-fr.md
  pages/network/load_balancer/use_api_logs_2_customers/meta.yaml
Labels: Guide creation

#8009 Solidigm SSD Firmware update - Product range fix
  pages/bare_metal_cloud/dedicated_servers/solidigm_d7-p5520_fw_update/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/solidigm_d7-p5520_fw_update/guide.fr-fr.md
Labels: FIX

#7953 Feat(iaas): new guide about IAAS migration
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/public_cloud/public_cloud_cross_functional/iaas-migration-steps/guide.en-gb.md
  pages/public_cloud/public_cloud_cross_functional/iaas-migration-steps/guide.fr-fr.md
  pages/public_cloud/public_cloud_cross_functional/iaas-migration-steps/images/schema_migration.png
  pages/public_cloud/public_cloud_cross_functional/iaas-migration-steps/meta.yaml
Labels: Guide creation

#8015 Public Cloud - IaaS migration - Deleting plaeholder line
  pages/public_cloud/public_cloud_cross_functional/iaas-migration-steps/guide.en-gb.md
  pages/public_cloud/public_cloud_cross_functional/iaas-migration-steps/guide.fr-fr.md
Labels: FIX

#8002 KevS-SK2184-LLMCB-3-How-to-enable-DNS-Anycast-for-DomainDNS
  links/web/domains-options-anycast
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/order-anycast-dns-step-2.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/dns-servers/order-anycast-dns.png
  pages/index.md
  pages/web_cloud/domains/dns_anycast_enable/guide.de-de.md
  pages/web_cloud/domains/dns_anycast_enable/guide.en-gb.md
  pages/web_cloud/domains/dns_anycast_enable/guide.es-es.md
  pages/web_cloud/domains/dns_anycast_enable/guide.fr-fr.md
  pages/web_cloud/domains/dns_anycast_enable/guide.it-it.md
  pages/web_cloud/domains/dns_anycast_enable/guide.pl-pl.md
  pages/web_cloud/domains/dns_anycast_enable/guide.pt-pt.md
  pages/web_cloud/domains/dns_anycast_enable/meta.yaml
Labels: Guide creation, Translations

#8012 KevS-SK1917-Carbon-footprint-TRANSLATIONS
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.de-de.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-asia.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-au.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-gb.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-ie.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-sg.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.en-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.es-es.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.es-us.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.fr-ca.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.fr-fr.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.it-it.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.pl-pl.md
  pages/account_and_service_management/managing_billing_payments_and_services/carbon_footprint/guide.pt-pt.md
Labels: Translations ONLY

#8031 Quantum computing: Fix typo
  pages/public_cloud/quantum_computing/getting-started-emulators/guide.en-gb.md
Labels: FIX

#8018 Hb db reversbility policies for MDB et OBS products (databases)
  links/public-cloud/dashboards
  pages/account_and_service_management/reversibility/14-reversibility-mdb/guide.en-gb.md
  pages/account_and_service_management/reversibility/14-reversibility-mdb/guide.fr-fr.md
  pages/account_and_service_management/reversibility/14-reversibility-mdb/meta.yaml
  pages/account_and_service_management/reversibility/15-reversibility-obs-data-visualization/guide.en-gb.md
  pages/account_and_service_management/reversibility/15-reversibility-obs-data-visualization/guide.fr-fr.md
  pages/account_and_service_management/reversibility/15-reversibility-obs-data-visualization/meta.yaml
  pages/index.md
Labels: Guide creation

#7997 KevS-SK2183-LLMCB-37-How-to-add-TXT-record-into-DNS-zone
  pages/index.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/guide.de-de.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/guide.es-es.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/guide.it-it.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/guide.pt-pt.md
  pages/web_cloud/domains/dns_zone_txt_record_creation/meta.yaml
Labels: Guide creation, Translations

#8027 KevS-SK2191-LLMCB201-Create-How-to-modify-rights-for-users-for-WebCloudDatabases
  pages/assets/screens/control_panel/product-selection/web-cloud/web-cloud-databases/users-and-rights.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-cloud-databases/users-and-rights/changing-user-rights-db-alone.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-cloud-databases/users-and-rights/manage-rights-user-alone.png
  pages/index.md
  pages/web_cloud/web_cloud_databases/create-db-and-user-on-db-server/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/guide.de-de.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/guide.es-es.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/guide.fr-fr.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/guide.it-it.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/guide.pt-pt.md
  pages/web_cloud/web_cloud_databases/modify_rights_for_users/meta.yaml
Labels: Guide creation, Translations

#8057 Translation guides for SD - Vatious fixes - Part 1
  pages/bare_metal_cloud/dedicated_servers/ipxe-scripts/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/ipxe-scripts/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/migrate_a_server_to_another/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/migrate_a_server_to_another/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/migrate_a_server_to_another/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/migrate_a_server_to_another/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/migrate_a_server_to_another/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/migrate_a_server_to_another/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/move-failover-ip/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_ipaliasing/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.pt-pt.md
Labels: FIX

#8058 FIX - Introduction to service logs
  pages/manage_and_operate/observability/logs_data_platform/introduction_to_services_logs/guide.en-gb.md
Labels: FIX

#8016 New guide - Using Networking Tools Available to OVHcloud Customers
  links/documentation
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/network/network_tools/guide.en-gb.md
  pages/network/network_tools/guide.fr-fr.md
  pages/network/network_tools/images/networking_tools01_.png
  pages/network/network_tools/images/networking_tools02_.png
  pages/network/network_tools/images/networking_tools03_.png
  pages/network/network_tools/images/networking_tools04_.png
  pages/network/network_tools/images/networking_tools05_.png
  pages/network/network_tools/images/networktools1.png
  pages/network/network_tools/images/networktools2.png
  pages/network/network_tools/images/networktools3.png
  pages/network/network_tools/images/networktools4.png
  pages/network/network_tools/meta.yaml
Labels: Guide creation

#8076 KevS-Updates-How-to-add-CNAME-for-DOmainDNS-revamping-and-optiomisations
  pages/web_cloud/domains/dns_zone_cname_record_creation/guide.de-de.md
  pages/web_cloud/domains/dns_zone_cname_record_creation/guide.en-gb.md
  pages/web_cloud/domains/dns_zone_cname_record_creation/guide.es-es.md
  pages/web_cloud/domains/dns_zone_cname_record_creation/guide.fr-fr.md
  pages/web_cloud/domains/dns_zone_cname_record_creation/guide.it-it.md
  pages/web_cloud/domains/dns_zone_cname_record_creation/guide.pl-pl.md
  pages/web_cloud/domains/dns_zone_cname_record_creation/guide.pt-pt.md
Labels: Minor update, Translations

#8090 Quickfix_270625
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_mail_app_ios/meta.yaml
Labels: FIX

#8091 Quickfix_270625-2
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/meta.yaml
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/faq-zimbra/meta.yaml
Labels: FIX

#8092 Quickfix_270625_3
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_mail_macos/meta.yaml
Labels: FIX

#8077 Hb reversibility policies BM 3AZ and Object storage
  pages/account_and_service_management/reversibility/16-object-storage-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/16-object-storage-reversibility/guide.fr-fr.md
  pages/account_and_service_management/reversibility/16-object-storage-reversibility/meta.yaml
  pages/account_and_service_management/reversibility/17-dedicated-servers-3AZ-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/17-dedicated-servers-3AZ-reversibility/guide.fr-fr.md
  pages/account_and_service_management/reversibility/17-dedicated-servers-3AZ-reversibility/meta.yaml
  pages/index.md
Labels: Guide creation

#8006 feat(block storage): improve the storage block creation guide
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.de-de.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-asia.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-au.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-gb.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ie.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-sg.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-es.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-fr.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.it-it.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pt-pt.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/images/horizon_create_volume.png
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/images/horizon_create_volume_02.png
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/images/horizon_manage_attachments.png
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/images/horizon_manage_attachments_display.png
Labels: Minor update, Translations

#8099 Link fix on Bare Metal reversibility policy
  pages/account_and_service_management/reversibility/17-dedicated-servers-3AZ-reversibility/guide.en-gb.md
  pages/account_and_service_management/reversibility/17-dedicated-servers-3AZ-reversibility/guide.fr-fr.md
Labels: FIX

#8101 Public Cloud Storage - Missing DE translation + Ref Category update
  pages/index-translations.de.yaml
  pages/storage_and_backup/object_storage/s3_choosing_the_right_storage_class_for_your_needs/meta.yaml
Labels: FIX

#8089 Bare Metal Servers - Resource tags
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/add_a_tag.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/assign_tag.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/assign_tag_populated.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/general_information.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/remove_tag.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/tag_added.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/tag_list_empty.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/tag_list_remove.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/images/tag_list_with_example.png
  pages/bare_metal_cloud/dedicated_servers/resource-tag-assign/meta.yml
  pages/index.md
Labels: Guide creation
