Repository ovh/docs, pull requests merged in 2025-01, with the labels that each got.

#7355 vROps-minor fixes
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_introduction/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.pt-pt.md
Labels: FIX

#7356 EN-LDP related-minor fixes
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_haproxy/guide.pt-pt.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.de-de.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.en-asia.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.en-au.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.en-ca.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.en-gb.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.en-ie.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.en-sg.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.en-us.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.es-es.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.es-us.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.fr-ca.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.fr-fr.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.it-it.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.pl-pl.md
  pages/manage_and_operate/observability/logs_data_platform/usecase_twitter/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/technical-resources-05-lb_logs_2_customers/guide.pt-pt.md
Labels: FIX

#7359 Fixes
  pages/bare_metal_cloud/dedicated_servers/firewall-Linux-iptable/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/network_virtual_mac/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/firewall-Linux-iptable/guide.de-de.md
  pages/public_cloud/compute/managing_tokens/guide.de-de.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_clone_volume/guide.de-de.md
  pages/storage_and_backup/file_storage/enterprise_file_storage/netapp_control_panel/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_outlook_app_android_ios/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/mx_plan/email_zimbra/guide.de-de.md
  pages/web_cloud/web_hosting/activate-email-hosting/guide.de-de.md
  pages/web_cloud/web_hosting/mail_function_script_records/guide.de-de.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.de-de.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-gb.md
Labels: FIX

#7361 Public Cloud Network Services - Gateway - FR links fix
  pages/public_cloud/public_cloud_network_services/getting-started-02-create-private-network-gateway/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-02-create-private-network-gateway/guide.fr-fr.md
Labels: FIX

#7364 Properly hide temporary credentials
  pages/public_cloud/public_cloud_databases/mongodb_22_benchmark/images/YCSBLoad.png
  pages/public_cloud/public_cloud_databases/mongodb_22_benchmark/images/YCSBrun.png
Labels: FIX

#7367 MongoDB - Format and index fixes
  pages/index.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/mongodb_01_concept_capabilities/guide.en-sg.md
Labels: FIX

#7362 Feat(custom gateway k8S ): add TF example
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/vrack-k8s-custom-gateway/guide.pt-pt.md
Labels: FIX

#7366 fix(cassandra versions): update eol
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.de-de.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-au.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-us.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.es-es.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.es-us.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.it-it.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.pt-pt.md
Labels: FIX

#7307 Creating MKS x EFS documentation
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/images/create-efs-volume.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/images/manage-efs-volume-access-ip.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/images/manage-efs-volume-access.png
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/images/manage-efs-volume-acl-list.png
Labels: Guide creation

#7370 Fix - MKS/EFS - Creating missing meta.yaml file
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/meta.yaml
Labels: FIX

#7348 fix(cassandra/opens): update backup retention
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.de-de.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-au.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.en-us.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.es-es.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.es-us.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.it-it.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/cassandra_01_capabilities/guide.pt-pt.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.de-de.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.en-asia.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.en-au.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.en-ca.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.en-ie.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.en-sg.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.en-us.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.es-es.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.es-us.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.fr-ca.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.fr-fr.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.it-it.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.pl-pl.md
  pages/public_cloud/public_cloud_databases/opensearch_01_capabilities/guide.pt-pt.md
Labels: FIX

#7365 delete(vps changelog): delete vps changelog guide and ref
  pages/index.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.de-de.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.en-asia.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.en-au.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.en-ca.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.en-gb.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.en-ie.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.en-sg.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.en-us.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.es-es.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.es-us.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.fr-ca.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.fr-fr.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.it-it.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.pl-pl.md
  pages/public_cloud/compute/00-essential-info-to-get-started-on-public-cloud/guide.pt-pt.md
  pages/public_cloud/compute/image_changelog/guide.de-de.md
  pages/public_cloud/compute/image_changelog/guide.en-asia.md
  pages/public_cloud/compute/image_changelog/guide.en-au.md
  pages/public_cloud/compute/image_changelog/guide.en-ca.md
  pages/public_cloud/compute/image_changelog/guide.en-gb.md
  pages/public_cloud/compute/image_changelog/guide.en-ie.md
  pages/public_cloud/compute/image_changelog/guide.en-sg.md
  pages/public_cloud/compute/image_changelog/guide.en-us.md
  pages/public_cloud/compute/image_changelog/guide.es-es.md
  pages/public_cloud/compute/image_changelog/guide.es-us.md
  pages/public_cloud/compute/image_changelog/guide.fr-ca.md
  pages/public_cloud/compute/image_changelog/guide.fr-fr.md
  pages/public_cloud/compute/image_changelog/guide.it-it.md
  pages/public_cloud/compute/image_changelog/guide.pl-pl.md
  pages/public_cloud/compute/image_changelog/guide.pt-pt.md
  pages/public_cloud/compute/image_changelog/meta.yaml
Labels: Guides removal

#7380 Test article - fixing the hidden flag
  pages/web_cloud/phone_and_fax/fax/test-article-snow/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/fax/test-article-snow/meta.yaml
Labels: BUG, FIX

#7383 Upd Auth keys BM
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/creating-ssh-keys-dedicated/meta.yaml
  pages/index.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.de-de.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-asia.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-au.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-ca.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-gb.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-ie.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-sg.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.en-us.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.es-es.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.es-us.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.fr-ca.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.fr-fr.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.it-it.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.pl-pl.md
  pages/public_cloud/compute/creating-ssh-keys-pci/guide.pt-pt.md
Labels: Translations

#7372 KevS-SK1874-Update-How-to-use-IAM-policies-from-your-control-panel
  pages/account_and_service_management/account_information/iam-policy-ui/guide.de-de.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-asia.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-au.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-ca.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-gb.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-ie.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-sg.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.en-us.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.es-es.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.es-us.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.fr-ca.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.fr-fr.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.it-it.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.pl-pl.md
  pages/account_and_service_management/account_information/iam-policy-ui/guide.pt-pt.md
  pages/assets/screens/control_panel/product-selection/right-column/identity-and-access-management-iam/tab-first-access.png
Labels: Minor update

#7377 feat(limit and capa): update and duplicate guides
  pages/index.md
  pages/public_cloud/data_analytics/analytics/information_05_capabilities/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/information_05_capabilities/meta.yaml
  pages/public_cloud/public_cloud_databases/information_05_capabilities/guide.en-gb.md
Labels: Guide creation

#7319 FB - How to migrate a website from a VPS to dedicated server or Public Cloud Instance
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/migrate-to-pci-or-dedicated-server/meta.yaml
  pages/index.md
Labels: Guide creation

#7387 MKS with EFS guide - date fix
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-multi-attach-persistent-volumes-with-ovh-efs/guide.pt-pt.md
Labels: FIX

#7390 ServiceNow troubleshoot - Updating test article
  pages/web_cloud/phone_and_fax/fax/test-article-snow/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-001-enabling-2fa.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-003-otp-choice.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-003-otp-code.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-004-u2f-choice.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/account-creation.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/account-type.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/code.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/nic-handle.png
Labels: BUG

#7241 Feat(object storage): create bucket lifecycle guide
  pages/index.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/meta.yaml
Labels: Guide creation

#7311 feat(deployment): create guide en & fr for the deployment modes
  pages/index.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.de-de.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-asia.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-au.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-ca.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-gb.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-ie.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-sg.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-us.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.es-es.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.es-us.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.fr-ca.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.fr-fr.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.it-it.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.pl-pl.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.pt-pt.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/meta.yaml
Labels: Guide creation

#7391 SK-1875-WEB-Emails-Zimbra-Configure_CalDV-FR
  pages/index.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-ios01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-ios02.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-ios03.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-ios04.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-macos01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-macos02.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-thunderbird01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-thunderbird02.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/images/zimbra-calendar-thunderbird03.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/zimbra_calendar_sync/meta.yaml
Labels: Guide creation

#7395 Guide improvement - Getting started with Load Balancer on Public Cloud
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.pt-pt.md
Labels: FIX

#7343 Guide Separation - Configuring the vRack on Public Cloud + New guide creation - Configuring the vRack on PCI via the Openstack API
  pages/index.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/images/addprojectvrack.png
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/images/ordering_vrack_2024.png
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/images/vrack2022-03.png
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/meta.yaml
Labels: Guide creation, FIX, Translations

#7396 Fixes for several pages
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-01-create-lb-service/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-fr.md
  pages/web_cloud/web_hosting/hosting_migrating_to_ovh/guide.pt-pt.md
Labels: FIX

#7376 feat(lifecycle): duplicate and refacto lifecycle guide
  pages/index.md
  pages/public_cloud/data_analytics/analytics/information_02_lifecycle_policy/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/information_02_lifecycle_policy/meta.yaml
  pages/public_cloud/public_cloud_databases/information_02_lifecycle_policy/guide.en-gb.md
  pages/public_cloud/public_cloud_databases/information_02_lifecycle_policy/guide.fr-fr.md
Labels: Guide creation

#7402 SK1863 - MKS - Forwarding audit logs to LDP - typo fix
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/forwarding-audit-logs-to-logs-data-platform/guide.pt-pt.md
Labels: FIX

#7388 Feat(database refacto): create info maintenance
  pages/index.md
  pages/public_cloud/data_analytics/analytics/information_06_maintenances/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/information_06_maintenances/images/maintenancesql.png
  pages/public_cloud/data_analytics/analytics/information_06_maintenances/images/maintenancesql2.png
  pages/public_cloud/data_analytics/analytics/information_06_maintenances/meta.yaml
Labels: Guide creation

#7398 Feat(database refacto): create guide getting started
  pages/index.md
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_01.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_02.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_03.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_04.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_05.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_06.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_07.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/images/getting_started_control_panel_08.png
  pages/public_cloud/data_analytics/analytics/analytics_getting_started/meta.yaml
Labels: Guide creation

#7399 Feat(database refacto): create general gettingstarted api guide
  pages/index.md
  pages/public_cloud/data_analytics/analytics/analytics_getting_started_api/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_getting_started_api/meta.yaml
Labels: Guide creation

#7408 Feat(database refacto): create disk full handling guide
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_full_disk_handling/meta.yaml
  pages/public_cloud/public_cloud_databases/databases_10_full_disk_handling/guide.en-gb.md
Labels: Guide creation

#7404 Feat(databse refacto): create troubleshooting guide
  pages/public_cloud/data_analytics/analytics/analytics_troubleshooting/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_troubleshooting/meta.yaml
Labels: Guide creation

#7403 Feat(database refacto): create advanced parameters guide
  pages/public_cloud/data_analytics/analytics/analytics_advanced_parameters/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_advanced_parameters/images/api_ui_00.png
  pages/public_cloud/data_analytics/analytics/analytics_advanced_parameters/images/api_ui_01.png
  pages/public_cloud/data_analytics/analytics/analytics_advanced_parameters/images/api_ui_02.png
  pages/public_cloud/data_analytics/analytics/analytics_advanced_parameters/images/api_ui_03.png
  pages/public_cloud/data_analytics/analytics/analytics_advanced_parameters/images/api_ui_04.png
  pages/public_cloud/data_analytics/analytics/analytics_advanced_parameters/meta.yaml
  pages/public_cloud/public_cloud_databases/databases_03_advanced_configuration/guide.en-gb.md
Labels: Guide creation

#7413 VMware - Pricing and Management of NSX Edges
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/meta.yaml
  pages/index.md
Labels: Guide creation

#7425 VMware - NSX pricing - Reverting EN on FR files + indentation fix
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/nsx_pricing/guide.pt-pt.md
Labels: FIX

#7418 [SK-1733] Proxmox + Broadcom BCM57502: explain how to fix slow downloads
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/proxmox-broadcom-slow-downloads/meta.yaml
  pages/index.md
Labels: Guide creation

#7414 Feat(database refacto): create resize storage guide
  pages/public_cloud/data_analytics/analytics/analytics_resize_cluster_storage/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_resize_cluster_storage/images/cluster-overview.png
  pages/public_cloud/data_analytics/analytics/analytics_resize_cluster_storage/images/edit-additional-storage.png
  pages/public_cloud/data_analytics/analytics/analytics_resize_cluster_storage/meta.yaml
Labels: Guide creation

#7420 feat(database refacto): create update cluster solution guide
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_plan/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_plan/images/cluster_overview.png
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_plan/images/plan_change_view.png
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_plan/meta.yaml
Labels: Guide creation

#7421 feat(database refacto): create setup logs forwarding guide
  pages/public_cloud/data_analytics/analytics/analytics_logs_to_customer/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_logs_to_customer/meta.yaml
Labels: Guide creation

#7417 Feat(database refacto): create update flavor guide
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/images/cluster_overview.png
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/images/flavor_change_view.png
  pages/public_cloud/data_analytics/analytics/analytics_update_cluster_flavor/meta.yaml
Labels: Guide creation

#7426 security spec for block storage
  links/support-business
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.de-de.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.en-asia.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.en-au.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.en-ca.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.en-gb.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.en-ie.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.en-sg.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.en-us.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.es-es.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.es-us.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.fr-ca.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.fr-fr.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.it-it.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.pl-pl.md
  pages/account_and_service_management/account_information/security-specification-block-storage/guide.pt-pt.md
  pages/account_and_service_management/account_information/security-specification-block-storage/meta.yaml
  pages/account_and_service_management/account_information/security-specification-pci/guide.en-gb.md
  pages/index.md
Labels: Guide creation

#7419 Guide creation - Upgrade/Downgrade the bandwidth on a dedicated server
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/images/bandwidth_01.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/images/bandwidth_02.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/images/bandwidth_02_1.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/images/bandwidth_03.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/images/bandwidth_03_1.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_api/meta.yaml
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/bandwidth_01.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_01.PNG
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_02.PNG
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_03.PNG
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_04.PNG
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_05.PNG
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/meta.yaml
  pages/index.md
Labels: Guide creation, Do not merge yet, Quality Check

#7438 Rename private_bandwidth_01.PNG to private_bandwidth_01.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_01.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_02.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_03.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_04.png
  pages/bare_metal_cloud/dedicated_servers/manage_bandwidth_vRack_api/images/private_bandwidth_05.png
Labels: FIX

#7442 Troubleshooting prod images issue - Test article
  pages/web_cloud/phone_and_fax/fax/test-article-snow/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-001-enabling-2fa.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-003-otp-choice.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-003-otp-code.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/2024-004-u2f-choice.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/account-creation.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/account-type.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/adresses_notifications.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/code.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/configuration-fax.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/entete_des_fax_emis.jpg
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/filtrage_menu.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/motdepassefax.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/nic-handle.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/options_de_notifications.jpg
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/options_generales.jpg
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/regles_filtrage.png
Labels: BUG

#7385 Creating : Modify sysctl parameters for specific usecases on MKS
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/configuring-sysctl-parameters-on-nodes/meta.yaml
Labels: Guide creation

#7397 feat(database refacto): add backup
  pages/index.md
  pages/public_cloud/data_analytics/analytics/information_07_automated_backups/guide.en-gb.md
  pages/public_cloud/data_analytics/analytics/information_07_automated_backups/meta.yaml
  pages/public_cloud/public_cloud_databases/databases_05_automated_backups/guide.en-gb.md
Labels: Guide creation

#7444 KevS-SK1886-KFT0023731-Create-How-to-detach-Web-Cloud-Databases-from-a-Web-hosting-plan
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/detach-my-web-cloud-databases.png
  pages/index.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.fr-ca.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.fr-fr.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/meta.yaml
Labels: Guide creation, KFT / Issue

#7449 Updating MKS Recommended External Resources guide
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/recommended-external-resources/guide.pt-pt.md
Labels: Minor update

#7407 fix(general guide deployment): update def
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.de-de.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-asia.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-au.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-ca.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-gb.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-ie.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-sg.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-us.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.es-es.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.es-us.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.fr-ca.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.fr-fr.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.it-it.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.pl-pl.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.pt-pt.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/images/1az_region_schema.png
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/images/3az_region_schema.png
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/images/localzone_schema.png
Labels: FIX

#7452 KevS-SK1886-KFT0023731-Create-How-to-detach-Web-Cloud-Databases-from-a-Web-hosting-plan-TRANSLATIONS
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.de-de.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.en-asia.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.en-au.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.en-ca.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.en-gb.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.en-ie.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.en-sg.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.en-us.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.es-es.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.es-us.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.it-it.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.pl-pl.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.pt-pt.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.de-de.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-asia.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-au.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-ca.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-gb.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-ie.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-sg.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.en-us.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.es-es.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.es-us.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.fr-ca.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.fr-fr.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.it-it.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.pl-pl.md
  pages/web_cloud/web_hosting/sql_overquota_database/guide.pt-pt.md
Labels: Translations ONLY, KFT / Issue

#7453 KevS-SK1889-Creation-How-to-install-an-SSL-on-a-VPS-TRANSLATIONS
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.pt-pt.md
Labels: Translations ONLY

#7456 KevS-1893-Update-Configure-IPv6-for-WebHosting
  pages/web_cloud/web_hosting/configure_ipv6/guide.fr-ca.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.fr-fr.md
Labels: Minor update

#7455 FB - Automating the deployment of your website on your VPS via GitLab CI/CD
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/deploy-website-gitlab-ci-cd/meta.yaml
  pages/index.md
Labels: Guide creation

#7461 Fixes on several guides
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-image/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/bring-your-own-linux/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/install-ssl-certificate/guide.pt-pt.md
  pages/web_cloud/web_cloud_databases/detach-from-web-hosting/guide.de-de.md
Labels: FIX

#7457 Managed Private Registry improvments
  pages/index.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_private_registry/creating-a-private-registry-with-pulumi/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/are-you-sure.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/connection-tested-ok.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/execution-status-success.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/execution-status.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/my-new-registry-01.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/my-new-registry-02.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/new-registry-endpoint-created.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/new-registry-endpoint.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/new-replication-rule.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/registries.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/replicate-button.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/replication-rule-created.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/replication-rule.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/replication-rule6.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/images/replications.png
  pages/public_cloud/containers_orchestration/managed_private_registry/eol-harbor-1.x/meta.yaml
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_private_registry/managed-private-registry-faq/guide.pt-pt.md
Labels: Guides removal

#7462 Test article for ServiceNow issue - update
  pages/web_cloud/phone_and_fax/fax/test-article-snow/guide.fr-fr.md
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/01campagne-fax2022.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/02campagne-fax.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/activer-desactiver-repondeur.jpg
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/configuration-repondeur.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/gestion-repondeur.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/mail2fax.png
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/messages.jpg
  pages/web_cloud/phone_and_fax/fax/test-article-snow/images/mot-de-passe-repondeur.jpg
Labels: BUG

#7463 Object Storage - Lifecycle rules - Guide removal
  pages/index.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/guide.pt-pt.md
  pages/storage_and_backup/object_storage/s3_bucket_lifecycle/meta.yaml
Labels: Guides removal

#7464 KevS-1893-Update-Configure-IPv6-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/configure_ipv6/guide.de-de.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.en-asia.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.en-au.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.en-ca.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.en-gb.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.en-ie.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.en-sg.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.en-us.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.es-es.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.es-us.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.fr-ca.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.fr-fr.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.it-it.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.pl-pl.md
  pages/web_cloud/web_hosting/configure_ipv6/guide.pt-pt.md
Labels: Translations ONLY

#7466 KevS-SK1897-Update-List-of-IP-adresses-for-WebHosting
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/ftp-ssh/find-cluster-ftp-ssh.png
  pages/assets/screens/control_panel/product-selection/web-cloud/web-hosting/general-information/ftp-ssh.png
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.fr-ca.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.fr-fr.md
Labels: Minor update

#7451 WEB-Emails-Zimbra-First_step-GA_update
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/guide.pt-pt.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_domain_add_external01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_domain_add_external02.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_domain_add_internal01.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/images/zimbra_domain_add_internal02.png
  pages/web_cloud/email_and_collaborative_solutions/zimbra/getting_started_zimbra/meta.yaml
Labels: Translations

#7475 KevS-SK1897-Update-List-of-IP-adresses-for-WebHosting-TRANSLATIONS
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.de-de.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-asia.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-au.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-ca.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-gb.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-ie.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-sg.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.en-us.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.es-es.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.es-us.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.it-it.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.pl-pl.md
  pages/web_cloud/web_hosting/clusters_and_shared_hosting_IP/guide.pt-pt.md
Labels: Translations ONLY

#7477 Upd WinRescue SD
  pages/assets/screens/other/windows/windows_rdp.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/manager-rescue-windows-menu.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt1.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt2.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt3.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt4.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt5.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt6.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt7.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt8.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-disk-mgmt9.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-mode-006.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/rescue-mode-007.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/images/winresc_summ.png
  pages/bare_metal_cloud/dedicated_servers/rescue-customer-windows/meta.yaml
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/rescue_mode/guide.pl-pl.md
  pages/index.md
Labels: Translations

#7480 KevS-SK1901-FullUpdate-Change-owner-for-DomainDNS
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/general-information/change-owner.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/general-information/manage-contacts-and-owners.png
  pages/assets/screens/control_panel/product-selection/web-cloud/domain-dns/general-information/owner.png
  pages/web_cloud/domains/trade_domain/guide.fr-ca.md
  pages/web_cloud/domains/trade_domain/guide.fr-fr.md
Labels: Update request, Priority: Urgent
