Repository ovh/docs, pull requests merged in 2025-03, with the labels that each got.

#7597 [MKS] IOLB and Octavia LB guides
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/expose_your_applications_using_a_load_balancer/guide.pt-pt.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.de-de.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-asia.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-au.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-gb.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-ie.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-sg.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.en-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.es-es.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.es-us.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.fr-ca.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.fr-fr.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.it-it.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.pl-pl.md
  pages/public_cloud/containers_orchestration/managed_kubernetes/using-lb/guide.pt-pt.md
Labels: FIX, Minor update

#7600 Public Cloud Reversibility - Typo fix and links improvements
  links/public-cloud/block-storage
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.de-de.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.en-asia.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.en-au.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.en-ca.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.en-gb.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.en-ie.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.en-sg.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.en-us.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.es-es.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.es-us.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.fr-ca.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.fr-fr.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.it-it.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.pl-pl.md
  pages/account_and_service_management/reversibility/03-public-cloud-reversibility-policy/guide.pt-pt.md
Labels: FIX

#7599 VCD concepts - udpating table
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pt-pt.md
Labels: Minor update

#7589 Minor fixes on various guides
  pages/network/load_balancer/create_http_https/guide.en-asia.md
  pages/network/load_balancer/create_http_https/guide.en-au.md
  pages/network/load_balancer/create_http_https/guide.en-ca.md
  pages/network/load_balancer/create_http_https/guide.en-gb.md
  pages/network/load_balancer/create_http_https/guide.en-sg.md
  pages/network/load_balancer/create_http_https/guide.en-us.md
  pages/network/load_balancer/create_http_https/guide.fr-ca.md
  pages/network/load_balancer/create_http_https/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-07-creating-vrack/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-08-creating-vrack-with-api/guide.pt-pt.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.de-de.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-asia.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-au.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-gb.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-ie.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-sg.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.en-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.es-es.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.es-us.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-ca.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.fr-fr.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.it-it.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.pl-pl.md
  pages/public_cloud/public_cloud_network_services/getting-started-09-creating-vrack-with-openstack/guide.pt-pt.md
Labels: Do not merge yet, FIX, Translations, Quality Check

#7607 KevS-Typo-action-quickfixes
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.fr-fr.md
Labels: FIX

#7606 KevS-Typo-action-quickfixes
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-ca.md
  pages/web_cloud/web_hosting/faq-web_hosting/guide.fr-fr.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.fr-ca.md
  pages/web_cloud/web_hosting/multisites_website_not_installed/guide.fr-fr.md
Labels: FIX

#7611 VCD post-migration - Minor adjustments
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_post_migration/guide.pt-pt.md
Labels: FIX

#7608 KevS-SK1941-Update-DNSSEC-for-DomainDNS
  pages/web_cloud/domains/dns_dnssec/guide.de-de.md
  pages/web_cloud/domains/dns_dnssec/guide.en-asia.md
  pages/web_cloud/domains/dns_dnssec/guide.en-au.md
  pages/web_cloud/domains/dns_dnssec/guide.en-ca.md
  pages/web_cloud/domains/dns_dnssec/guide.en-gb.md
  pages/web_cloud/domains/dns_dnssec/guide.en-ie.md
  pages/web_cloud/domains/dns_dnssec/guide.en-sg.md
  pages/web_cloud/domains/dns_dnssec/guide.en-us.md
  pages/web_cloud/domains/dns_dnssec/guide.es-es.md
  pages/web_cloud/domains/dns_dnssec/guide.es-us.md
  pages/web_cloud/domains/dns_dnssec/guide.fr-ca.md
  pages/web_cloud/domains/dns_dnssec/guide.fr-fr.md
  pages/web_cloud/domains/dns_dnssec/guide.it-it.md
  pages/web_cloud/domains/dns_dnssec/guide.pl-pl.md
  pages/web_cloud/domains/dns_dnssec/guide.pt-pt.md
Labels: Minor update, Translations

#7613 feat(block storage further): add guide in further section
  pages/public_cloud/compute/volume-backup/guide.de-de.md
  pages/public_cloud/compute/volume-backup/guide.en-asia.md
  pages/public_cloud/compute/volume-backup/guide.en-au.md
  pages/public_cloud/compute/volume-backup/guide.en-ca.md
  pages/public_cloud/compute/volume-backup/guide.en-gb.md
  pages/public_cloud/compute/volume-backup/guide.en-ie.md
  pages/public_cloud/compute/volume-backup/guide.en-sg.md
  pages/public_cloud/compute/volume-backup/guide.en-us.md
  pages/public_cloud/compute/volume-backup/guide.es-es.md
  pages/public_cloud/compute/volume-backup/guide.es-us.md
  pages/public_cloud/compute/volume-backup/guide.fr-ca.md
  pages/public_cloud/compute/volume-backup/guide.fr-fr.md
  pages/public_cloud/compute/volume-backup/guide.it-it.md
  pages/public_cloud/compute/volume-backup/guide.pl-pl.md
  pages/public_cloud/compute/volume-backup/guide.pt-pt.md
Labels: Minor update

#7617 VoIP - Softcall - Link fix
  pages/web_cloud/phone_and_fax/voip/installer_configurer_softcall/guide.fr-fr.md
Labels: FIX

#7616 VMware - SFTP connection - Guide retirement
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/deploiement_d_une_machine_virtuelle/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/SFTP.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/SFTP1.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/SFTP3.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/SFTP4.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/SFTP5.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/SFTP6.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/SFTP7.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/connection_sftp_browse_datastore.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/connection_sftp_filezilla.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/connection_sftp_filezilla_log.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/sftpconnection.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/images/sftpconnexion.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/sftp_connexion/meta.yaml
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vmware_datastore_upload/guide.pt-pt.md
  pages/index.md
Labels: Guides removal

#7601 BGPaaS Introduction
  pages/index-translations.de.yaml
  pages/index-translations.es.yaml
  pages/index-translations.fq.yaml
  pages/index-translations.fr.yaml
  pages/index-translations.it.yaml
  pages/index-translations.pl.yaml
  pages/index-translations.pt.yaml
  pages/index.md
  pages/network/bgp_service/bgp_service_config/guide.de-de.md
  pages/network/bgp_service/bgp_service_config/guide.en-asia.md
  pages/network/bgp_service/bgp_service_config/guide.en-au.md
  pages/network/bgp_service/bgp_service_config/guide.en-ca.md
  pages/network/bgp_service/bgp_service_config/guide.en-gb.md
  pages/network/bgp_service/bgp_service_config/guide.en-ie.md
  pages/network/bgp_service/bgp_service_config/guide.en-sg.md
  pages/network/bgp_service/bgp_service_config/guide.en-us.md
  pages/network/bgp_service/bgp_service_config/guide.es-es.md
  pages/network/bgp_service/bgp_service_config/guide.es-us.md
  pages/network/bgp_service/bgp_service_config/guide.fr-ca.md
  pages/network/bgp_service/bgp_service_config/guide.fr-fr.md
  pages/network/bgp_service/bgp_service_config/guide.it-it.md
  pages/network/bgp_service/bgp_service_config/guide.pl-pl.md
  pages/network/bgp_service/bgp_service_config/guide.pt-pt.md
  pages/network/bgp_service/bgp_service_config/images/bgpaas_basic-peering.png
  pages/network/bgp_service/bgp_service_config/images/bgpaas_rs-peering.png
  pages/network/bgp_service/bgp_service_config/images/shadow_bgpaas_rs-peering.png
  pages/network/bgp_service/bgp_service_config/meta.yaml
Labels: Guide creation, Do not merge yet

#7594 SK-1788-WEB-Emails-emailpro-outlook-ios-Translation
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.en-gb.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.en-ie.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.fr-fr.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/email_pro/how_to_configure_outlook_ios/guide.pt-pt.md
Labels: Translations ONLY

#7623 Load Balancer - en-us FAQ update to trigger fix on INC-0270624
  pages/network/load_balancer/create_faq/guide.en-us.md
Labels: FIX

#7622 Alpha disclaimer + H6 titles change
  pages/network/bgp_service/bgp_service_config/guide.de-de.md
  pages/network/bgp_service/bgp_service_config/guide.en-asia.md
  pages/network/bgp_service/bgp_service_config/guide.en-au.md
  pages/network/bgp_service/bgp_service_config/guide.en-ca.md
  pages/network/bgp_service/bgp_service_config/guide.en-gb.md
  pages/network/bgp_service/bgp_service_config/guide.en-ie.md
  pages/network/bgp_service/bgp_service_config/guide.en-sg.md
  pages/network/bgp_service/bgp_service_config/guide.en-us.md
  pages/network/bgp_service/bgp_service_config/guide.es-es.md
  pages/network/bgp_service/bgp_service_config/guide.es-us.md
  pages/network/bgp_service/bgp_service_config/guide.fr-ca.md
  pages/network/bgp_service/bgp_service_config/guide.fr-fr.md
  pages/network/bgp_service/bgp_service_config/guide.it-it.md
  pages/network/bgp_service/bgp_service_config/guide.pl-pl.md
  pages/network/bgp_service/bgp_service_config/guide.pt-pt.md
Labels: Minor update

#7627 [EN-GB]-VCD-Network concepts
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd_network_concepts/guide.pt-pt.md
Labels: Minor update

#6628 SAP on SecNumCloud
  links/network/ovhcloud-connect
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.pt-pt.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/images/concept-sap-vmware-secnumcloud.png
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/meta.yaml
  pages/index.md
Labels: Guide creation

#7630 fix: sap
  links/hosted-private-cloud/sap-hana
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_dedicated_server_and_hpc/guide.pt-pt.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_sap_on_secnumcloud/guide.pt-pt.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/concept_vmware_for_sap/guide.pt-pt.md
Labels: FIX

#7631 Reorganize & clarify WinPW reset procedures SD
  pages/bare_metal_cloud/dedicated_servers/changing-admin-password-on-windows/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/changing-admin-password-on-windows/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/changing-admin-password-on-windows/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/changing-admin-password-on-windows/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/changing-admin-password-on-windows/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/changing-admin-password-on-windows/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/changing-admin-password-on-windows/meta.yaml
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/firewall_network/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/network_security_dashboard/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/rcw-changing-admin-password-on-windows/guide.pt-pt.md
Labels: Minor update, Translations

#7633 vROps alert via SMTP - updating recommended port
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vrops_monitoring_by_smtp/guide.pt-pt.md
Labels: Minor update

#7614 FR update overthebox version matrix
  pages/web_cloud/internet/overthebox/config_upgrade/guide.fr-fr.md
Labels: Minor update

#7625 SK-1957-WEB-Emails-migrate-MXplan_to_Zimbra-TRANSLATION
  pages/web_cloud/email_and_collaborative_solutions/zimbra/migrate_mxplan_to_zimbra/guide.de-de.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/migrate_mxplan_to_zimbra/guide.es-es.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/migrate_mxplan_to_zimbra/guide.it-it.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/migrate_mxplan_to_zimbra/guide.pl-pl.md
  pages/web_cloud/email_and_collaborative_solutions/zimbra/migrate_mxplan_to_zimbra/guide.pt-pt.md
Labels: Translations ONLY

#7643 Technical capabilities and limitations of Public VCF aaS - Guide creation
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/meta.yaml
  pages/index.md
Labels: Guide creation

#7644 [AI Endpoints] - Troubleshooting guide
  pages/index.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_03_troubleshooting/meta.yaml
Labels: Guide creation

#7646 IPv6 in vRack - Minor edits + French translation
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/configure-an-ipv6-in-a-vrack/guide.pt-pt.md
Labels: Do not merge yet

#7634 FB - End of copper FTTH
  pages/index.md
  pages/web_cloud/internet/internet_access/comment_changer_mon_offre_xdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_commander_et_gerer_un_bloc_ip_29/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_demenager_mon_acces_xdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/comment_resilier_mon_acces_xdsl/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/configuration_du_modem_a_partir_de_votre_espace_client/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/end_of_copper_migration_ftth/guide.fr-fr.md
  pages/web_cloud/internet/internet_access/end_of_copper_migration_ftth/images/changement-offre-fibre.png
  pages/web_cloud/internet/internet_access/end_of_copper_migration_ftth/images/info-fermeture-cuivre.png
  pages/web_cloud/internet/internet_access/end_of_copper_migration_ftth/images/services2023.png
  pages/web_cloud/internet/internet_access/end_of_copper_migration_ftth/meta.yaml
Labels: Guide creation

#7656 Public VCF aaS limitations - Updating general limitations table
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vcd-limitations/guide.pt-pt.md
Labels: Minor update

#7659 [EN]-KMS-grammatical fixes
  pages/manage_and_operate/kms/kms-kmip/guide.de-de.md
  pages/manage_and_operate/kms/kms-kmip/guide.en-asia.md
  pages/manage_and_operate/kms/kms-kmip/guide.en-au.md
  pages/manage_and_operate/kms/kms-kmip/guide.en-ca.md
  pages/manage_and_operate/kms/kms-kmip/guide.en-gb.md
  pages/manage_and_operate/kms/kms-kmip/guide.en-ie.md
  pages/manage_and_operate/kms/kms-kmip/guide.en-sg.md
  pages/manage_and_operate/kms/kms-kmip/guide.en-us.md
  pages/manage_and_operate/kms/kms-kmip/guide.es-es.md
  pages/manage_and_operate/kms/kms-kmip/guide.es-us.md
  pages/manage_and_operate/kms/kms-kmip/guide.fr-ca.md
  pages/manage_and_operate/kms/kms-kmip/guide.fr-fr.md
  pages/manage_and_operate/kms/kms-kmip/guide.it-it.md
  pages/manage_and_operate/kms/kms-kmip/guide.pl-pl.md
  pages/manage_and_operate/kms/kms-kmip/guide.pt-pt.md
  pages/manage_and_operate/kms/kms-usage/guide.de-de.md
  pages/manage_and_operate/kms/kms-usage/guide.en-asia.md
  pages/manage_and_operate/kms/kms-usage/guide.en-au.md
  pages/manage_and_operate/kms/kms-usage/guide.en-ca.md
  pages/manage_and_operate/kms/kms-usage/guide.en-gb.md
  pages/manage_and_operate/kms/kms-usage/guide.en-ie.md
  pages/manage_and_operate/kms/kms-usage/guide.en-sg.md
  pages/manage_and_operate/kms/kms-usage/guide.en-us.md
  pages/manage_and_operate/kms/kms-usage/guide.es-es.md
  pages/manage_and_operate/kms/kms-usage/guide.es-us.md
  pages/manage_and_operate/kms/kms-usage/guide.fr-ca.md
  pages/manage_and_operate/kms/kms-usage/guide.fr-fr.md
  pages/manage_and_operate/kms/kms-usage/guide.it-it.md
  pages/manage_and_operate/kms/kms-usage/guide.pl-pl.md
  pages/manage_and_operate/kms/kms-usage/guide.pt-pt.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.de-de.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.en-asia.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.en-au.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.en-ca.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.en-gb.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.en-ie.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.en-sg.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.en-us.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.es-es.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.es-us.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.it-it.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.pl-pl.md
  pages/manage_and_operate/kms/responsibility-model-kms/guide.pt-pt.md
Labels: FIX

#7662 INC-0281700 - PL translation fix for Tutorials
  pages/index-translations.pl.yaml
Labels: FIX

#7651 fix(update hostname): update guide for changeing the hostname of an instance
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.de-de.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.en-asia.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.en-au.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.en-ca.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.en-gb.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.en-ie.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.en-sg.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.en-us.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.es-es.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.es-us.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.fr-ca.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.fr-fr.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.it-it.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/changing_the_hostname_of_an_instance/guide.pt-pt.md
Labels: FIX

#7650 fix(block storage): update index
  pages/index.md
Labels: FIX

#7661 Ag object user mgmt
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_identity_and_access_management/guide.pt-pt.md
Labels: Minor update, Priority: Low

#7637 feat(3az ref archietcture): create EN and FR guides
  pages/index.md
  pages/public_cloud/compute/3az_ref_architecture/guide.de-de.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-asia.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-au.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-ca.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-gb.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-ie.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-sg.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-us.md
  pages/public_cloud/compute/3az_ref_architecture/guide.es-es.md
  pages/public_cloud/compute/3az_ref_architecture/guide.es-us.md
  pages/public_cloud/compute/3az_ref_architecture/guide.fr-ca.md
  pages/public_cloud/compute/3az_ref_architecture/guide.fr-fr.md
  pages/public_cloud/compute/3az_ref_architecture/guide.it-it.md
  pages/public_cloud/compute/3az_ref_architecture/guide.pl-pl.md
  pages/public_cloud/compute/3az_ref_architecture/guide.pt-pt.md
  pages/public_cloud/compute/3az_ref_architecture/images/2az-with-local-storage.png
  pages/public_cloud/compute/3az_ref_architecture/images/2az-with-regional-storage.png
  pages/public_cloud/compute/3az_ref_architecture/meta.yaml
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.de-de.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-asia.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-au.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-ca.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-gb.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-ie.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-sg.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.en-us.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.es-es.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.es-us.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.fr-ca.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.fr-fr.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.it-it.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.pl-pl.md
  pages/public_cloud/compute/deployment_modes_comparison_resilience_details/guide.pt-pt.md
Labels: Guide creation, Priority: High

#7664 SAP - Placeholder for Installation Wizard upcoming guide
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.de-de.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.en-asia.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.en-au.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.en-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.en-gb.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.en-ie.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.en-sg.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.en-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.es-es.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.es-us.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.fr-ca.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.fr-fr.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.it-it.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.pl-pl.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/guide.pt-pt.md
  pages/hosted_private_cloud/sap_on_ovhcloud/installation-wizard/meta.yaml
  pages/index.md
Labels: Guide creation

#7665 3AZ Resilience - Header fix
  pages/public_cloud/compute/3az_ref_architecture/guide.de-de.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-asia.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-au.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-ca.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-gb.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-ie.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-sg.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-us.md
  pages/public_cloud/compute/3az_ref_architecture/guide.es-es.md
  pages/public_cloud/compute/3az_ref_architecture/guide.es-us.md
  pages/public_cloud/compute/3az_ref_architecture/guide.fr-ca.md
  pages/public_cloud/compute/3az_ref_architecture/guide.fr-fr.md
  pages/public_cloud/compute/3az_ref_architecture/guide.it-it.md
  pages/public_cloud/compute/3az_ref_architecture/guide.pl-pl.md
  pages/public_cloud/compute/3az_ref_architecture/guide.pt-pt.md
Labels: FIX

#7610 feat(block storage): add explanations about volume type
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.de-de.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-asia.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-au.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-gb.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-ie.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-sg.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.en-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-es.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.es-us.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-ca.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.fr-fr.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.it-it.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pl-pl.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pt-pt.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/images/volume-types.png
Labels: Minor update

#7667 fix(3az architecture): update typo
  pages/public_cloud/compute/3az_ref_architecture/guide.de-de.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-asia.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-au.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-ca.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-gb.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-ie.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-sg.md
  pages/public_cloud/compute/3az_ref_architecture/guide.en-us.md
  pages/public_cloud/compute/3az_ref_architecture/guide.es-es.md
  pages/public_cloud/compute/3az_ref_architecture/guide.es-us.md
  pages/public_cloud/compute/3az_ref_architecture/guide.fr-ca.md
  pages/public_cloud/compute/3az_ref_architecture/guide.fr-fr.md
  pages/public_cloud/compute/3az_ref_architecture/guide.it-it.md
  pages/public_cloud/compute/3az_ref_architecture/guide.pl-pl.md
  pages/public_cloud/compute/3az_ref_architecture/guide.pt-pt.md
Labels: FIX

#7612 feat(block storage increasing size): add explanations about how see disk size .. warning ..
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.de-de.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.en-asia.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.en-au.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.en-ca.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.en-gb.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.en-ie.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.en-sg.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.en-us.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.es-es.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.es-us.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.fr-ca.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.fr-fr.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.it-it.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.pl-pl.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/guide.pt-pt.md
  pages/public_cloud/compute/increase_the_size_of_an_additional_disk/meta.yaml
Labels: Minor update

#7670 Public Cloud - Compute - Links fix
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.de-de.md
  pages/public_cloud/compute/create_and_configure_an_additional_disk_on_an_instance/guide.pt-pt.md
Labels: FIX

#7675 Fix
  pages/assets/screens/control_panel/product-selection/bare-metal-cloud/vps/cp_kvm.png
Labels: FIX

#7653 SK-1968 - Customer/Internal Feedback - Update on network configurations for vrack on SD
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/guide.pt-pt.md
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/images/centos_alma_configuration.png
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/images/debian_configuration.png
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/images/netplan_configuration.png
  pages/bare_metal_cloud/dedicated_servers/vrack_configuring_on_dedicated_server/meta.yaml
Labels: Do not merge yet, FIX, Quality Check

#7679 fix(update instances size): new image for manager
  pages/public_cloud/compute/resize_instance_manager/images/template.png
Labels: FIX

#7681 feat(s3 managing object lock): add info
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.de-de.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.en-asia.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.en-au.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.en-ca.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.en-gb.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.en-ie.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.en-sg.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.en-us.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.es-es.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.es-us.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.fr-ca.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.fr-fr.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.it-it.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.pl-pl.md
  pages/storage_and_backup/object_storage/s3_managing_object_lock/guide.pt-pt.md
Labels: FIX

#7680 FB - Web hosting version details
  pages/index.md
  pages/web_cloud/web_hosting/web_hosting_main_info/guide.fr-fr.md
  pages/web_cloud/web_hosting/web_hosting_main_info/meta.yaml
Labels: Guide creation

#7686 Upd VPS FAQ
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.de-de.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-asia.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-au.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-ca.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-gb.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-ie.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-sg.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.en-us.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.es-es.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.es-us.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.fr-ca.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.fr-fr.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.it-it.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.pl-pl.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/guide.pt-pt.md
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/images/get-api.png
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/images/post-api.png
  pages/bare_metal_cloud/virtual_private_servers/vps-faq/meta.yaml
Labels: Translations
