Repository ovh/docs, pull requests merged in 2025-10, with the labels that each got.

#8465 KevS-SSL-management-quickfix
  pages/web_cloud/web_hosting/ssl_management/guide.es-es.md
  pages/web_cloud/web_hosting/ssl_management/guide.pt-pt.md
Labels: FIX

#8454 Guide Update - Understanding vScope SK-2356
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.de-de.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.en-asia.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.en-au.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.en-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.en-ie.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.en-sg.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.en-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.es-es.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.es-us.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.fr-ca.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.it-it.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.pl-pl.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/guide.pt-pt.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/gatewayPCC.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/img_364.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/img_366.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/img_367.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/img_368.jpg
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/managerLink.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope1.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope10.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope2.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope4.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope6.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope7.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/how_to_use_vscope/images/vScope8.png
Labels: Priority: High

#8442 FB - Rafiki unblock tcp out warning
  pages/index.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/guide.de-de.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/guide.en-gb.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/guide.es-es.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/guide.fr-fr.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/guide.it-it.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/guide.pl-pl.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/guide.pt.pt.md
  pages/web_cloud/web_hosting/resolve_anomalous-activity/meta.yaml
Labels: Guide creation, Translations, Priority: High

#8478 ESXi Install guide - clarity fix
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.de-de.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.en-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.es-es.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.es-us.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.fr-fr.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.it-it.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.pl-pl.md
  pages/bare_metal_cloud/dedicated_servers/esxi-partitioning/guide.pt-pt.md
Labels: FIX

#8477 100G update
  pages/network/ovhcloud_connect/occ-limits/guide.de-de.md
  pages/network/ovhcloud_connect/occ-limits/guide.en-asia.md
  pages/network/ovhcloud_connect/occ-limits/guide.en-au.md
  pages/network/ovhcloud_connect/occ-limits/guide.en-ca.md
  pages/network/ovhcloud_connect/occ-limits/guide.en-gb.md
  pages/network/ovhcloud_connect/occ-limits/guide.en-ie.md
  pages/network/ovhcloud_connect/occ-limits/guide.en-sg.md
  pages/network/ovhcloud_connect/occ-limits/guide.en-us.md
  pages/network/ovhcloud_connect/occ-limits/guide.es-es.md
  pages/network/ovhcloud_connect/occ-limits/guide.es-us.md
  pages/network/ovhcloud_connect/occ-limits/guide.fr-ca.md
  pages/network/ovhcloud_connect/occ-limits/guide.fr-fr.md
  pages/network/ovhcloud_connect/occ-limits/guide.it-it.md
  pages/network/ovhcloud_connect/occ-limits/guide.pl-pl.md
  pages/network/ovhcloud_connect/occ-limits/guide.pt-pt.md
Labels: Minor update

#8479 Minor fixes on some guides
  pages/account_and_service_management/account_information/phishing_care/guide.en-asia.md
  pages/account_and_service_management/account_information/phishing_care/guide.en-au.md
  pages/account_and_service_management/account_information/phishing_care/guide.en-ca.md
  pages/account_and_service_management/account_information/phishing_care/guide.en-sg.md
  pages/account_and_service_management/account_information/phishing_care/guide.en-us.md
  pages/account_and_service_management/account_information/phishing_care/guide.fr-ca.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.en-asia.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.en-au.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.en-ca.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.en-gb.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.en-ie.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.en-sg.md
  pages/bare_metal_cloud/dedicated_servers/replacing-user-password/guide.en-us.md
Labels: FIX

#8480 Index fix for Secret Manager
  pages/index.md
Labels: FIX

#8485 Guide creation - Vsphere rights - Sk-2225
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/guide.en-gb.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/guide.fr-fr.md
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/images/add-object-right.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/images/edit-rights-modal.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/images/remove-object-right.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/images/rights-by-datacentre.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/images/users-actions-menu.png
  pages/hosted_private_cloud/hosted_private_cloud_powered_by_vmware/vsphere_granular_rights/meta.yaml
  pages/index.md
Labels: Guide creation

#8489 [AI Notebooks] - Capabilities adds details to a sentence
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.de-de.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.en-au.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.en-us.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.es-es.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.es-us.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.it-it.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/notebook_guide_capabilities/guide.pt-pt.md
Labels: FIX

#8490 [AI Endpoints - Billing] - Replace table by OVHcloud official website link
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.de-de.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-asia.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-au.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-gb.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-ie.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-sg.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.en-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.es-es.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.es-us.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.fr-ca.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.fr-fr.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.it-it.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.pl-pl.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/guide.pt-pt.md
  pages/public_cloud/ai_machine_learning/endpoints_guide_04_billing_concept/images/pricing-overview.png
Labels: Minor update
